// Exam-level questions, set 4: securities & managed products (E7) and conflicts of interest & ethics (E9).
window.QB_HARD = window.QB_HARD || {};
(function () {
  const add = (k, list) => { window.QB_HARD[k] = (window.QB_HARD[k] || []).concat(list); };

  add("fixed", [
    ["An investor expects interest rates to rise significantly over the next year. She holds four Government of Canada securities and wants to sell the one most exposed to rising rates. Which holding is likely to lose the most value?",
      ["A 25-year strip bond", "A 25-year bond with a 5% coupon", "A 3-year bond with a 5% coupon", "A 6-month Treasury bill"],
      "Long maturity and no coupon give a strip the highest duration, so the largest price drop when rates rise.", "s"],
    ["A corporate treasurer must invest $5 million of surplus cash for 90 days. She's choosing between Government of Canada T-bills and commercial paper issued by a large, highly rated Canadian company. Which statement best describes the trade-off?",
      ["Commercial paper usually yields a bit more, because it carries the issuer's credit risk",
         "Commercial paper usually yields less, because the Bank of Canada guarantees its repayment",
         "T-bills usually yield more, because they're less liquid than commercial paper",
         "There's no meaningful difference, because both are money market instruments"],
      "Commercial paper is unsecured corporate debt; the extra yield compensates for credit and liquidity risk.", "s"],
    ["A client bought a callable corporate bond paying a 6% coupon five years ago. Since then, market yields on similar bonds have fallen to 3.5%. The bond has eight years left to maturity. What is the main risk the client now faces?",
      ["The bond may be called, forcing her to reinvest at lower rates",
       "The bond's price will fall sharply as yields keep declining",
       "The coupon will automatically reset to the new 3.5% market yield",
       "The bond's maturity will be extended to match current market rates"],
      "Issuers call bonds when rates fall, leaving holders with reinvestment risk and limiting price gains.", "s"],
    ["A client buys a 3-year bond with a 5% annual coupon at a price of 103 and plans to hold it to maturity. Which statement about its yield to maturity is correct?",
      ["It's below 5%, since the $3 premium is lost by maturity", "It's above 5%, since the bond trades above its par value", "It's exactly 5%, the same as the bond's coupon rate", "It can't be estimated without knowing the credit rating"],
      "Buying above par means the premium is lost at maturity, so YTM is below the coupon rate.", "c"],
    ["As a recession deepens, the yield spread between BBB-rated corporate bonds and Government of Canada bonds widens from 1.5% to 3.5%. A client holds a portfolio of BBB corporate bonds. What does the wider spread mean for her holdings?",
      ["Their prices have fallen relative to government bonds as credit fears grew",
       "Their prices have risen relative to government bonds of the same maturity",
       "Their coupon payments have increased automatically to match the new spread",
       "Their credit ratings have been upgraded because their yields are now higher"],
      "Wider spreads mean investors demand more yield for credit risk, pushing corporate bond prices down relative to governments.", "s"],
    ["Which of the following is the best example of a cash equivalent?",
      ["A 91-day Government of Canada T-bill", "A 2-year Government of Canada bond", "A preferred share with a 5-year reset", "A 5-year non-redeemable GIC"],
      "Cash equivalents are very short-term, highly liquid, low-risk instruments."],
    ["A client in a high tax bracket buys a Government of Canada strip bond maturing in 10 years and holds it in her non-registered account. Which statement about its taxation is correct?",
      ["She pays tax each year on interest that accrues, even though none is paid to her",
       "No tax is owed until the strip matures and she receives the full face value",
       "The gain she receives at maturity is taxed as a capital gain at a 50% inclusion rate",
       "Strips are tax-free, because they're issued by the Government of Canada"],
      "Accrued interest on strips is taxable annually, which is why they're usually held in registered accounts.", "s"],
    ["A client compares three 10-year bonds: one issued by the Government of Canada, one by the Province of Ontario, and an A-rated debenture issued by a Canadian bank. How would their yields typically rank, from lowest to highest?",
      ["Government of Canada, Ontario, then the bank debenture", "Ontario, Government of Canada, then the bank debenture", "Bank debenture, Ontario, then the Government of Canada", "All three yield the same, since the maturity is the same"],
      "Yield rises with credit and liquidity risk: federal < provincial < corporate.", "s"]
  ]);

  add("equity", [
    ["A company is liquidated. After all creditors are paid, $10 million is left. The company has preferred shares with a total liquidation preference of $25 million, and 5 million common shares outstanding. How much do the common shareholders receive?",
      ["Nothing, because the preferred shares rank first and are owed more",
       "$10 million, split evenly between preferred and common shareholders",
       "$10 million, because the common shareholders own the company",
       "An amount based on the market value of each share class"],
      "Preferred shares rank ahead of common in liquidation. Common shareholders get only what's left after the preferred claims.", "c"],
    ["Felix, 62, wants a dividend-paying security that ranks ahead of common shares. He's worried that rising interest rates will hurt the value of fixed-income investments. Which security best fits?",
      ["A floating-rate preferred share", "A perpetual fixed-rate preferred share", "A common share of a large utility", "A 30-year Government of Canada strip bond"],
      "Floating-rate preferreds adjust their dividend with interest rates, reducing price sensitivity.", "s"],
    ["Sara owns shares of a small company that goes bankrupt owing its lenders and suppliers far more than its assets are worth. Creditors are pursuing every possible source of payment. What is the most Sara can lose?",
      ["The amount she invested in the shares", "Her investment, plus a share of the unpaid debts", "Nothing, because CIPF covers bankrupt companies", "Twice her investment, under shareholder liability rules"],
      "Limited liability means shareholders can't lose more than what they invested.", "s"],
    ["An investor wants to read a TSX-listed company's official annual financial statements, MD&A and recent material change reports before buying its shares. Where is the most reliable source?",
      ["SEDAR+", "SEDI", "The TSX's daily trading summary", "The company's social media accounts"],
      "SEDAR+ is the official system for public filings. SEDI holds insider trading reports.", "s"],
    ["A company declares a quarterly dividend with a record date of Thursday, March 12. The payment date is April 1. Under T+1 settlement, which purchase entitles the buyer to this dividend?",
      ["A purchase on Wednesday, March 11", "A purchase on Thursday, March 12", "A purchase on Friday, March 13", "Any purchase before April 1"],
      "Under T+1, the ex-dividend date is the record date. Buyers must buy before the ex-date.", "c"],
    ["A client is choosing between buying a company's common shares and buying its bonds. Which is a key disadvantage of the common shares?",
      ["No guaranteed income, and they rank last if the company is liquidated",
       "They can't be sold until the company reaches a set maturity date",
       "Shareholders are personally liable for the company's unpaid debts",
       "Shareholders can't benefit at all if the company grows its profits"],
      "Shares offer growth and voting rights but no promised payments, and they're the residual claim.", "s"],
    ["A Canadian client wants to buy shares of a company listed only on the New York Stock Exchange. She asks her Canadian advisor what to expect. Which answer is most accurate?",
      ["She can buy through her Canadian dealer, but faces currency risk and conversion costs",
       "She must open an account with a U.S. dealer before buying any U.S.-listed shares",
       "U.S.-listed shares can't legally be held in a Canadian investor's account",
       "She'll avoid all U.S. withholding tax on dividends, whatever account she uses"],
      "Canadian dealers provide access to U.S. markets, but the investment is exposed to the USD/CAD exchange rate.", "s"],
    ["Paul has held REIT units in his non-registered account for 15 years. Much of each year's distribution has been classified as return of capital, and his adjusted cost base has gradually fallen to zero. This year, he receives another $2,000 of return of capital. What happens?",
      ["The $2,000 is treated as a capital gain this year",
       "Nothing, because return of capital is never taxable",
       "The negative ACB is carried forward until he sells",
       "The $2,000 is taxed in full as interest income"],
      "Return of capital lowers ACB. Once ACB would go below zero, the excess is deemed a capital gain.", "c"]
  ]);

  add("funds", [
    ["During a market panic, a corporate bond ETF trades at a 6% discount to its published NAV for several days, while many of the bonds it holds barely trade. A client asks why. What is the most likely explanation?",
      ["The ETF's price reflects live trading, while the NAV relies on stale bond prices",
         "The ETF manager made an error when calculating the fund's NAV during that week",
         "The ETF had to sell its bonds at a 6% loss that day to meet redemptions",
         "ETFs are required to trade at a discount whenever markets are falling"],
      "When underlying markets are illiquid, an ETF's exchange price can move away from NAV, reflecting real-time price discovery.", "s"],
    ["Nadia, 44, may need to access her investment on short notice to help her parents, and wants to be able to sell within a day at a price close to its underlying value. Which product best fits?",
      ["A conventional mutual fund", "A closed-end fund", "A hedge fund with quarterly redemptions", "A 6-year principal-protected note"],
      "Mutual funds redeem at NAVPS on demand. Closed-end funds may trade at discounts, and hedge funds and PPNs have limited liquidity.", "s"],
    ["A client holds a segregated fund contract and a mutual fund in an account at an investment dealer. She asks what protection she has if the insurance company or the dealer fails. Which statement is correct?",
      ["Assuris covers the segregated fund; CIPF may cover the dealer-held mutual fund",
         "CDIC covers both the segregated fund and the mutual fund up to $100,000 each, per institution",
         "CIPF covers the segregated fund, and Assuris covers the mutual fund",
         "Neither product has any protection if the insurer or the dealer fails"],
      "Segregated funds are insurance contracts, protected by Assuris. CIPF protects client property held at insolvent CIRO members.", "s"],
    ["An accredited investor is considering a hedge fund sold under an offering memorandum. Which feature is most characteristic of this kind of fund?",
      ["Limited liquidity, such as lock-ups, plus performance fees",
         "Daily redemptions at NAV, with strict regulatory limits on leverage",
         "A guarantee of principal at maturity provided by the issuing bank",
         "A required listing on the TSX, with units trading throughout the day"],
      "Hedge funds sold to accredited investors often restrict liquidity, use leverage and charge performance fees.", "s"],
    ["A client is comparing a hedge fund sold under an exemption with a liquid alternative mutual fund that uses similar strategies. What distinguishes the liquid alternative fund?",
      ["It's sold by prospectus to retail investors, offers regular liquidity, and has leverage limits",
         "It can only be sold to accredited investors, and it has no investment restrictions of any kind",
         "It must hold only cash and government bonds, despite its alternative strategy name",
         "It can't charge any performance fee, under any circumstances or conditions"],
      "Liquid alts bring alternative strategies under NI 81-102, with caps on leverage, borrowing and short selling.", "s"],
    ["A bank sells a principal-protected note linked to the S&P/TSX 60. It has a 6-year term, a cap on returns, and no guaranteed secondary market. Which statement about its risks is most accurate?",
      ["Principal is repaid at maturity only if the bank can pay, and selling early may mean a loss",
         "Principal is guaranteed by CDIC, so the investor can't lose money under any possible scenario",
         "The investor receives the index's full return, with no cap or other limit on gains",
         "The note can be redeemed at its full par value on any business day before maturity"],
      "PPN protection depends on the issuer's credit and applies only at maturity. Returns may be capped and liquidity is limited.", "s"],
    ["Mia wants bitcoin exposure in her RRSP. She already owns some bitcoin in a personal crypto wallet. Which approach is generally available?",
      ["Buying a crypto asset ETF listed on a Canadian exchange inside the RRSP",
       "Transferring the bitcoin from her personal wallet directly into the RRSP",
       "Buying bitcoin directly on a crypto trading platform through the RRSP",
       "Holding bitcoin futures contracts directly inside the RRSP account"],
      "Exchange-listed crypto ETFs can be qualified investments for registered plans; crypto held directly can't.", "s"],
    ["A client wants to buy crypto assets directly on a crypto trading platform. Which risk is especially important for her to understand?",
      ["High volatility, and possible losses if the platform or custodian fails",
         "That her crypto assets are protected by CIPF up to a $1 million limit",
         "That crypto prices are set each day by the Bank of Canada",
         "That gains on crypto assets are always tax-free for Canadian residents"],
      "Crypto assets are highly volatile, and platform or custody failures can cause losses. CIPF doesn't protect them.", "s"],
    ["A client places a buy order for a mutual fund at 2:00 p.m. on a business day, when markets have risen sharply. The fund calculates its NAVPS once a day, after markets close at 4:00 p.m. What price will she pay?",
      ["The NAVPS calculated at 4:00 p.m. that day", "The NAVPS from the previous business day", "The NAVPS at 2:00 p.m. when she ordered", "The next morning's market opening price"],
      "Forward pricing means orders get the next NAVPS calculated after the order is received.", "s"],
    ["Which statement best describes how a closed-end fund raises money and how investors later buy or sell units?",
      ["It raises money in an IPO; afterward, investors trade units on an exchange",
       "It issues new units every day to anyone who wants to invest in the fund",
       "It redeems units from investors at the NAVPS whenever they ask",
       "Its units can't be traded on a stock exchange once they're issued"],
      "Closed-end funds have a fixed number of units after the IPO, so their price reflects market supply and demand."],
    ["Ahmed is choosing between buying a rental condo and investing the same amount in a diversified REIT. Which is a key advantage of the REIT?",
      ["Diversification across many properties, and liquidity through exchange trading",
         "A distribution level that is guaranteed to investors by provincial law",
         "Complete insulation from changes in interest rates and borrowing costs",
         "Full control over which properties are bought, managed, rented out and sold"],
      "REIT units give diversified, liquid real estate exposure, but distributions aren't guaranteed and prices are rate-sensitive.", "s"],
    ["A client holds an ETF, a mutual fund and a segregated fund contract. She asks what summary disclosure documents she should have received. Which statement is correct?",
      ["ETF Facts, Fund Facts, and an information folder for the segregated fund",
         "The same Fund Facts document for all three, since they're all pooled investment products",
         "A disclosure document for the mutual fund only, since the other two are exempt",
         "A simplified prospectus for the segregated fund, filed with CIRO rather than an insurer"],
      "Each product type has its own disclosure regime. Segregated funds use an information folder (with fund facts) under insurance rules.", "s"],
    ["Olga holds a Canadian equity mutual fund in her non-registered account, with a large unrealized gain. Her advisor recommends switching to another fund in the same fund family. She assumes there's no tax because she's staying with the same company. What is the actual tax result?",
      ["The switch is a sale, so the capital gain is taxable this year",
       "No tax, because the switch stays within the same fund family",
       "No tax until she eventually sells the new fund she switched into",
       "The gain is taxed as interest income rather than a capital gain"],
      "Switching is a disposition for tax purposes in a non-registered account.", "s"]
  ]);

  add("tax", [
    ["Lena sells a stock at a loss in her non-registered account on November 10 to reduce her taxes. On November 25, her husband buys the same stock in his own non-registered account, unaware of her sale. What happens to Lena's capital loss?",
      ["It's denied as a superficial loss, because her spouse is an affiliated person",
       "It's allowed, because the purchase was made in a different person's account",
       "It's allowed, because more than 14 days passed between the two trades",
       "It's split equally between the two spouses for tax purposes"],
      "The superficial loss rule applies when the taxpayer or an affiliated person, including a spouse, buys the same property within 30 days before or after the sale.", "s"],
    ["A stock in Priya's TFSA has fallen from $20,000 to $8,000. She sells it, hoping to use the $12,000 loss. What can she do with the loss?",
      ["Nothing; losses inside a TFSA can't be claimed for tax",
       "Use it to offset capital gains in her non-registered account",
       "Carry it forward to offset future gains inside her TFSA",
       "Add the $12,000 to her TFSA contribution room next year"],
      "TFSA gains aren't taxed and losses can't be claimed. Contribution room depends on contributions and withdrawals, not losses.", "s"],
    ["Jordan borrows $50,000 on a line of credit and contributes it to his TFSA, which he invests in dividend-paying stocks. He asks whether he can deduct the interest on the loan. What is the answer?",
      ["No, interest on money borrowed for a TFSA isn't deductible",
       "Yes, interest on any loan used for investing is deductible",
       "Yes, but only half of the interest he pays is deductible",
       "Yes, as long as the TFSA holds dividend-paying stocks"],
      "Interest is deductible only when borrowing to earn taxable investment income. TFSAs and RRSPs don't qualify.", "s"],
    ["A client in a high tax bracket can earn $1,000 a year either as interest from a GIC or as eligible dividends from Canadian stocks, in a non-registered account. Ignoring risk, which statement about after-tax income is generally correct?",
      ["The dividends are taxed less than the interest, due to the dividend tax credit",
       "The interest is taxed less than the dividends, due to the GIC's CDIC coverage",
       "Both are taxed identically, at the client's full marginal tax rate",
       "The dividends are tax-free for clients in the highest tax bracket"],
      "The gross-up and dividend tax credit give eligible dividends a lower effective tax rate than interest.", "s"]
  ]);

  add("ethics", [
    ["A firm plans a new compensation grid that would pay advisors 20% more on sales of its in-house funds than on third-party funds. Its compliance team is reviewing the plan under the conflict of interest rules. What is the correct sequence?",
      ["Identify the conflict, assess whether it's material, then address it in clients' best interest or avoid it",
         "Disclose the conflict to all affected clients in writing, then implement the plan with no further review",
         "Implement the plan first, and then deal with any client complaints about it as they arise",
         "Ask CIRO to approve the plan, since CIRO approval means the conflict no longer needs to be managed"],
      "Firms must identify existing and reasonably foreseeable conflicts, assess materiality, and address material conflicts in clients' best interest, avoiding those they can't address.", "s"],
    ["When must a material conflict of interest be disclosed to an affected client?",
      ["Before the client acts on a recommendation it affects",
         "Only once a year, in the client's annual report on charges",
         "Only if the client specifically asks whether any conflicts exist",
         "Within 90 days after the trade that is affected by the conflict"],
      "Disclosure must be timely, prominent and specific, so the client can understand the conflict before making a decision."],
    ["After reviewing a conflict, a firm concludes that no combination of controls and disclosure would allow it to be managed in the client's best interest. What must the firm do?",
      ["Avoid the conflict", "Disclose it more prominently", "Get each client to sign a waiver", "Report the conflict to OBSI"],
      "Conflicts that can't be addressed in the client's best interest must be avoided."],
    ["Teresa, an advisor, is elected treasurer of her local community association, an unpaid role. It gives her signing authority over the association's bank account and control of its $300,000 reserve fund. She plans to start next week. What must she do?",
      ["Disclose it to her firm and get approval before starting",
       "Nothing, because the treasurer role is entirely unpaid",
       "Nothing, as long as she doesn't sell it any investments",
       "Only tell her clients about the role at their next review"],
      "Outside activities, including unpaid roles with financial authority or influence, must be disclosed to and approved by the firm.", "s"],
    ["Over lunch, Mark's close friend, an investment banker at the same firm, mentions that a client company is about to be acquired at a large premium. The deal hasn't been announced. Mark is a retail advisor. What should he do?",
      ["Not trade or tell anyone, and report the barrier breach to compliance",
         "Buy shares for his clients quickly, before the news becomes public knowledge",
         "Buy shares only in his own account, so that clients aren't involved",
         "Nothing, since the information came from someone within his own firm"],
      "Information barriers protect material non-public information. Possessing it means no trading or tipping, and the breach should be reported.", "s"],
    ["A firm approves a referral arrangement with a local accounting firm that will receive 10% of the first year's fees for each client it refers. Which information must referred clients receive?",
      ["The parties, key terms, conflicts, and how the fee is calculated",
       "Only that the accountant is a trusted local professional",
       "Only the total fees the firm expects to earn from each client",
       "Nothing, as long as the accountant pays the fee, not the client"],
      "Clients must receive written disclosure of the arrangement's material terms, including the fee, before the referral.", "s"],
    ["An advisor believes a particular fund is suitable for a client. It also pays her a higher commission than two similar funds the firm offers. Which action best reflects ethical conduct?",
      ["Recommend it only if it's genuinely the best option for the client, and be open about pay",
         "Recommend it, since it's suitable and suitability is the only test that must be met",
         "Recommend the lowest-commission fund in every case, to avoid any possible conflict",
         "Recommend it, but avoid discussing her compensation unless the client asks her directly"],
      "Suitability must put the client's interest first, and compensation conflicts must be addressed, not ignored.", "s"],
    ["A cautious client asks her advisor to explain a principal-protected note before buying it. Which description is most appropriate?",
      ["'Principal is repaid at maturity if the issuer can pay; returns aren't guaranteed, and early sale could lose money.'",
         "'It's fully guaranteed, so you can't lose any money no matter what happens in the markets or to the issuing bank.'",
         "'It works just like a GIC, so it's covered by CDIC deposit insurance up to the usual limit.'",
         "'You get the full return of the stock market, with no downside of any kind over the term.'"],
      "Communications must be fair and not misleading. The protection depends on the issuer and on holding to maturity.", "s"],
    ["On his personal social media account, an advisor posts glowing praise for a small company's stock. His firm is currently underwriting that company's share offering, which he doesn't mention. The post wasn't reviewed by his firm. What is the main problem?",
      ["It's an unapproved, misleading communication that hides a conflict of interest",
         "Personal social media accounts may never mention any specific securities at all",
         "Nothing, as long as the advisor doesn't personally own the stock",
         "Nothing, because he posted it outside business hours from home"],
      "Communications about securities must be approved and fair, and conflicts such as underwriting relationships must be disclosed.", "s"],
    ["A friend asks advisor Ken to introduce some of his clients to the friend's private start-up, which is raising money. Ken wouldn't be paid anything, and the investments wouldn't go through Ken's firm. What is the correct view?",
      ["It's still off-book activity, so it must not proceed outside the firm",
       "It's acceptable, because Ken wouldn't receive any compensation for it",
       "It's acceptable, as long as every client is an accredited investor",
       "It's acceptable, if Ken discloses the friendship to his clients first"],
      "Securities-related business must go through the firm, whether or not the advisor is paid.", "s"],
    ["A client asks her advisor to overstate her income on a form so that she qualifies as an accredited investor and can buy into a private placement she's excited about. She says she'll take full responsibility. What should the advisor do?",
      ["Refuse, and explain that she must actually meet the criteria for the exemption",
       "Help her, since the client has agreed to take responsibility for the form",
       "Help her, as long as the amount she invests in the placement is small",
       "Fill in the form as she asks, but have her sign it herself afterward"],
      "Falsifying information to fit an exemption is dishonest and illegal.", "s"],
    ["Advisor Lisa has become close friends with a wealthy client over many years. The client proposes that they jointly buy and run a small café, each investing $100,000. Under CIRO rules, which statement is most accurate?",
      ["It's a personal financial dealing that is generally restricted or prohibited",
         "It's allowed, since the client has also been a close personal friend for years",
         "It's allowed, as long as no securities are bought or sold between them",
         "It only needs to be disclosed if the café business ends up losing money"],
      "Personal financial dealings with clients create conflicts and are tightly restricted.", "s"],
    ["A firm requires employees to get pre-clearance for personal trades and bans trading in any security on its restricted list. What is the main purpose of these rules?",
      ["To prevent misuse of confidential information and trading ahead of clients",
         "To reduce the commissions that employees pay on their own personal trades",
         "To make sure employees invest primarily in the firm's own products",
         "To meet the conditions for the firm's CIPF membership and coverage"],
      "Personal trading controls address conflicts and protect client priority and confidential information."],
    ["An advisor could legally sell a client a complex product that technically fits the client's KYC. However, during their discussion, the client's questions suggest he doesn't really understand how it works. What does ethical practice require?",
      ["Make sure he understands it before proceeding, or recommend something else",
         "Proceed with the sale, since it's legal and fits the client's KYC information on paper",
         "Proceed with the sale, and note in the file that the client seemed confused",
         "Have the client sign a waiver acknowledging the risks, and then proceed"],
      "Ethics goes beyond technical compliance. Clients must understand what they're buying.", "s"],
    ["After a strong year, a wealthy client gives her advisor a $3,000 watch as a holiday gift. The firm's gift policy caps gifts from clients at $100. What should the advisor do?",
      ["Decline the gift, or report it and follow the firm's policy for gifts over the limit",
       "Accept it, since the client chose to give it freely as a personal holiday gift",
       "Accept it, and give the client a gift of similar value in return to keep it even",
       "Accept it, then sell it and donate the proceeds without telling the firm"],
      "Gift policies limit benefits that could compromise objectivity. Significant gifts must be declined or reported.", "s"],
    ["A firm uses part of its clients' trading commissions to pay for independent research that its portfolio managers use in managing those clients' accounts. What makes this practice acceptable?",
      ["The research benefits clients and the arrangement is properly disclosed",
       "The commissions charged are below the industry average for such trades",
       "The research providers are also clients of the firm's investment bank",
       "Nothing; using client commissions for research is always prohibited"],
      "Soft-dollar arrangements are permitted when the goods or services benefit clients and are disclosed."],
    ["Advisor Rob makes a trading error that costs a client $4,000. To avoid having it on his record, he offers to repay the client personally and asks her not to mention it. What is the correct view?",
      ["He must report it so the firm corrects it; private settlements are prohibited",
         "It's acceptable, since the client is fully compensated for the $4,000 she lost",
         "It's acceptable, if the client agrees to the arrangement in writing",
         "It's acceptable, since the amount is under the $5,000 reporting level"],
      "Errors and settlements must go through the firm so they're supervised and recorded.", "s"],
    ["Which of these situations creates a conflict of interest that a firm must identify and manage?",
      ["The firm earns more when clients hold its own funds than third-party funds",
       "A client asks for a printed copy of her most recent account statement",
       "An advisor attends a required continuing education course on ethics",
       "A client calls to update her mailing address after moving to a new home"],
      "Compensation differences between products are a classic conflict that must be identified and addressed."],
    ["Advisor Joanne holds a power of attorney for her 80-year-old mother, who is also one of her clients at the firm. Her firm's policy restricts advisors from holding POAs for clients. What is generally required?",
      ["Disclosure to and approval by the firm, which may allow a family exception",
       "Nothing, because family arrangements are a private matter for the family",
       "Moving her mother's account to a different dealer as soon as possible",
       "Getting CIRO's approval before each trade she makes for her mother"],
      "Restrictions on acting as a client's POA generally have family exceptions, but the firm must know and approve.", "s"],
    ["A client once asked her advisor to keep her account details private from her adult children. Two years later, the advisor's firm receives a court order requiring it to produce the client's account records for a legal proceeding. What should the advisor do?",
      ["Follow the firm's legal and compliance process to comply with the order",
       "Refuse, since she promised the client to keep the information private",
       "Ask the client's adult children to decide which records to produce",
       "Choose the documents she thinks are relevant, without telling compliance"],
      "Confidentiality has legal limits. Disclosure required by law should be handled through the firm.", "s"],
    ["An advisor recommends that a client move from a commission account to a fee-based account. The advisor's revenue from the account would roughly triple. The client makes about one trade a year. What should the advisor do?",
      ["Recommend it only if it's in the client's best interest, given her low activity and costs",
       "Recommend it anyway, since fee-based accounts are always more transparent for clients",
       "Recommend it, but avoid discussing the difference in cost unless she asks directly",
       "Make the switch without asking, since the fee is disclosed in the account agreement"],
      "Moving clients to fee-based accounts when it mainly benefits the advisor can be 'reverse churning,' a conflict to avoid.", "s"],
    ["Which approach to ethical decision-making best reflects industry expectations?",
      ["Weigh the facts, the people affected, the rules and the client's interest, and pick what you could defend publicly",
         "Choose whichever action maximizes the firm's revenue, as long as no specific rule is technically broken",
         "Follow whatever the most senior person in the branch decides, since they are accountable",
         "Choose the action that seems least likely to result in a client complaint or a regulatory review of any kind"],
      "Ethical decision-making weighs stakeholders, rules and fairness. The 'newspaper test' is a useful final check."],
    ["An advisor's brother runs a small portfolio management firm. The advisor starts steering clients who want managed accounts toward her brother's firm, without telling them about the relationship. The brother's firm pays her nothing. What is the main issue?",
      ["An undisclosed conflict of interest that could bias her recommendations",
         "Nothing, since she receives no payment from her brother's firm",
         "Nothing, as long as her brother's firm is properly registered as a portfolio manager",
         "Only a concern if the clients' managed accounts lose money"],
      "Personal relationships can bias advice even without payment, so the conflict must be addressed and disclosed.", "s"],
    ["A firm holds an annual sales contest. The top three advisors who sell the most units of a new structured note win a trip. What is the main ethical concern with this contest?",
      ["It encourages advisors to recommend the note whether or not it suits the client",
       "Sales contests are illegal for all Canadian investment dealers and advisors",
       "The trip must be reported to the CRA as a taxable benefit for each winner",
       "It reduces the firm's profit on the structured note during the contest"],
      "Incentives tied to selling specific products create conflicts that must be addressed or avoided.", "s"],
    ["An advisor learns that a colleague has been selling unapproved private investments to clients outside the firm for over a year. The colleague asks him to 'keep it between us.' What should the advisor do?",
      ["Report what he knows to compliance or his supervisor",
       "Keep it confidential, since it's the colleague's business",
       "Warn the colleague privately and give him a chance to stop",
       "Contact the colleague's clients himself to warn them"],
      "Registrants are expected to escalate misconduct such as off-book activity, which harms clients and the firm.", "s"],
    ["A client asks her advisor to buy shares in her brother's name so that her employer won't see she owns them. Her employer is a listed company, and she works in its finance department. What should the advisor do?",
      ["Refuse, since hiding ownership through a nominee is prohibited",
         "Proceed, as long as her brother agrees to hold the shares on her behalf",
         "Proceed, but only if the purchase is less than $10,000",
         "Open a joint account with her brother and buy the shares there instead"],
      "Trading through a nominee to hide beneficial ownership is prohibited, and here it may also conceal insider trading.", "s"],
    ["A firm discovers that one of its approved advisors has been acting as executor for several clients' estates and receiving executor fees. The clients aren't family members. What is the main concern?",
      ["A serious conflict that firm rules generally prohibit or restrict",
         "Nothing, since executor fees are reviewed and approved by the courts",
         "Only a tax issue, if the advisor didn't report the fees",
         "Nothing, provided the estates' accounts stay with the firm"],
      "Acting as executor, trustee or POA for non-family clients creates conflicts and opportunities for abuse.", "s"]
  ]);
})();
