// Exam-style questions (CIRE practice exam format), part 2: Element 3 scope of client relationships
// and Element 4 complaint handling. Format: [question, [correct, wrong, wrong, wrong], explanation, kind]
window.QB_HARD = window.QB_HARD || {};
(function () {
  const add = (k, list) => { window.QB_HARD[k] = (window.QB_HARD[k] || []).concat(list); };

  // ---------- Element 3: roles, KYC, appropriateness and suitability ----------
  add("kyc", [
    ["What does the account appropriateness obligation require a dealer to consider?",
      ["Whether the account type, such as fee-based, suits the client", "Whether each trade in the account suits the client's KYC profile", "Whether the client can afford the account's annual opening fee", "Whether the client's holdings are all listed on a Canadian exchange"],
      "Account appropriateness is about the type of account (fee-based or commission, advisory or managed, OEO) given the client's needs and expected activity. It includes explaining the features and costs of the account types. Suitability is about investment actions.", "r"],
    ["A client who rarely trades and holds mostly GICs is moved into a fee-based account charging 1.5% a year. What concern does this raise?",
      ["The account type may not be appropriate for her", "The trades in her account may involve front running", "She must now be classified as an institutional client", "Her holdings will no longer be covered by CIPF"],
      "Putting a buy-and-hold client into an asset-based fee account can cost her far more than commissions would ('reverse churning'). That is an account appropriateness problem.", "s"],
    ["How does account appropriateness differ from a suitability determination?",
      ["Appropriateness looks at the account type; suitability at investment actions", "Appropriateness covers institutional clients; suitability covers retail clients", "Appropriateness is reviewed yearly; suitability only when a client complains", "They are the same obligation, described in two different CIRO rules"],
      "Appropriateness asks whether the account type fits the client. Suitability asks whether a specific investment action (a trade, recommendation, transfer or deposit) fits the client.", "r"],
    ["Which event requires a dealer to determine suitability for a retail advisory account?",
      ["Securities are transferred in from another firm", "The client asks for a copy of last month's statement", "The market closes lower three days in a row", "The client's trusted contact person moves house"],
      "Suitability must be determined when a recommendation is made or an order accepted, when securities are deposited or transferred in, when the responsible representative changes and when there is a significant change in KYC information.", "r"],
    ["A client's Registered Representative retires and the account is assigned to a new RR. What should the new RR do?",
      ["Review the suitability of the account", "Wait until the client places a new order", "Close and reopen the account in their own name", "Rely fully on the previous RR's last assessment"],
      "A change in the representative responsible for an account triggers a suitability review.", "s"],
    ["Under the client-focused reforms, what must a suitability determination consider?",
      ["Costs and a reasonable range of alternatives", "Only the client's risk tolerance and current age", "The commission the dealer will earn on the trade", "Only the security's performance in the past three years"],
      "Suitability considers the client's KYC, the product (KYP), the impact on the account (concentration, liquidity), the potential and actual impact of costs, and a reasonable range of alternatives, and it must put the client's interest first.", "r"],
    ["A suitability determination must also confirm that the investment action does what?",
      ["Puts the client's interest first", "Earns the dealer a fair profit", "Has beaten its benchmark recently", "Has the accountant's approval"],
      "Under CIRO's rules and the client-focused reforms, a suitable investment action must put the client's interest ahead of the firm's and the representative's.", "r"],
    ["A client in an advisory account insists on buying a speculative stock that her RR believes is unsuitable. What must the RR do before acting on her instruction?",
      ["Explain why it's unsuitable, suggest an alternative, then get her instruction", "Refuse the order in all circumstances, since unsuitable trades are always prohibited", "Accept the order but record it in the file as a solicited recommendation", "Transfer the client to an order-execution-only account before placing it"],
      "If a client directs an unsuitable action, the representative must tell the client why it's not suitable, recommend a suitable alternative, and proceed only on the client's instruction, documenting each step.", "s"],
    ["A client with a medium risk tolerance asks to put 60% of her portfolio into one small-cap stock. Which suitability factor is the main concern?",
      ["Concentration", "The dividend tax credit", "Best execution", "The settlement date"],
      "Suitability must consider the impact of the action on the account, including concentration and liquidity. A 60% position in one small-cap stock is a major concentration risk.", "s"],
    ["A client needs $40,000 for a home down payment in six months. Which recommendation raises the biggest suitability concern?",
      ["A five-year non-redeemable GIC", "A high-interest savings ETF", "A Government of Canada T-bill", "A money market mutual fund"],
      "The client needs liquidity in six months. Money locked in a non-redeemable five-year GIC wouldn't be available when needed.", "s"],
    ["A dealer wants to assess suitability for a married couple at the household level. Which statement is true?",
      ["It's optional and supplements account-level suitability", "It replaces the need to assess each account separately", "It's required for every couple who holds a joint account", "It lets one spouse waive suitability for both of them"],
      "Household-level suitability is a supplementary approach a dealer may use with the clients' consent. It never replaces the account-level assessment.", "r"],
    ["Why doesn't a dealer determine suitability for trades in an order-execution-only (OEO) account?",
      ["OEO accounts give no recommendations, so clients decide", "OEO clients are all classified as institutional clients", "OEO trades are too small to need any regulatory review", "OEO accounts are exempt from every CIRO rule"],
      "OEO dealers execute client decisions without making recommendations, so there is no suitability determination. KYC (such as identity) and other rules still apply.", "r"],
    ["Which activity is NOT permitted for an order-execution-only dealer?",
      ["Recommending a specific stock to a client", "Executing a client's order to buy an ETF", "Providing general market data and tools", "Collecting the client's identity information"],
      "OEO dealers may provide general information and tools but may not make recommendations.", "r"],
    ["Before relying on a suitability waiver from a non-individual institutional client, what must the dealer reasonably conclude?",
      ["That it can evaluate recommendations independently", "That it has been profitable for three years in a row", "That it holds more than $100 million in total assets", "That it will never complain about investment losses"],
      "CIRO lets a dealer skip suitability for such a client if the dealer reasonably concludes the client can independently evaluate investment recommendations and the client confirms in writing that it doesn't need suitability determinations.", "r"],
    ["Suitability exemptions can depend on the type of account, service or client. Which is an exemption based on the type of client?",
      ["A non-individual institutional client's waiver", "An order-execution-only account", "A direct electronic access arrangement", "An order the client places on her own initiative, without any advice"],
      "Exemptions by client type cover sophisticated non-individual clients. OEO and DEA are exemptions by account type; unsolicited orders relate to the type of service.", "r"],
    ["Which activity is part of a Registered Representative's role but not an Investment Representative's?",
      ["Recommending investments", "Taking and entering orders", "Giving clients price quotes", "Reporting trade executions"],
      "Investment Representatives may answer enquiries, give quotes, take and enter orders, report on trades and correct errors, but they can't make recommendations.", "r"],
    ["A client calls an Investment Representative (IR) and asks whether she should buy a particular bank stock. How should the IR respond?",
      ["Explain IRs can't recommend and offer to refer her to an RR", "Recommend the stock if it fits her KYC information", "Read her the firm's research rating and urge her to buy", "Place the order and tell her it looks like a sound choice"],
      "IRs are prohibited from making investment recommendations. They can refer the client to a Registered Representative.", "s"],
    ["What must an Investment Representative confirm before entering a client's order?",
      ["The account, security, quantity, buy or sell, price and duration", "The client's outlook for the economy and the stock's prospects", "The client's tax bracket and the expected capital gain", "A branch manager's approval for each order"],
      "Accurate order details prevent errors: account number, security, buy or sell, quantity, order type and price, and how long the order stays open.", "r"],
    ["An IR enters a buy order for 1,000 shares when the client asked for 100. What should happen?",
      ["Report it under firm procedures; the client doesn't bear the cost", "Ask the client to keep the extra 900 shares at the price paid", "Cancel the trade directly with the counterparty, without asking for approval", "Sell the extra shares and keep any gain in the IR's own account"],
      "Errors are corrected through the firm's error procedures (usually an error account). The client must be put in the position they would have been in, and nobody may profit from the error.", "s"],
    ["When an investment dealer buys shares on an exchange to fill a client's order, in what capacity does it act?",
      ["As agent for the client", "As principal, from inventory", "As trustee for the shares", "As the client's fiduciary"],
      "Executing a client's order on a marketplace is an agency trade. When the dealer sells from or buys into its own inventory, it acts as principal.", "r"],
    ["A dealer sells a client a corporate bond from its own inventory. How does this differ from an agency trade?",
      ["The dealer is the counterparty and earns a markup", "The dealer must hold the bond in trust for a year", "The client has no right to a trade confirmation", "The dealer becomes the client's fiduciary for it"],
      "In a principal trade the dealer is on the other side of the trade and is paid through the price (a markup or markdown) rather than a commission. The confirmation must say the dealer acted as principal.", "r"],
    ["In which situation is a fiduciary duty most likely to arise?",
      ["A Portfolio Manager has discretion over the account", "An OEO client buys shares through an online platform", "An institutional client trades through a sales trader", "A client receives the firm's general market newsletter"],
      "Fiduciary duty arises where the advisor has discretion or the client is vulnerable and relies on the advisor's judgment. A discretionary Portfolio Manager must put the client's interest above all else.", "r"],
    ["Courts weigh several factors in deciding whether an advisor owed a client a fiduciary duty. Which is one?",
      ["The client's reliance on the advisor", "The size of the advisor's branch office", "Whether the account has a margin feature", "Whether the client named a trusted contact"],
      "Key factors include the client's vulnerability, trust and reliance on the advisor, the advisor's discretion, and any professional rules or policies.", "r"],
    ["Which of the following best describes a trust?",
      ["An arrangement where a trustee holds property for beneficiaries", "A type of corporation that pays no tax on its investment income", "A partnership in which every partner must also be a beneficiary", "An account that only the person who set it up can trade in"],
      "A trust is a relationship, not a separate legal person: the settlor transfers property to a trustee, who holds it for the benefit of the beneficiaries.", "r"],
    ["When opening an account for a family trust, which document is most important to review?",
      ["The trust deed", "The beneficiaries' tax returns", "The settlor's will", "The trustees' bank statements"],
      "The trust agreement (deed) sets out who the trustees are, what powers they have and what investments they may make.", "s"],
    ["Which item must be included in a dealer's relationship disclosure information (RDI)?",
      ["How the dealer assesses suitability", "The advisor's own personal holdings", "A forecast of portfolio returns", "The names of other clients"],
      "RDI describes the account types, products and services, their limits, the charges, conflicts, the suitability process, the reports the client will receive, the complaint process and how benchmarks are used.", "r"],
    ["When must relationship disclosure information be given to a new retail client?",
      ["Before the dealer first trades or advises", "Within 90 days after the account has been opened", "Only if the client asks for it in writing", "With the client's first annual performance report"],
      "RDI must be provided at or before account opening, before any trading or advice, and it must be in plain language.", "r"],
    ["A dealer changes its fee structure for advisory accounts. What must it do about relationship disclosure?",
      ["Notify clients of the significant change", "Nothing; RDI is only given once at opening", "Have each client reapply for an account", "File the new fees with CIRO for approval"],
      "When RDI content changes significantly, clients must be told in a timely manner, before the change takes effect where possible.", "s"],
    ["How often must a dealer take reasonable steps to update KYC information for a managed account?",
      ["At least every 12 months", "At least every 36 months", "At least every five years", "Only when the client reports a change"],
      "KYC must be updated at least every 12 months for managed accounts and at least every 36 months for other accounts where suitability applies, and whenever the dealer learns of a significant change.", "r"],
    ["A client tells his advisor he has inherited $2 million. What is the most appropriate step?",
      ["Update his KYC and review his account's suitability", "Invest the money right away under his existing KYC", "Report the inheritance to FINTRAC as a large transaction", "Wait for the next scheduled review to discuss it"],
      "A significant change in financial circumstances means the KYC must be updated and the suitability of the account reassessed.", "s"],
    ["A client tells her advisor by phone that she has lost her job. What should the advisor do?",
      ["Update her KYC and reassess suitability", "Wait for the next 36-month KYC update", "Note the call but take no further action", "Close the account, as she has no income"],
      "A job loss is a significant change in financial circumstances that may affect her risk capacity, time horizon and need for cash.", "s"]
  ]);

  // ---------- Element 3: services, KYP, escalation, styles, benchmarks, foreign clients ----------
  add("recs", [
    ["A client wants her advisor to make all investment decisions without calling her before each trade. Which service fits?",
      ["A managed (discretionary) account", "An advisory account", "An order-execution-only account", "A margin account"],
      "In a managed account, a Portfolio Manager makes decisions under a written managed account agreement. In an advisory account the client approves each trade.", "s"],
    ["In an advisory account, who makes the final investment decision?",
      ["The client, after hearing the advice", "The advisor, without client approval", "A portfolio manager at the firm", "The branch manager on review"],
      "The advisor recommends; the client decides. Trading without the client's approval in an advisory account is unauthorized trading.", "r"],
    ["A client moves from a full-service advisory account to an order-execution-only (OEO) account. What is the main effect on her experience?",
      ["Lower costs, but no recommendations or suitability review", "Lower costs, with the same recommendations she received before", "Her holdings lose CIPF protection in the new account", "She will no longer receive trade confirmations"],
      "OEO accounts are cheaper because the client makes her own decisions without advice. CIPF coverage and confirmations still apply.", "s"],
    ["A hedge fund wants financing, securities lending, custody and clearing from one dealer. Which service is it looking for?",
      ["Prime brokerage", "Underwriting", "Equity research", "M&A advisory"],
      "Prime brokerage bundles custody, financing (margin), securities lending and clearing for hedge funds and other active institutional traders.", "s"],
    ["What is the main purpose of a dealer's securities lending service?",
      ["Lending securities, often to short sellers, for a fee", "Lending cash to retail clients so they can buy on margin", "Lending the dealer's own capital to issuers in the weeks before an IPO", "Lending research reports to institutional clients for a fee"],
      "Securities lending lets institutions earn extra income by lending securities, typically to cover short sales, in exchange for collateral and a fee.", "r"],
    ["A company hires an investment dealer to help it sell new shares to the public. Which service is the dealer providing?",
      ["Underwriting", "Prime brokerage", "Securities lending", "Market making"],
      "Underwriting is helping issuers raise capital by distributing new securities, either on a bought-deal basis or a best-efforts basis.", "r"],
    ["A dealer's corporate finance team advises a client company on how to defend against a hostile take-over bid. Which institutional service is this?",
      ["Mergers and acquisitions advisory", "Underwriting a new share issue", "Institutional equity research", "Securities lending"],
      "M&A advisory covers advising on acquisitions, divestitures, take-over bids and defences, and fairness opinions.", "s"],
    ["Before an investment dealer makes a new structured note available to its clients, what must it do?",
      ["Assess its structure, risks and costs, then approve it", "Confirm the note will outperform the S&P/TSX Composite Index", "Confirm that it pays more commission than similar products on the shelf", "Get written approval from each client who may buy it"],
      "The product due diligence (know-your-product) obligation requires the dealer to assess and approve securities before making them available, and then monitor them.", "r"],
    ["After approving a product for its shelf, what does the dealer's product due diligence obligation require?",
      ["Monitoring it for significant changes", "No further review unless a client complains", "Guaranteeing its performance for a year", "Re-approving it only once it is sold out"],
      "Dealers must keep monitoring approved products and respond to significant changes, such as a change in risk, costs or the issuer's condition.", "r"],
    ["What does the know-your-product (KYP) obligation require of an Approved Person?",
      ["Understanding the costs and risks of each security they recommend", "Knowing the recent performance of every security that trades in Canada", "Holding each product they recommend in their own account first", "Recommending only products that are issued by their own dealer"],
      "Approved Persons must understand the structure, features, risks, costs and impact of costs of each security they purchase, sell or recommend for a client.", "r"],
    ["An advisor recommends a fund without understanding how its leverage and fees work. Which obligation has the advisor failed to meet?",
      ["Know-your-product", "Best execution", "Account appropriateness", "Trade confirmation"],
      "KYP requires understanding a security's structure, features, risks and costs before recommending it.", "s"],
    ["Besides understanding the products they recommend, the KYP obligation expects Approved Persons to understand what else?",
      ["How those products compare with others the dealer offers", "Every product sold by competing dealers across the country", "The personal portfolios of other advisors at the firm", "The issuer's internal budgets and staffing plans"],
      "To consider a reasonable range of alternatives, representatives need a general understanding of the products available through their dealer and how they compare.", "r"],
    ["A client asks her RR to help set up a covered call strategy. The RR isn't approved to deal in options. What should the RR do?",
      ["Escalate to an options-qualified colleague or supervisor", "Place the trades and learn about the strategy afterward", "Tell the client that options are too risky for anyone", "Suggest she open an online account at another dealer"],
      "Derivatives require specific proficiency and approval. Representatives must escalate to qualified internal experts rather than act outside their approval.", "s"],
    ["Which situation most clearly calls for escalation to an internal subject-matter expert?",
      ["A client asks about cross-border estate and tax issues", "A client wants a quote on a large bank stock", "A client wants a copy of last month's statement", "A client wants to buy a Government of Canada T-bill"],
      "Specialist questions (cross-border tax, estates, derivatives, complex products) should go to experts at the firm.", "s"],
    ["An elderly client seems confused and asks to wire a large sum to someone she met online. Whom should the advisor involve first?",
      ["The firm's supervisor or vulnerable client specialist", "The client's neighbour, who seems trustworthy", "The receiving bank, to cancel the transfer", "No one; the client's instructions must be followed"],
      "Possible financial exploitation or diminished capacity should be escalated under the firm's procedures. The firm may contact the trusted contact person or place a temporary hold.", "s"],
    ["Which of these is an active equity management style?",
      ["Sector rotation through the business cycle", "Holding an S&P/TSX Composite index fund", "Rebalancing a fixed basket to index weights", "Buying and holding a market-cap portfolio"],
      "Active styles try to beat a benchmark through security selection or timing (value, growth, sector rotation). Indexing and buy-and-hold are passive.", "r"],
    ["A manager looks for companies whose P/E and price-to-book ratios are low compared with their peers. Which style is this?",
      ["Value", "Growth", "Momentum", "Indexing"],
      "Value managers look for stocks that look cheap relative to fundamentals. Growth managers pay up for above-average earnings growth.", "r"],
    ["A bond manager expects interest rates to fall and lengthens the portfolio's duration. Which strategy is this?",
      ["Interest rate anticipation, an active strategy", "Laddering, a passive strategy for lengthening maturities", "Buy-and-hold, a passive strategy", "Indexing, a passive strategy that tracks the bond index"],
      "Interest rate anticipation positions the portfolio for an expected rate move. Lengthening duration increases the gain if rates fall.", "s"],
    ["A client wants a low-maintenance bond portfolio. She buys equal amounts maturing each year for ten years and reinvests each maturing bond at the long end. What is this approach?",
      ["A ladder, a passive strategy", "A barbell, an active strategy", "Rate anticipation, an active strategy", "Credit spread trading, an active strategy"],
      "A laddered portfolio spreads maturities evenly, which reduces reinvestment and interest rate risk with little management. It's a passive approach.", "s"],
    ["A client's portfolio is 60% Canadian large-cap stocks and 40% Canadian investment-grade bonds. Which benchmark is most relevant?",
      ["60% S&P/TSX Composite and 40% FTSE Canada Universe Bond", "The S&P 500 Index, measured in Canadian dollars to match the client", "The Dow Jones Industrial Average", "100% FTSE Canada Universe Bond Index"],
      "A benchmark should match the portfolio's asset mix and markets. A blended benchmark does that for a balanced portfolio.", "s"],
    ["Why should a benchmark used for performance reporting match the portfolio's investments?",
      ["So the comparison reflects similar risk and asset mix", "So the portfolio always looks favourable to the client", "Because regulators require the S&P 500 for all accounts", "So that fees can be deducted from the benchmark return"],
      "An inappropriate benchmark (for example, an equity index for a bond portfolio) gives a misleading picture of performance.", "r"],
    ["A dealer decides to include benchmark comparisons in its client reports. Which requirement applies?",
      ["Use relevant benchmarks and explain them in the relationship disclosure", "Get CIRO's approval for each benchmark before it is used in reports", "Use only the S&P/TSX Composite Index, for every type of client", "Show benchmarks only to institutional clients, never to retail clients"],
      "If benchmarks are used, they must be relevant and the relationship disclosure must explain how they are used to assess the client's investment performance.", "r"],
    ["A long-standing client moves permanently to Arizona and wants to keep trading through her Canadian advisor. What is the key issue?",
      ["US registration rules, or an exemption, now apply", "Nothing changes, since the account opened in Canada", "She must move all her holdings into a TFSA first", "She may only trade Government of Canada bonds"],
      "Once a client resides in the US, the dealer and representative must be registered there or rely on an exemption before trading with her.", "s"],
    ["When onboarding a client who lives outside Canada, which extra step is commonly required?",
      ["Confirming tax residency and whether local law allows it", "Getting the foreign embassy's approval for each trade in the account", "Limiting the client to cash and T-bills only", "Registering the client separately with CIPF"],
      "Dealers must collect tax residency self-certifications (for FATCA and CRS reporting) and check whether the client's home jurisdiction allows the dealer to deal with them.", "r"],
    ["A Registered Representative wants discretionary trading authority over a retail client's account. What is required?",
      ["The client's written authorization and the firm's approval", "A verbal agreement noted in the client's file", "Approval from the provincial regulator for each discretionary trade", "The consent of the client's trusted contact person"],
      "Discretionary accounts need prior written client authorization and approval by the dealer, and they are subject to closer supervision.", "r"],
    ["What must a client sign before a Portfolio Manager can manage her account on a fully discretionary basis?",
      ["A managed account agreement", "A margin account agreement", "A trusted contact consent form", "A risk acknowledgement form"],
      "The managed account agreement gives the Portfolio Manager discretionary authority and sets out the investment objectives and fees.", "r"]
  ]);

  // ---------- Element 4: complaint handling and reporting ----------
  add("complaints", [
    ["Within what time must a dealer acknowledge a retail client's complaint?",
      ["Five business days", "Thirty calendar days", "Ninety days", "Two business days"],
      "CIRO requires an acknowledgement within five business days, and a substantive response within 90 days.", "r"],
    ["A dealer can't send a substantive response to a complaint within 90 days. What must it do?",
      ["Tell the client why, give a new date and explain OBSI access", "Close the complaint file and open a new one under a new number", "Ask CIRO for a one-year extension to complete its investigation", "Offer a payment to settle the complaint before the deadline"],
      "The dealer must explain the delay and when it expects to respond. The client can take the complaint to OBSI once 90 days have passed.", "s"],
    ["Which of the following is a complaint that must be handled under the dealer's complaint procedures?",
      ["A phone call alleging trades were unsuitable", "A question about how to read a statement", "A request to change the mailing address", "A comment that markets were disappointing"],
      "Complaints can be verbal or written. An allegation about the dealer's or representative's conduct, such as unsuitable trades, must go through the complaint process.", "s"],
    ["A client complains that her advisor took four days to return her calls. How is this treated?",
      ["As a service complaint handled internally, not reported to CIRO", "As a complaint that must be reported to CIRO within 20 business days", "As not a complaint, so it doesn't need to be recorded", "As a matter to be referred directly to OBSI"],
      "Service issues (delays, rudeness) are handled and recorded under the firm's procedures but aren't among the matters reportable to CIRO.", "s"],
    ["Which complaint must a dealer report to CIRO?",
      ["An allegation that an advisor misappropriated funds", "A complaint about a slow website", "A complaint that a quarterly statement arrived two weeks late", "A complaint about branch parking"],
      "Serious allegations such as theft, fraud, misappropriation, forgery, money laundering, market manipulation, insider trading and unauthorized trading must be reported to CIRO.", "r"],
    ["What may happen if a dealer fails to report a reportable complaint to CIRO?",
      ["CIRO may discipline the firm", "The client automatically wins", "The CSA takes over the complaint", "Nothing; reporting is voluntary"],
      "Reporting is a regulatory obligation. Failing to report can lead to disciplinary action, including fines.", "r"],
    ["A client is unhappy with her dealer's final response to her complaint. Within what period must she take it to OBSI?",
      ["180 days of the response", "30 days of the response", "One year of the trade", "Six years of the trade"],
      "A client can go to OBSI within 180 days of the dealer's final response (or after 90 days if no response has been given).", "r"],
    ["Ninety days have passed since a client complained to her dealer, and she has had no substantive response. What can she do?",
      ["Take the complaint to OBSI", "Nothing until the dealer replies", "File a claim with CIPF", "Ask CIRO to order compensation"],
      "If the dealer hasn't responded within 90 days, the client may go directly to OBSI.", "s"],
    ["Which statement about the Ombudsman for Banking Services and Investments (OBSI) is correct?",
      ["It's free and can recommend up to $350,000", "Its decisions are binding on all parties", "It charges clients a fee based on the claim", "It handles complaints before the firm does"],
      "OBSI is free and independent. It can recommend compensation up to $350,000, but its recommendations aren't legally binding.", "r"],
    ["How does CIRO's arbitration program compare with OBSI?",
      ["Arbitration produces a decision binding on both sides", "Arbitration is free and its awards are never binding", "Arbitration only hears claims under $10,000", "Arbitration requires the client to hire a lawyer"],
      "Arbitration is a formal process with a binding decision, suited to more complex disputes, and it's usually faster and cheaper than court. Awards are capped at $500,000.", "r"],
    ["When is litigation most likely to be the preferred route for a client's complaint?",
      ["For a large claim needing a binding, uncapped judgment", "For a quick and free review of a simple complaint", "For a claim under $1,000 with straightforward facts", "For a guaranteed response within 90 days"],
      "Courts can award any amount and their judgments are binding, but litigation is slow and expensive.", "r"],
    ["A client asks CIRO to make her advisor repay her losses. What can CIRO generally do?",
      ["Investigate and discipline, but not award compensation", "Order the advisor to repay her losses in full, with interest", "Pay her claim from the CIPF fund", "Refer her claim to the Bank of Canada"],
      "CIRO's role is regulatory enforcement. Compensation routes include the firm, OBSI, arbitration and the courts.", "s"],
    ["What role do provincial securities regulators play in the complaints framework?",
      ["They oversee CIRO and enforce securities laws", "They resolve every retail complaint in 90 days", "They pay compensation on every proven complaint", "They handle only complaints about crypto platforms"],
      "Provincial regulators oversee CIRO's handling of complaints and enforcement and take their own action for breaches of securities law.", "r"],
    ["An advisor makes trades in a client's account without her authorization. What consequences could follow?",
      ["Civil liability and regulatory discipline", "Only an internal warning from the branch", "Nothing at all, if the trades made money", "Criminal charges against the client"],
      "Unauthorized trading can lead to a civil claim by the client, CIRO discipline and firm sanctions, whatever the trades' outcome.", "s"],
    ["A client sues her advisor, saying he ignored her clear instruction to sell a stock before it fell. What legal basis is she most likely relying on?",
      ["Negligence or breach of contract", "Insider trading by the advisor", "Market manipulation", "Breach of Canada's anti-spam law"],
      "Failing to follow instructions is a classic negligence or breach-of-contract claim. Other common bases include breach of fiduciary duty and misrepresentation.", "s"],
    ["A dealer's obligations to clients come from several sources. Which is a contractual obligation?",
      ["The terms of the client's account agreement", "The Criminal Code's prohibition on fraud", "PIPEDA's privacy requirements", "The PCMLTFA's transaction reporting rules"],
      "Contractual obligations come from agreements with the client. The others are legislative obligations.", "r"],
    ["An advisor offers to repay a complaining client's losses from his own pocket so the complaint goes away. Which statement is correct?",
      ["It's prohibited; the dealer must handle and approve any settlement", "It's acceptable as long as the client signs a confidentiality agreement", "It's required, so that the complaint never reaches OBSI", "It's acceptable for amounts under $5,000"],
      "Approved Persons can't settle complaints privately or pay clients from personal funds. Complaints and settlements must be handled and approved by the dealer.", "s"],
    ["A dealer settles a complaint with a client. Which settlement term is prohibited?",
      ["Stopping the client from reporting to regulators", "Stating the exact amount of the settlement payment", "Releasing the firm from further claims", "Requiring payment within 30 days"],
      "Settlement agreements can't restrict a client from reporting to, or cooperating with, regulators or law enforcement.", "r"],
    ["A dealer's compliance department is reviewing its complaint files. How long must it keep records of each complaint?",
      ["At least seven years", "Two years after closing", "Until the account closes", "As firm policy decides"],
      "Complaint records, including the investigation and response, must be kept for at least seven years.", "r"],
    ["How must a dealer handle complaints from institutional clients?",
      ["Under written procedures that differ from the retail rules", "Exactly as retail complaints, including referral to OBSI", "With no procedures, since institutional clients sue instead", "By forwarding them to CIRO, which resolves them on the client's behalf"],
      "Dealers must have procedures for institutional complaints, but the detailed retail process (such as OBSI access) doesn't all apply.", "r"],
    ["Which of the following must a dealer's complaint handling policies include?",
      ["A designated person responsible for complaints", "A filing fee charged to clients who complain", "A rule that complaints be made only in writing", "A $5,000 cap on any settlement"],
      "Dealers must designate a complaints officer, have written procedures, supervise complaint handling and keep records. Verbal complaints count too.", "r"],
    ["Several clients of the same advisor complain about undisclosed fees within a few months. What should the dealer's complaint process do with this information?",
      ["Identify the pattern and fix the underlying problem", "Treat each complaint separately and close each file", "Wait to see whether more clients complain", "Send each client a refund and take no other step"],
      "Complaint records should be analyzed for patterns that point to a supervision or compliance problem, which must then be addressed.", "s"]
  ]);
})();
