// Exam-style questions (CIRE practice exam format), part 5: Element 9 conflicts of interest and ethics.
// Format: [question, [correct, wrong, wrong, wrong], explanation, kind]
window.QB_HARD = window.QB_HARD || {};
(function () {
  const add = (k, list) => { window.QB_HARD[k] = (window.QB_HARD[k] || []).concat(list); };

  add("ethics", [
    ["Under the client-focused reforms, how must a dealer deal with a material conflict of interest?",
      ["Address it in the client's best interest, or avoid it", "Disclose it in the account documents, which is always enough", "Have the client sign a waiver that releases the dealer", "Report it to CIRO and continue with the transaction"],
      "Material conflicts must be identified and addressed in the client's best interest. If that isn't possible, the conflict must be avoided. Disclosure alone isn't enough.", "r"],
    ["A dealer believes that disclosing a conflict in its account opening documents is enough to manage it. What is wrong with this view?",
      ["Disclosure alone doesn't address the conflict for the client", "Conflicts of interest never need to be disclosed to clients in writing", "Disclosure of conflicts must always be given verbally", "Only CIRO is allowed to disclose a dealer's conflicts"],
      "Disclosure is required, but the dealer must also control or avoid the conflict so the client's interest comes first.", "r"],
    ["Which is an example of a reasonably foreseeable conflict that a firm should identify in advance?",
      ["A planned campaign paying bigger bonuses on in-house funds", "A client buying a stock that later goes up in price", "An advisor taking two weeks of vacation during the busy summer season", "A client moving to a new address in the same city"],
      "Firms must identify existing conflicts and those that are reasonably foreseeable, such as incentives that could bias recommendations.", "r"],
    ["A dealer pays advisors a higher payout on its own funds than on third-party funds. What is the main concern?",
      ["Advisors may favour in-house funds over better options", "Selling in-house funds to retail clients is illegal in Canada", "Third-party funds aren't subject to KYP review", "Clients can't hold in-house funds in an RRSP"],
      "Proprietary products and differential compensation are material conflicts. They must be controlled so recommendations rest on the client's interest.", "s"],
    ["An advisor wants to refer clients to an accountant in exchange for a referral fee. Which condition applies?",
      ["A written agreement through the dealer, disclosed to clients", "The fee may be paid to the advisor privately, in cash, with no record", "No disclosure is needed if the fee is under $500", "The client must pay the fee to the accountant"],
      "Referral arrangements must be set out in a written agreement with the dealer, recorded, and disclosed to clients in writing before the referral.", "s"],
    ["To whom must a referral fee earned through an Approved Person's referral be paid?",
      ["To the dealer", "To the Approved Person directly", "To the referred client", "To CIRO"],
      "All compensation for activity on behalf of clients must flow through the dealer, which may then pay the Approved Person.", "r"],
    ["An RR is invited to become a paid director of a local private company. What must she do first?",
      ["Report it to her dealer and get approval", "Nothing, as long as she does it on weekends", "Notify CIRO, but not her own dealer", "Ask each of her clients for written consent"],
      "Outside activities must be reported to the dealer and approved before they begin. The dealer then assesses conflicts and supervises.", "s"],
    ["When reviewing an Approved Person's request for an outside activity, which is a key consideration for the dealer?",
      ["Whether clients could be confused about who they're dealing with", "How much the outside activity will pay the Approved Person", "Whether the activity takes place in the same city as the branch", "Whether the Approved Person's spouse approves of the activity"],
      "The dealer considers conflicts of interest, potential client confusion, the time involved and its ability to supervise.", "r"],
    ["After approving an Approved Person's outside activity, what must the dealer do?",
      ["Supervise it and keep records", "Nothing further at all", "Report it to the CSA monthly", "Take a share of the income"],
      "Approval isn't the end: the dealer must supervise the activity appropriately and keep records of its approval and review.", "r"],
    ["An advisor is also treasurer of a local seniors' club, and several members start opening accounts with him. What concern arises?",
      ["He may be in a position of influence over these clients", "None, as long as each member signs a disclosure form", "He must become each member's power of attorney", "Clients over 65 can't open accounts with him"],
      "A position of influence over potential clients (such as a community, religious or care role) is a material conflict. It must be reported to the dealer and may require restricting or avoiding those client relationships.", "s"],
    ["An Approved Person holds a position of influence over people who could become clients. What is generally required?",
      ["Report it to the dealer, which must assess and restrict as needed", "Nothing, as long as the person is well respected in the community", "Ask those individuals to keep the relationship confidential", "Offer those individuals lower fees to compensate for the conflict"],
      "The dealer must treat it as a material conflict, require disclosure and restrict the person's dealings with those individuals where the conflict can't be addressed in their best interest.", "r"],
    ["A fund wholesaler offers an advisor playoff tickets worth $1,500. What should the advisor do?",
      ["Follow the gift policy, which likely means declining", "Accept, since gifts from wholesalers are normal practice", "Accept, and then give the tickets to one of his clients", "Accept, and promise to recommend the wholesaler's funds"],
      "Gifts and entertainment beyond modest value can compromise objectivity. Firms set limits and require reporting.", "s"],
    ["Which personal trading practice creates a conflict with clients?",
      ["Trading a security ahead of client orders", "Holding broad index ETFs for the long term", "Pre-clearing trades with compliance", "Keeping personal accounts at the firm"],
      "Trading ahead of clients puts the employee's interest first. Firms require pre-clearance and monitoring of employee accounts.", "r"],
    ["A long-time client who isn't related to her advisor offers to lend him $20,000. What applies?",
      ["It's generally prohibited", "It's allowed with a signed promissory note", "It's allowed at a market interest rate", "It's allowed for amounts under $25,000"],
      "Approved Persons generally can't borrow from or lend to clients, unless the client is a related person or a lending institution and the dealer approves.", "s"],
    ["A client with no family asks her advisor to act as her power of attorney. What applies?",
      ["He generally can't, as she isn't a related person", "He may accept if she signs a waiver first", "He must accept, to protect her interests", "He may accept if her trusted contact person agrees"],
      "Approved Persons can't have control or authority over a client's financial affairs (POA, trustee, executor) unless the client is a related person and the dealer approves.", "s"],
    ["An advisor learns he's been named executor in the will of a client who isn't related to him. What should he do?",
      ["Disclose it to the firm; he generally can't act", "Accept, since executor roles aren't regulated", "Accept, and keep it private from the firm", "Accept, and charge the estate a fee"],
      "Acting as executor or trustee for an unrelated client is a prohibited personal financial dealing. He should tell the firm and decline.", "s"],
    ["A client asks her advisor to personally guarantee that her losses won't exceed 5%. What is the issue?",
      ["Guaranteeing clients against loss is prohibited", "It's acceptable if the guarantee is in writing", "It's acceptable for institutional clients only", "Only the branch manager can give guarantees"],
      "Approved Persons must not guarantee clients against loss. It's an improper personal financial dealing.", "r"],
    ["An advisor offers to share in a client's profits and losses if she lets him manage her account more closely. What applies?",
      ["It's an improper personal financial dealing", "It's acceptable if the terms are in writing", "It's acceptable if the dealer gets a share", "It's acceptable for accounts over $1 million"],
      "Sharing in a client's account creates a conflict and is a prohibited personal financial dealing.", "s"],
    ["A grateful client hands her advisor $500 in cash as a thank-you after a good year. What should the advisor do?",
      ["Decline; pay for client work must go through the firm", "Accept, since the amount is under $1,000", "Accept, and report it as income on his own personal tax return", "Accept, and share it with his assistant"],
      "Approved Persons may not accept consideration from anyone other than their dealer for activities on behalf of a client.", "s"],
    ["A client's modest balanced account turns over six times in a year, generating large commissions. What is the likely issue?",
      ["Churning", "Best execution", "Front running", "Window dressing"],
      "Churning is excessive trading to generate commissions rather than to serve the client.", "s"],
    ["Which statement best describes the relationship between ethics and rules?",
      ["Ethics guide conduct where rules are silent or unclear", "Ethics replace the rules once a firm adopts a code", "Rules are optional when they conflict with ethics", "Ethics are enforced only by the courts, never by CIRO"],
      "Rules are specific; ethical principles are broader and help people act properly in situations the rules don't cover.", "r"],
    ["What do CIRO's standards of conduct require of Regulated Persons?",
      ["High standards of ethics and conduct, dealing fairly and honestly", "Maximizing the dealer's revenue on every client account", "Avoiding every possible conflict of interest, whatever the circumstances", "Following every client instruction without question"],
      "CIRO requires high standards of ethics and conduct, just and equitable principles of trade, and no conduct unbecoming or detrimental to the public interest.", "r"],
    ["An Approved Person is found to have committed fraud in a personal side business unrelated to the dealer. Can CIRO discipline them?",
      ["Yes, as conduct unbecoming or against the public interest", "No, because CIRO only regulates trading and advice in securities", "No, because only the police can deal with fraud", "Only if one of the person's clients complains"],
      "CIRO's standards cover conduct that reflects on a person's integrity and fitness, even outside their work at the dealer.", "s"],
    ["A branch manager pressures an RR to move clients into a new high-fee product to meet targets. The RR thinks it's wrong for most of them. What is the ethical response?",
      ["Recommend it only where suitable and raise concerns with compliance", "Move all of the clients into the product to meet the branch targets", "Recommend it to every client, with full disclosure of the fees", "Resign immediately rather than discuss the issue with anyone"],
      "The RR's duty is to each client. Recommending only where it is in the client's interest, and escalating the pressure, is the ethical path.", "s"],
    ["An advisor has a small allocation of a popular new issue. How should he allocate it among his clients?",
      ["Fairly, under firm policy and each client's suitability", "To the clients who pay him the most commissions first", "To his own family members' accounts first", "To whichever clients happen to call him first"],
      "Limited opportunities must be allocated fairly and only to clients for whom they are suitable.", "s"],
    ["At a dinner, a client who is a company's CFO mentions it will announce a takeover next week. What should the advisor do?",
      ["Not trade or recommend it, and notify compliance", "Buy the company's shares for his other clients", "Tell his manager so the firm can trade on it", "Nothing, since the comment was made socially"],
      "This is material non-public information. Acting on it or passing it on would be insider trading or tipping. Compliance should be told so it can manage the information.", "s"],
    ["What is the purpose of an information barrier at a dealer?",
      ["Stopping inside information moving between departments", "Stopping hackers from reaching the firm's systems", "Keeping client assets separate from the firm's own assets", "Stopping clients from seeing the firm's research"],
      "Information barriers separate areas that hold material non-public information (such as investment banking) from sales, trading and research.", "r"],
    ["How does a grey (watch) list differ from a restricted list?",
      ["The grey list is confidential; the restricted list is shared and limits activity", "The restricted list is confidential; the grey list is shared and limits activity", "Both lists are published to clients on the firm's website", "The grey list tracks clients, while the restricted list tracks employees"],
      "Compliance quietly monitors trading in grey list securities. Restricted list securities are subject to known limits on trading, research or solicitation.", "r"],
    ["A dealer is lead underwriter on a company's public offering. What is the firm likely to do?",
      ["Put the company on its restricted list", "Publish a buy rating on the company", "Ask advisors to promote the stock widely", "Remove the company from all its lists"],
      "During an offering, the firm restricts research, trading and solicitation in the issuer's securities to manage conflicts and comply with distribution rules.", "s"],
    ["An analyst is brought 'over the wall' to help with a confidential deal. What follows?",
      ["He can't publish or trade on the company until it's public", "He may trade the company's shares for his own account afterward", "He can share what he learns with the sales team", "He must publish a report announcing the deal at once"],
      "Wall-crossed employees are restricted until the information is made public or no longer material, and the crossing is logged by compliance.", "s"],
    ["What must a dealer's client confidentiality policies ensure?",
      ["Information is used properly and shared only on a need-to-know basis", "Information is available to every employee at the firm at all times", "Information may be sold to partners if clients don't object", "Information is kept only on paper so it can't be hacked"],
      "Dealers must have policies to protect client information, restrict access and use, and get consent before disclosing it.", "r"],
    ["A client's ex-spouse calls and asks for the client's account balance for a court case. What should the advisor do?",
      ["Refuse without consent or a court order", "Provide it, since they used to be married", "Provide it if the caller knows the number", "Give a rough estimate of the balance"],
      "Client information is confidential. It may be disclosed only with the client's consent or where the law requires it, such as a court order.", "s"],
    ["What is the most effective first line of defence against phishing at a dealer?",
      ["Training staff to spot and report suspicious emails", "Turning off email for every employee at the firm", "Sharing passwords among the team for convenience", "Keeping client files on employees' personal devices"],
      "People are the main target of phishing, so awareness training and easy reporting are key, along with technical controls.", "r"],
    ["A dealer suffers a cybersecurity incident. Within what time must it make an initial report to CIRO?",
      ["Three calendar days", "Thirty days", "One year", "Only if clients complain"],
      "CIRO requires an initial report within three calendar days of discovering a cybersecurity incident, followed by an investigation report within 30 days.", "r"],
    ["Why do dealers use multi-factor authentication for clients' online access?",
      ["To reduce the risk of unauthorized access", "To speed up the client's login process", "To meet the anti-spam consent rules", "To avoid sending trade confirmations"],
      "Requiring more than a password makes it much harder for someone with stolen credentials to get into an account.", "r"],
    ["An advisor loses an unencrypted laptop containing client files. What should happen first?",
      ["Report it to the firm immediately", "Wait a few days to see if it turns up", "Tell the clients to change their passwords", "Buy a replacement laptop and move on"],
      "The firm needs to assess the breach quickly, contain it, and decide whether clients and regulators must be notified.", "s"],
    ["Which is an example of an ethical responsibility that goes beyond legal requirements?",
      ["Taking extra time to explain risks to a hesitant client", "Filing suspicious transaction reports with FINTRAC", "Sending trade confirmations by the next business day", "Keeping client records for at least seven years"],
      "Legal duties are specific requirements. Ethical conduct includes going further to make sure clients understand and are treated fairly.", "r"],
    ["Why do ethics matter in the investment industry beyond compliance with rules?",
      ["Client trust and market confidence depend on fair dealing", "Ethical codes are enforceable in court, unlike CIRO's rules", "Following ethics allows advisors to ignore some of the rules", "Ethics are what determine the commissions an advisor can charge"],
      "Markets work only if investors trust that firms and representatives act with integrity. Ethics also guide behaviour where rules fall short.", "r"],
    ["A research analyst is asked to rate a company that pays the firm large banking fees, and no control can make the rating truly independent. What should the firm do?",
      ["Avoid the conflict, for example by not issuing the rating", "Issue the rating, with a note disclosing the banking fees", "Issue a positive rating to protect the banking relationship", "Let the analyst decide alone how to handle it"],
      "When a conflict can't be addressed in the clients' best interest through controls and disclosure, it must be avoided.", "s"],
    ["A firm requires employees to pre-clear their personal trades. Which conflict is this mainly aimed at?",
      ["Trading ahead of clients or on inside information", "Employees paying too much in commissions", "Employees holding too few securities", "Clients trading too often in their own accounts"],
      "Pre-clearance lets compliance check employee trades against client orders, restricted and grey lists.", "r"],
    ["An advisor tells a client that a stock 'will definitely double this year.' What is the issue?",
      ["Presenting an opinion as a guaranteed fact", "Failing to provide best execution on the trade", "Breaching the client priority rule", "Charging an excessive commission"],
      "Representations about future value or returns must not mislead. Opinions must be presented as opinions, never as guarantees.", "s"],
    ["What does putting the client's interest first mean in practice?",
      ["Recommendations are based on the client's interest, not the firm's", "The client's instructions are always followed without discussion", "The client always pays the lowest available fee for every product", "The firm guarantees the client a positive return each year"],
      "The client-first standard means the representative's and firm's interests can't drive recommendations.", "r"],
    ["An advisor sells clients shares of a private company outside the firm's books. What is this, and is it allowed?",
      ["Selling away, and it's prohibited", "Arbitrage, and it's allowed", "Underwriting, and it's allowed", "Cross trading, and it's allowed"],
      "Selling away means dealing in securities outside the dealer's supervision. It's prohibited because clients lose the firm's oversight and protections.", "s"],
    ["An advisor buys a stock in a client's advisory account without talking to her first, believing she'll like it. What has happened?",
      ["Unauthorized trading", "Best execution failure", "Churning", "Front running"],
      "Advisory accounts require the client's approval for each trade. Using discretion without written authority is unauthorized trading.", "s"],
    ["Which compensation practice most clearly creates a conflict for advisors?",
      ["A sales contest rewarding sales of one product", "A salary plus a bonus based on client satisfaction", "A flat fee based on client assets across products", "A salary with no link to which products are sold"],
      "Incentives tied to specific products can bias recommendations. Firms must assess and control them, or stop them.", "r"],
    ["An elderly client tells her advisor she plans to leave him a large gift in her will. What should he do?",
      ["Disclose it to the firm, which will likely make him decline", "Accept quietly, since it's her decision to make", "Encourage the gift by giving her extra attention and service over time", "Ask her to keep the plan secret from her family"],
      "A gift from a client, especially a vulnerable one, is a serious conflict. It must be disclosed, and firms typically require it to be refused.", "s"],
    ["What is the main purpose of a firm's code of ethics?",
      ["Setting expectations for integrity beyond specific rules", "Replacing CIRO's rules with the firm's own internal standards", "Allowing employees to settle complaints directly", "Setting the commission rates for advisors"],
      "A code of ethics sets out values and expected behaviour, guiding decisions where rules are general or silent.", "r"],
    ["A Portfolio Manager realizes a stock bought for a discretionary account doesn't fit the client's KYC, and sells it at a small loss. What else should happen?",
      ["Follow the firm's error policy, including telling the client", "Nothing, since the position has already been sold", "Recover the loss with a riskier trade in the same client account", "Remove the trade from the account's records"],
      "Errors must be handled transparently under firm policy: documented, corrected so the client isn't harmed, and disclosed.", "s"]
  ]);
})();
