// Exam-style questions modelled on CIRO's CIRE practice exam: short stems, four parallel options,
// one clearly best answer. Original wording; each list is tagged with its syllabus outcome in comments.
// Format: [question, [correct, wrong, wrong, wrong], explanation, kind]  (kind: r concept, s scenario, c calculation)
window.QB_HARD = window.QB_HARD || {};
(function () {
  const add = (k, list) => { window.QB_HARD[k] = (window.QB_HARD[k] || []).concat(list); };

  // ---------- Element 1: regulatory framework (1.1 – 1.9, 1.11) ----------
  add("reg", [
    ["Which body coordinates securities regulation across Canada's provinces and territories, mainly through National Instruments?",
      ["The Canadian Securities Administrators (CSA)", "The Canadian Investment Regulatory Organization (CIRO)", "The Office of the Superintendent of Financial Institutions (OSFI)", "The federal Department of Finance under the Bank Act"],
      "Canada has no national securities regulator. The CSA is the umbrella group of the 13 provincial and territorial regulators, and it harmonizes their rules through National Instruments and policies.", "r"],
    ["A provincial securities commission finds that a company is selling shares to the public with no prospectus and no exemption. Which action is within the commission's powers?",
      ["Issue a cease trade order against the company", "Order CIPF to compensate the company's investors", "Expel the company from membership in CIRO", "Lay Criminal Code charges against its officers"],
      "Provincial regulators can halt trading, deny exemptions, impose administrative penalties and bring proceedings under their securities act. Criminal charges are laid by police and prosecuted by the Crown. CIPF only pays when a member firm becomes insolvent.", "s"],
    ["What does it mean when a securities regulator issues a final receipt for a prospectus?",
      ["The prospectus meets disclosure rules and the securities may be sold", "The regulator has reviewed the business plan and endorses its merits", "The regulator guarantees investors against any misrepresentation", "The issuer is now exempt from continuous disclosure obligations"],
      "A receipt means the document meets the disclosure requirements. Regulators don't judge the merits of an investment or guarantee the information. Investors have statutory rights if the prospectus contains a misrepresentation.", "r"],
    ["Which of the following best describes a Companion Policy (CP)?",
      ["It explains how regulators interpret and apply a related instrument", "It is a rule adopted by some, but not all, provincial regulators", "It is a statute passed by a provincial or territorial legislature", "It sets out the terms of a dealer's agreement with its clients"],
      "A Companion Policy accompanies an instrument and sets out how regulators interpret it. A rule adopted by only some jurisdictions is a Multilateral Instrument. Statutes are passed by legislatures.", "r"],
    ["How does a Multilateral Instrument differ from a National Instrument?",
      ["It's adopted by some CSA jurisdictions rather than all of them", "It applies only to trading on foreign organized regulated markets", "It is guidance only, so it doesn't have the force of law", "It is issued by CIRO rather than by the provincial regulators"],
      "Both are rules with legal force. A National Instrument is adopted in every jurisdiction; a Multilateral Instrument is adopted in some (for example, where Ontario doesn't take part).", "r"],
    ["What is the main purpose of a CSA Staff Notice?",
      ["To share staff views or guidance on how requirements apply", "To create new legal obligations binding on every registrant", "To announce penalties imposed on individual registrants", "To give the CSA authority over federally chartered banks"],
      "Staff Notices communicate staff views and guidance; they aren't rules. Binding obligations come from statutes, regulations and National or Multilateral Instruments.", "r"],
    ["Which of the following falls under CIRO's regulatory authority?",
      ["Investment dealers, mutual fund dealers and marketplace trading", "Banks, insurance companies and federally regulated pension plans in Canada", "Listed public companies and the conduct of their boards of directors", "Portfolio managers and exempt market dealers in every province"],
      "CIRO was formed in 2023 by merging IIROC and the MFDA. It oversees investment dealers and mutual fund dealers and supervises trading on Canada's debt and equity marketplaces. Portfolio managers and exempt market dealers are overseen directly by the provincial regulators.", "r"],
    ["CIRO is a self-regulatory organization. Who oversees CIRO itself?",
      ["The provincial and territorial regulators that recognize it", "The Bank of Canada, under its financial stability mandate", "The Office of the Superintendent of Financial Institutions", "Its member firms, which can veto any proposed CIRO rule"],
      "CIRO operates under recognition orders from the CSA members. They oversee CIRO and approve its rules.", "r"],
    ["After a disciplinary hearing, which sanction can CIRO impose on an Approved Person?",
      ["A fine, a suspension or a permanent bar", "A prison term for a serious rule breach", "An order that CIPF compensate the clients", "A criminal conviction for insider trading"],
      "CIRO can reprimand, fine (up to $5 million per contravention or three times the benefit gained), suspend, bar and order disgorgement. It can't imprison anyone or lay criminal charges.", "r"],
    ["How do CIRO's guidance notes differ from CIRO's rules?",
      ["Guidance explains CIRO's expectations; the rules set the requirements", "Guidance overrides the rules whenever the two of them conflict", "Guidance applies to mutual fund dealers but not investment dealers", "Guidance must be accepted by each client before it takes effect"],
      "Rules are binding on members and Approved Persons. Guidance notes explain how CIRO interprets the rules and what it expects to see, which helps firms comply.", "r"],
    ["Which set of rules governs how Participants trade on Canadian equity marketplaces?",
      ["The Universal Market Integrity Rules (UMIR)", "The Investment Dealer and Partially Consolidated Rules", "National Instrument 45-106 Prospectus Exemptions", "The Mutual Fund Dealer Rules"],
      "UMIR sets the trading conduct rules: best execution, client priority, manipulation, front running, short sale marking and more. The IDPC Rules cover dealers' business conduct, financial and operational matters.", "r"],
    ["An individual wants to start trading securities with clients at an investment dealer. Which statement about registration is true?",
      ["They must register, with CIRO acting for provincial regulators", "No registration is needed once the dealer itself is registered", "Only the CSA approves individuals, so CIRO plays no role in it", "Registration is optional once the individual has passed the CIRE"],
      "Firms and their dealing representatives must be registered under provincial securities law. For investment dealers, CIRO approves individuals and handles their registration on behalf of the provincial regulators. Passing an exam meets proficiency; it isn't registration.", "s"],
    ["Besides registering with the provincial regulators, what must an investment dealer do to operate in Canada?",
      ["Become a member of CIRO", "Obtain a charter under the Bank Act", "List its own shares on a recognized exchange", "Register with OSFI as a deposit-taking institution"],
      "Investment dealers must be registered in each jurisdiction where they do business and must be members of CIRO, which regulates their conduct and capital.", "r"],
    ["How does an alternative trading system (ATS) differ from a recognized exchange?",
      ["An ATS can't list issuers or regulate the conduct of its subscribers", "An ATS isn't subject to any form of regulatory oversight at all", "An ATS may trade crypto assets but not traditional securities", "An ATS can list new issuers but cannot match buy and sell orders"],
      "Both are marketplaces. An exchange lists issuers and can regulate its members; an ATS only provides trading, must register as a dealer and must be a CIRO member.", "r"],
    ["Why are secondary marketplaces important to companies raising capital in the primary market?",
      ["They give investors liquidity, so new issues are easier to sell", "They set the price of a new issue before underwriting begins", "They guarantee that every new issue will be fully subscribed", "They lend capital directly to the issuers that list on them"],
      "Investors are more willing to buy new securities when they know they can resell them later. Exchanges and ATSs provide that liquidity and transparent pricing.", "r"],
    ["A crypto-asset trading platform (CTP) wants to serve Canadian investors. Which statement best describes its regulatory position?",
      ["It must register and meet investor protection terms", "It's exempt because crypto assets aren't legal tender in Canada", "It only needs approval from the Bank of Canada to begin operating", "It may operate freely as long as its servers are located outside Canada"],
      "Regulators treat many crypto platform arrangements as securities or derivatives. CTPs must register and meet terms on custody, disclosure, product limits and investor purchase limits.", "s"],
    ["A CTP limits how much of most crypto assets a client who isn't an eligible investor can buy in 12 months. What is the main purpose of this limit?",
      ["To cap the client's exposure to a volatile, high-risk asset", "To keep the platform below the threshold for CIRO membership", "To meet the anti-spam rules for electronic offers", "To let the Bank of Canada control crypto prices"],
      "CSA terms limit non-eligible investors' net purchases of most crypto assets (other than a few specified ones such as Bitcoin and Ether) and require an appropriateness assessment. The goal is investor protection.", "s"],
    ["What is a foreign organized regulated market (FORM)?",
      ["A foreign exchange regulated by a recognized foreign regulator", "A Canadian ATS that trades only foreign-currency securities", "An offshore platform that trades crypto assets with no regulation", "A marketplace run by CIRO for cross-listed Canadian securities"],
      "UMIR defines a FORM as a market outside Canada that is an exchange or quotation system regulated by a foreign securities regulator. UMIR allows certain trades to be done on a FORM.", "r"],
    ["What is the main function of CDS Clearing and Depository Services (CDS)?",
      ["Holding securities centrally and settling trades by book entry", "Guaranteeing the performance of exchange-traded options and futures", "Insuring client accounts against losses when a dealer becomes insolvent", "Supervising trading activity on Canada's equity marketplaces"],
      "CDS holds securities centrally and clears and settles trades electronically, so certificates don't have to change hands. CDCC clears exchange-traded derivatives, CIPF protects clients of insolvent members and CIRO supervises trading.", "r"],
    ["A client buys an exchange-traded call option on the Montréal Exchange. Which organization guarantees performance of the contract?",
      ["The Canadian Derivatives Clearing Corporation (CDCC)", "CDS Clearing and Depository Services (CDS)", "The Canadian Investor Protection Fund (CIPF)", "The option writer's dealer, from its own capital"],
      "CDCC is the clearing house for exchange-traded derivatives in Canada. It becomes the counterparty to both sides, so the buyer doesn't bear the writer's credit risk.", "s"],
    ["A client's investment dealer becomes insolvent. Which loss is CIPF most likely to cover?",
      ["Securities missing from her account when the firm failed", "A fall in the market value of her shares during the past year", "Losses on trades her advisor wrongly recommended", "Losses on a bond after its issuer defaulted"],
      "CIPF covers missing customer property (cash and securities) when a member firm becomes insolvent, up to its limits. It doesn't protect against market losses, unsuitable advice or issuer defaults.", "s"],
    ["A client has a cash account and a margin account at one member firm, plus an RRSP at the same firm. If the firm fails, how does CIPF coverage apply?",
      ["$1 million for the cash and margin accounts together, plus $1 million for the RRSP", "$1 million for each of the three accounts separately, for $3 million of coverage in total", "$1 million for all three accounts together, as a single combined limit", "$100,000 for each account, the same as CDIC deposit insurance"],
      "CIPF coverage is up to $1 million per account category. Non-registered accounts such as cash and margin accounts are grouped as general accounts; registered retirement accounts (RRSPs, RRIFs and similar) form a separate category.", "s"],
    ["How is customer property distributed when an investment dealer goes bankrupt under Part XII of the Bankruptcy and Insolvency Act?",
      ["It's pooled and shared by net equity, with CIPF covering eligible shortfalls", "Each client gets back their own securities in order of the account's age", "The firm's unsecured creditors are paid first, then any remaining clients", "The CSA sells the firm's assets and pays every client a fixed amount"],
      "Part XII creates a customer pool fund that is shared among customers in proportion to their net equity, ahead of general creditors. CIPF covers eligible shortfalls up to its limits.", "r"],
    ["Under Part XII of the Bankruptcy and Insolvency Act, what generally happens to securities registered in a client's own name when the dealer fails?",
      ["They're returned to the client rather than pooled", "They're pooled with other customer property", "They're sold to repay the firm's general creditors", "They're held by CIPF until all claims are settled"],
      "Customer name securities belong to the client and are delivered back to them (if the client isn't indebted to the firm). Securities held in the firm's name go into the customer pool fund.", "r"],
    ["How is the Canadian Investor Protection Fund funded?",
      ["By assessments on its member firms", "By annual federal government grants", "By premiums charged on each client account", "By fines that CIRO collects from dealers"],
      "Member firms pay regular assessments to CIPF. Clients pay nothing directly for the coverage.", "r"],
    ["Which of the following is generally NOT an eligible claimant for CIPF coverage?",
      ["A client who caused or helped cause the firm's failure", "A retail client who holds an RRSP account at the firm", "A corporation that holds a margin account at the firm", "A client who lives in a different province from the firm's head office"],
      "CIPF protects customers of a failed member firm. Anyone who caused or materially contributed to the insolvency is excluded.", "r"],
    ["CIRO rules require an investment dealer to meet minimum capital requirements. Why?",
      ["So it can meet its obligations and absorb losses without harming clients", "So it has enough money to invest in high-return securities for profit", "So it can use client cash as working capital when markets are busy", "So it can pay its CIPF assessments without needing client approval"],
      "Capital requirements (including an early warning system) keep dealers solvent and able to meet their obligations, which protects clients and the wider market.", "r"],
    ["The deposit practices of an Ontario credit union are under review. Which regulator is responsible?",
      ["The Financial Services Regulatory Authority of Ontario (FSRA)", "The Ontario Securities Commission (OSC)", "The Office of the Superintendent of Financial Institutions", "The Canadian Investment Regulatory Organization (CIRO)"],
      "FSRA regulates non-securities financial services in Ontario: credit unions, insurance, pensions, mortgage brokering, loan and trust companies, and financial planner titles. OSFI oversees federally regulated institutions such as banks.", "s"],
    ["Which of the following is a function of the Bank of Canada?",
      ["Conducting monetary policy and promoting a stable financial system", "Supervising the solvency of banks and federally regulated insurers", "Approving the registration of new investment dealers", "Setting the federal government's budget and tax rates"],
      "The Bank of Canada conducts monetary policy, issues bank notes, promotes financial stability and manages funds for the government. OSFI supervises banks' solvency; fiscal policy belongs to the government.", "r"],
    ["Investigators are looking into a large stock-promotion fraud with a view to criminal charges. Which organization specializes in criminal investigations of serious capital markets fraud?",
      ["The RCMP Integrated Market Enforcement Teams (IMET)", "The Ombudsman for Banking Services and Investments", "The Canadian Investor Protection Fund", "The Financial Consumer Agency of Canada"],
      "IMET units combine RCMP investigators with lawyers and forensic accountants to investigate serious capital markets fraud for criminal prosecution.", "s"],
    ["What is the main role of the Office of the Superintendent of Financial Institutions (OSFI)?",
      ["Supervising federally regulated institutions like banks", "Investigating client complaints about investment dealers", "Regulating trading activity on Canadian stock exchanges", "Collecting suspicious transaction reports from dealers"],
      "OSFI is the federal prudential regulator of banks, federally regulated trust, loan and insurance companies, and federally regulated pension plans.", "r"],
    ["What is the role of FINTRAC?",
      ["Analyzing transaction reports and supervising AML compliance", "Prosecuting money launderers in criminal court for the Crown", "Freezing client accounts on behalf of the provincial regulators", "Approving each dealer's AML program in advance"],
      "FINTRAC is Canada's financial intelligence unit. It receives reports, discloses intelligence to police and supervises compliance, including administrative monetary penalties. Prosecution is done by the Crown.", "r"],
    ["A client believes her dealer disclosed her personal information without consent. Which body oversees compliance with PIPEDA?",
      ["The Office of the Privacy Commissioner of Canada", "The Financial Transactions and Reports Analysis Centre", "The Ombudsman for Banking Services and Investments", "The Competition Bureau of Canada"],
      "The federal Privacy Commissioner oversees PIPEDA. Alberta, British Columbia and Quebec have their own similar private-sector privacy laws and commissioners.", "s"],
    ["A Canadian investment dealer wants to deal with clients who live in the United States. Which statement is true?",
      ["It must register in the US or rely on an exemption", "Its Canadian registration lets it deal with residents of any country", "US residents may only open order-execution-only accounts in Canada", "The CSA must approve each US client account before it is opened"],
      "Dealing with residents of another country brings that country's laws into play. In the US that means the SEC, FINRA and state regulators (and the CFTC and NFA for futures).", "s"],
    ["Which US regulator oversees the futures and swaps markets?",
      ["The Commodity Futures Trading Commission (CFTC)", "The Securities and Exchange Commission (SEC)", "The Financial Industry Regulatory Authority (FINRA)", "The Federal Deposit Insurance Corporation (FDIC)"],
      "The CFTC regulates US futures and swaps (with the NFA as the industry's self-regulatory body). The SEC regulates securities markets, and FINRA is the SRO for broker-dealers.", "r"],
    ["Which statement best describes the Bank Act's relevance to the securities industry?",
      ["It governs banks, which may own investment dealers through subsidiaries", "It sets the trading rules that bank-owned dealers follow on exchanges", "It requires every investment dealer to hold a federal bank charter", "It lets banks regulate the conduct of their own dealer subsidiaries"],
      "The federal Bank Act governs how banks are incorporated, owned and operated, supporting their stability. Since 1987 banks have been allowed to own investment dealers, which remain regulated by provincial securities law and CIRO.", "r"],
    ["Which of the following is an offence under the Criminal Code of Canada?",
      ["Insider trading and tipping", "Missing a 36-month KYC update", "Sending a promotional email without consent", "Charging a fee that isn't on the fee schedule"],
      "The Criminal Code makes insider trading, tipping, market manipulation, fraud affecting the public market and money laundering crimes. KYC lapses are regulatory breaches, and email marketing falls under CASL.", "r"],
    ["Why are some serious market abuses prosecuted under the Criminal Code rather than only under securities law?",
      ["The Criminal Code allows much longer prison terms for serious fraud", "Provincial securities laws don't apply to companies listed on exchanges", "Only the Criminal Code makes market manipulation an offence at all", "CIRO isn't permitted to investigate trading on Canadian marketplaces"],
      "Securities acts and the Criminal Code both prohibit manipulation and fraud, but Criminal Code offences such as fraud affecting the public market carry much heavier penalties (up to 14 years in prison).", "r"],
    ["An advisor wants to email a newsletter promoting the firm's services to people she met at a seminar. Under Canada's Anti-Spam Legislation (CASL), what is required?",
      ["Consent, sender identification and an unsubscribe option", "CIRO's approval before each message is sent out", "Nothing, as long as the content isn't false or misleading to readers", "A signed paper consent form from each recipient"],
      "CASL requires consent (express or implied), clear identification of the sender and a working unsubscribe mechanism. Unsubscribe requests must be honoured within 10 business days.", "s"],
    ["Under PIPEDA, when must a firm report a breach of security safeguards involving personal information?",
      ["When it creates a real risk of significant harm", "Only when over 1,000 clients are affected", "Only when an affected client asks it to", "Never, if the data is recovered within 30 days"],
      "Breaches that pose a real risk of significant harm must be reported to the Privacy Commissioner, and affected individuals must be notified as soon as feasible. Records of all breaches must be kept for 24 months.", "r"],
    ["A firm wants to use client information collected at account opening to market an unrelated insurance product from a partner company. What does PIPEDA require?",
      ["The client's consent for the new purpose", "Nothing, since the information is already on file", "A notice in the firm's annual report", "FINTRAC's approval before it is used"],
      "Personal information may be used only for the purposes the client consented to. A new purpose, such as a partner's marketing, needs new consent.", "s"],
    ["An investment banker is about to receive confidential details of a client company's planned acquisition. What is the purpose of having the banker sign a confidentiality agreement?",
      ["To bind the banker to protect the information and use it only for the deal", "To allow the banker to share the details with the firm's retail clients", "To exempt the acquisition from the take-over bid rules", "To make the information public as soon as the agreement is signed"],
      "Confidentiality agreements protect corporate, client and third-party information by limiting its use and disclosure. They also support the firm's insider trading controls.", "s"]
  ]);

  // ---------- Element 1: anti-money laundering (1.10) ----------
  add("reg", [
    ["A client deposits cash in small amounts at several branches, then wires the money through accounts in several countries. Which stage of money laundering do the wires represent?",
      ["Layering", "Placement", "Integration", "Structuring"],
      "Placement gets illicit cash into the financial system (the small deposits; 'structuring' is a placement technique). Layering moves it through complex transactions to hide its source. Integration returns it to the economy looking legitimate.", "s"],
    ["A launderer buys a luxury condominium with funds that have already passed through several shell companies. Which stage of money laundering is this?",
      ["Integration", "Placement", "Layering", "Smurfing"],
      "Integration is the final stage: the laundered funds re-enter the legitimate economy, here as a real estate purchase.", "s"],
    ["Which is a required element of an investment dealer's anti-money laundering compliance program?",
      ["A documented risk assessment of its business and clients", "FINTRAC's approval of each new client before account opening", "A complete ban on accepting cash deposits from clients", "Annual reporting to FINTRAC of every trade over $1,000"],
      "A compliance program needs an appointed compliance officer, written and up-to-date policies and procedures, a risk assessment, an ongoing training program and an effectiveness review every two years.", "r"],
    ["How often must an investment dealer review the effectiveness of its AML compliance program?",
      ["At least every two years", "Every month", "At least every five years", "Only after FINTRAC finds a gap"],
      "The PCMLTF Regulations require a review of the policies, procedures, risk assessment and training at least every two years.", "r"],
    ["A dealer's review gives it reasonable grounds to suspect that a client's transaction is related to money laundering. When must it file a suspicious transaction report (STR)?",
      ["As soon as practicable", "Within 30 days, after telling the client", "Only once the transaction has completed", "At quarter-end, with its other reports"],
      "An STR must be filed as soon as practicable once the measures taken establish reasonable grounds to suspect. Attempted transactions must be reported too, and the client must not be told.", "r"],
    ["After filing a suspicious transaction report, a dealer is asked by the client why her wire was delayed. What must the dealer avoid?",
      ["Telling her that a report was made to FINTRAC", "Continuing to monitor activity in her account", "Recording the conversation in her client file", "Applying enhanced measures to her account"],
      "Tipping off a client that a report has been filed is prohibited. The firm should keep monitoring and document what happens.", "s"],
    ["A client deposits $10,500 in cash to her account in one transaction. Nothing else about it seems unusual. What must the dealer do?",
      ["File a large cash transaction report with FINTRAC", "Refuse the deposit, since dealers can't take cash", "File a suspicious transaction report right away", "Report the deposit to CIRO within 30 days"],
      "Receiving $10,000 or more in cash (in one transaction, or several within 24 hours) requires a large cash transaction report within 15 calendar days. It needs an STR only if there are reasonable grounds to suspect.", "s"],
    ["A dealer discovers that an account belongs to a listed terrorist entity. What must it do?",
      ["Freeze the property and report it immediately", "Close the account and return the assets to the client", "Keep the account open and monitor it", "Report it in its next quarterly filing"],
      "The property must not be dealt with. A terrorist property report goes to FINTRAC immediately, and the Criminal Code requires disclosure to the RCMP and CSIS.", "s"],
    ["A new client tells you he was his country's ambassador to Canada until two years ago. How should the dealer treat him?",
      ["As a foreign PEP, with enhanced measures such as source of funds", "As a domestic PEP, since he now lives and works in Canada permanently", "As an ordinary client, since he no longer holds office", "As a client who must be reported to FINTRAC at once"],
      "Once someone is a foreign politically exposed person, they remain one. Foreign PEPs are high risk: the dealer must establish the source of funds, get senior management approval and apply enhanced ongoing monitoring.", "s"],
    ["Which of the following would be treated as a politically exposed person, or a family member of one, under the PCMLTFA?",
      ["The spouse of a sitting provincial premier", "A clerk in a city's finance department", "A senior manager at a private company", "A volunteer on a local political campaign"],
      "PEP rules cover the office-holder and their family members and close associates. Domestic PEPs include premiers, members of Parliament and legislatures, deputy ministers and mayors.", "r"],
    ["Which method is acceptable for verifying an individual client's identity under FINTRAC rules?",
      ["Checking valid government-issued photo ID", "Accepting a mailed copy of an expired passport", "Relying on the client's own statement of identity", "Using one utility bill with no other source"],
      "Acceptable methods include authentic, valid and current government-issued photo ID, the credit file method and the dual-process method (two different reliable sources). An expired document or a single bill isn't enough.", "r"],
    ["A client opening an account says she'll be investing money on behalf of her brother. What must the dealer do?",
      ["Take reasonable measures to identify and record the third party", "Refuse the account, since third-party money is never allowed", "Open the account in the brother's name without telling him", "Treat her as a politically exposed person from now on"],
      "Dealers must make a third-party determination and record the third party's details and relationship to the client.", "s"],
    ["To meet its AML and regulatory record-keeping obligations, how long should an investment dealer keep its client relationship records?",
      ["At least seven years from when each record is created", "At least three years from the client's last trade", "At least two years from the date the account opened", "At least one year from when the account is closed"],
      "CIRO's record-keeping standard is seven years, and it is the answer CIRO's practice exam expects. It also satisfies the PCMLTFA's five-year minimum.", "r"],
    ["Which factor would most likely raise a new client's rating in a dealer's AML risk assessment?",
      ["Frequent wires to and from a high-risk foreign jurisdiction", "A long career at a large Canadian public company", "A modest RRSP funded by regular payroll deductions", "Residency in the same city as the dealer's main branch office"],
      "Risk assessments consider clients, products, delivery channels and geography. Dealings with high-risk jurisdictions are a classic risk indicator.", "s"],
    ["Under a dealer's AML compliance program, who must receive AML training?",
      ["Employees and agents who deal with clients or transactions", "Only the chief compliance officer and the designated AML officer", "Only staff in the firm's cash-handling department", "Only senior management, who then decide what to share"],
      "The training program must cover everyone who deals with clients or handles transactions, so they can recognize and escalate suspicious activity.", "r"],
    ["A client who normally makes small monthly RRSP contributions suddenly receives several large wires from unrelated people overseas. What should her advisor do first?",
      ["Escalate it to the firm's AML compliance officer", "Tell the client to stop the wires, and say nothing more", "File a suspicious transaction report personally", "Close the account and send the money back"],
      "Activity that doesn't fit the client's profile should be escalated internally under the firm's procedures. The AML officer investigates and decides whether to file a report.", "s"]
  ]);

  // ---------- Element 2: prospective client relationships ----------
  add("onboard", [
    ["Which client qualifies as an institutional client under CIRO rules without having to ask?",
      ["A corporation with $15 million of securities under administration", "An individual with $12 million of securities under administration", "An individual who has earned $400,000 a year for two years", "A small charity with $2 million invested at the firm"],
      "A non-individual with more than $10 million in securities and precious metals bullion under administration or management qualifies. An individual over $10 million qualifies only by requesting and consenting to it.", "s"],
    ["An individual client has $14 million in securities under administration. How can she be treated as an institutional client?",
      ["Only if she requests and consents to it", "Automatically, as she is over $10 million", "Only if she is a registered portfolio manager", "She can't; individuals are always retail"],
      "Individuals with more than $10 million in securities and bullion can be classified as institutional only if they request it and consent to the classification.", "s"],
    ["Which of the following falls within CIRO's definition of an institutional client?",
      ["A registrant under securities law, other than an individual", "Any client who has had an account for over ten years", "An individual with annual income above $200,000", "Any client who trades in an order-execution-only account"],
      "Institutional clients include accepted counterparties, accepted institutions, regulated entities, non-individual registrants, non-individuals over $10 million, and individuals or hedgers who request and consent to the classification.", "r"],
    ["A grain-farming company uses futures to hedge its crops. When can it be classified as an institutional client for those accounts?",
      ["If it requests and consents to it for its hedging accounts", "Automatically, because hedging reduces its overall risk", "Only once its net assets are more than $25 million", "Never; commercial hedgers are always retail clients"],
      "A hedger can be an institutional client for accounts with qualifying hedging activity, but only if it requests and consents to the classification.", "s"],
    ["What is the main practical difference in how retail and institutional clients are treated?",
      ["Retail clients get more protection, such as full suitability and reporting", "Institutional clients get more protection because their trades are larger", "Retail clients can't buy securities that trade on an exchange", "Institutional clients are exempt from all anti-money laundering rules"],
      "Many client protections (relationship disclosure, cost and performance reports, full suitability) are reduced or not required for institutional clients, who are presumed to be sophisticated. AML rules apply to everyone.", "r"],
    ["Under CIRO rules, which clients are retail clients?",
      ["Any client who isn't an institutional client", "Individuals with under $1 million in assets", "Any client who has an advisory account", "Individuals who aren't accredited investors"],
      "CIRO defines a retail client simply as a client that is not an institutional client.", "r"],
    ["Which individual qualifies as an accredited investor under NI 45-106?",
      ["One with financial assets over $1 million, net of related debt", "One with net income of $150,000 in the most recent year", "One with a mortgage-free home worth more than $900,000", "One with total assets of $3 million, including a mortgaged home"],
      "Individual tests include financial assets over $1 million (net of related liabilities), net income over $200,000 ($300,000 with a spouse) in each of the last two years, or net assets of at least $5 million.", "r"],
    ["Raj earned $230,000 before tax in each of the last two years and expects the same this year. His financial assets are $400,000. Is he an accredited investor?",
      ["Yes, under the income test", "No, his financial assets are too low", "No, he must earn $300,000 on his own", "Only if his spouse also signs"],
      "An individual qualifies with net income over $200,000 in each of the two most recent years and a reasonable expectation of exceeding it this year. Only one test needs to be met.", "s"],
    ["Why does NI 45-106 allow accredited investors to buy securities without a prospectus?",
      ["They're presumed able to assess the risks and absorb losses", "The securities they buy are guaranteed by the issuer", "They must resell the securities within 30 days of buying them", "Their purchases are reviewed in advance by the CSA"],
      "Prospectus exemptions rest on the idea that some investors can get information and bear risk without a prospectus's protection.", "r"],
    ["An individual who qualifies as an accredited investor under the $1 million financial asset test buys a private placement. What must the dealer usually obtain?",
      ["A signed risk acknowledgement form", "A receipt from the provincial regulator", "An audited statement of her net worth", "Written approval from CIRO"],
      "Individuals relying on the income or $1 million financial asset tests must sign Form 45-106F9. Individuals with financial assets over $5 million don't need it.", "r"],
    ["A pension fund that is a permitted client tells its dealer it doesn't need suitability assessments. What lets the dealer stop assessing suitability?",
      ["A written waiver from the pension fund", "A note of the conversation in the client file", "Nothing; suitability can never be waived", "Approval from the pension fund's auditor"],
      "A permitted client that isn't an individual can waive suitability in writing. CIRO allows a similar written waiver for non-individual institutional clients.", "s"],
    ["Which client may NOT waive the suitability requirement?",
      ["An individual retail client in a managed account", "A non-individual permitted client", "A pension fund that is an institutional client", "A corporation with $30 million of net assets"],
      "Individual retail clients can't waive suitability, and suitability can't be waived for managed accounts.", "r"],
    ["A client's risk profile combines which two elements?",
      ["Willingness to take risk and ability to absorb losses", "Investment knowledge and the client's investment time horizon", "Annual income and total net worth", "Return objectives and liquidity needs"],
      "Risk profile = risk tolerance (willingness) plus risk capacity (ability). Both must be assessed and documented.", "r"],
    ["Mei, 34, has a stable income, no debt and a 30-year time horizon, but she says she would sell everything if her portfolio fell 10%. How would you describe her risk profile?",
      ["High risk capacity, low risk tolerance", "Low risk capacity, high risk tolerance", "High risk capacity, high risk tolerance", "Low risk capacity, low risk tolerance"],
      "Capacity is her financial ability to absorb losses (high). Tolerance is her willingness (low). When the two differ, the lower one should generally drive the risk profile.", "s"],
    ["Which item falls under a client's personal circumstances in KYC?",
      ["Marital status and dependants", "Annual income and net worth", "Experience trading options", "A goal of long-term growth"],
      "Personal circumstances include age, family situation, dependants and employment. Income and net worth are financial circumstances; growth is an investment objective.", "r"],
    ["How is a client's investment time horizon best described?",
      ["The time until a significant part of the money is needed", "The number of years the client has been investing", "The term to maturity of the longest bond they hold", "The minimum holding period set out in the account agreement"],
      "Time horizon is the period from now until the client needs a significant part of the money. It affects how much risk the account can take.", "r"],
    ["Why must an advisor assess a client's investment knowledge?",
      ["To judge which products and explanations suit the client", "To decide which commission rate to charge the client", "To decide whether the client qualifies as an institutional client", "To meet FINTRAC's identity verification requirements"],
      "Investment knowledge affects how the advisor communicates and whether a client can understand the risks of a product.", "r"],
    ["A new retail client wants to open an advisory account today and buy shares. What must happen before the advisor makes a recommendation?",
      ["Collect KYC information and provide relationship disclosure", "Send the client a first monthly account statement", "Get copies of the client's last three tax returns", "Register the client with CIPF so the account is protected against loss"],
      "KYC must be collected and the relationship disclosure provided before the dealer gives advice or trades for a new retail client. CIPF coverage is automatic.", "s"],
    ["A client's adult son presents a power of attorney (POA) and asks to trade in his mother's account. What should the dealer do?",
      ["Review the POA, keep a copy and confirm it covers the account", "Accept his instructions, since he is a close family member", "Refuse, since a POA can never be used for investments", "Ask the mother to close her account and open a joint one"],
      "A POA lets the attorney act for the client, but the dealer must check the document, keep a copy, confirm its scope and verify the attorney's identity.", "s"],
    ["Why might a client grant a continuing (enduring) power of attorney for property?",
      ["So someone can manage her finances if she loses capacity", "To transfer ownership of her assets to the attorney now", "To avoid paying tax on her investment income", "To allow the dealer to trade her account at its discretion"],
      "A continuing POA stays in force if the person later loses mental capacity, so a trusted person can manage their affairs. It doesn't transfer ownership.", "r"],
    ["When must a dealer take reasonable steps to obtain the name and contact information of a retail client's trusted contact person (TCP)?",
      ["When opening the account and when updating KYC", "Only once the client reaches age 65", "Only after exploitation is suspected", "Only if the client has a power of attorney"],
      "Dealers must ask for TCP details at account opening and keep them current. The client may decline. A TCP can't give trading instructions.", "r"],
    ["A dealer suspects a client is being financially exploited by a new acquaintance. How can it use the client's trusted contact person (TCP)?",
      ["Contact the TCP about its concerns, as the client consented to", "Accept trading instructions from the TCP while the concern is reviewed", "Transfer the account's assets to the TCP for safekeeping", "Have the TCP sign a power of attorney for the client"],
      "With the client's written consent, the dealer may contact the TCP about suspected exploitation, diminished capacity, contact details or the client's legal representative. The TCP has no authority over the account.", "s"],
    ["A dealer puts a temporary hold on a withdrawal because it reasonably believes an elderly client is being exploited. What must it do?",
      ["Tell the client why and review the hold at least every 30 days", "Keep the hold confidential from the client until it is finally lifted", "Hold the funds for at least one year before reviewing", "Move the funds to the client's trusted contact person"],
      "The dealer must give the client notice of the hold and its reasons, document it, and review it at least every 30 days until it is lifted.", "s"],
    ["A client asks her advisor to send her account details to her accountant, who is preparing her taxes. What should the advisor do?",
      ["Get her written authorization and record the accountant's details", "Send the details, since accountants keep information confidential", "Refuse, since client information can never be shared with anyone", "Ask the accountant to open an account at the firm first"],
      "Client information is confidential. With the client's authorization, the dealer can share it with a professional such as an accountant and should document that person's role.", "s"],
    ["Why should a dealer document the role of a client's lawyer, accountant or insurance agent?",
      ["To know who the dealer may contact and what each person can do", "So they can enter trades in the client's account if needed", "So they become responsible for the account's suitability", "So the dealer no longer needs to update the client's KYC"],
      "Knowing which professionals are involved, and what authority each has, helps the dealer coordinate advice, protect confidentiality and spot unauthorized instructions.", "r"],
    ["Two index ETFs track the same index with similar tracking error. One has an MER of 0.06% and the other 0.45%. How should cost affect the advisor's recommendation?",
      ["Cost matters; the cheaper fund is likely the better choice", "Cost doesn't matter, since both track the same index", "The pricier fund is better, since higher fees mean quality", "Recommend whichever pays the advisor more compensation"],
      "Suitability must consider costs and their impact. When products are otherwise comparable, lower costs mean higher net returns for the client.", "s"],
    ["Which statement about cost in a suitability determination is correct?",
      ["Cost must be weighed, but the cheapest isn't always required", "The lowest-cost product must always be recommended to the client", "Cost may be ignored when the client has a high net worth", "Cost only matters for clients with order-execution-only accounts"],
      "The client-focused reforms make cost a key factor. Other factors (risk, features, the client's needs) can justify a higher-cost choice, but the reasons should be clear.", "r"],
    ["A client invests $50,000 in a fund that earns 6% a year before fees. About how much more would she have after 20 years if the MER were 0.5% instead of 2%?",
      ["About $36,000", "About $15,000", "About $20,000", "About $45,000"],
      "Net returns are 4% vs 5.5%. $50,000 × 1.04^20 ≈ $109,600 and $50,000 × 1.055^20 ≈ $145,900. The difference is about $36,300.", "c"],
    ["A fund has very high portfolio turnover. How is this most likely to affect an investor who holds it in a non-registered account?",
      ["Higher trading costs and more taxable gains distributed", "Lower costs, since trades are spread over more holdings", "No effect, since trading costs are already in the MER", "Higher returns, since active trading beats the index"],
      "High turnover raises trading costs (reported separately as the trading expense ratio, not in the MER) and tends to realize more gains, which are distributed and taxed.", "s"],
    ["Two clients each earn 5% interest on bonds. One holds them in a TFSA and the other in a non-registered account. Why do their after-tax returns differ?",
      ["Interest in the non-registered account is taxed each year", "TFSA interest is taxed at a lower rate than in other accounts", "Interest is only taxed once the bond reaches maturity", "The non-registered account gets the dividend tax credit"],
      "Income in a TFSA isn't taxed. Interest in a non-registered account is fully taxable at the client's marginal rate every year.", "s"],
    ["Which document is usually part of a dealer's account opening (welcome) package?",
      ["A fee schedule", "A list of other clients' holdings", "The advisor's tax return", "A CIPF guarantee against losses"],
      "The package typically includes the account agreement, fee schedule, relationship disclosure, CIRO's account opening brochure, conflict of interest disclosures and complaint handling information.", "r"],
    ["Why do dealers give new clients CIRO's account opening brochure?",
      ["To explain CIRO's role and how clients are protected", "To obtain CIRO's approval before the new account can be used", "To disclose the advisor's pay on each trade", "To confirm the client's identity for FINTRAC"],
      "The brochure explains what CIRO does, the protections available to investors, and how to raise concerns.", "r"],
    ["When must a dealer give a client information about its complaint handling process?",
      ["At account opening", "Only after a complaint", "Only on written request", "With year-end tax slips"],
      "Complaint handling information is part of the account opening package, so clients know how to complain before a problem arises.", "r"],
    ["A dealer sells its own proprietary funds. When should this material conflict be disclosed to a new client?",
      ["Before the account is opened or the first trade", "Only if the client buys a proprietary fund", "Only in the firm's annual report", "With the client's first quarterly statement"],
      "Material conflicts must be disclosed in a timely way, before the client relies on the dealer's services, in prominent and plain language.", "s"],
    ["Which set lists the main pillars of the client relationship model?",
      ["Relationship disclosure, conflicts, suitability and performance reporting", "Best execution, client priority, short marking and gatekeeping", "Placement, layering, integration and suspicious transaction reporting", "Product approval, shelf review, trailer disclosure and fund facts"],
      "The client relationship model is built on relationship disclosure, conflict of interest management, suitability assessment and account (cost and performance) reporting.", "r"],
    ["What must a retail client's annual investment performance report include?",
      ["Annualized returns over periods such as 1, 3, 5 and 10 years", "A forecast of the account's expected return for next year", "A comparison with the returns of the advisor's other clients", "The dealer's own profit earned from the client's account"],
      "The annual report shows opening and closing values, deposits and withdrawals, the change in value and annualized money-weighted returns for 1, 3, 5 and 10 years and since inception.", "r"],
    ["In which situation is a time-weighted rate of return more appropriate than a money-weighted return?",
      ["Evaluating a manager who doesn't control client cash flows", "Showing a client the effect of her own deposit timing", "Preparing a retail client's annual performance report", "Measuring the return of a client who added cash monthly"],
      "Time-weighted returns remove the effect of deposits and withdrawals, so they're used to judge managers. Money-weighted returns show the client's own experience, which is why client reports use them.", "r"],
    ["What must a dealer's annual report on charges and compensation show a retail client?",
      ["Charges the client paid and compensation such as trailers", "Only the commissions charged on securities bought during the year", "The fees the client can expect to pay over the coming year", "The firm's net income earned from the client's trades"],
      "The report shows operating and transaction charges paid and third-party compensation such as trailers. Starting with 2026, it must also show the ongoing costs of investment funds (fund expenses) in dollars.", "r"],
    ["Which statement best reflects a dealer's obligations for client records?",
      ["They must be accurate, current and available to regulators", "They can be destroyed once a client's account is closed", "Only paper records count for regulatory purposes", "They need only be kept for clients who complain"],
      "Dealers must keep complete, accurate and up-to-date records (KYC, agreements, orders, notes, confirmations) in a form they can produce promptly to regulators.", "r"]
  ]);
})();
