// Exam-level questions, set 1: regulatory framework (E1), prospective client relationships (E2),
// complaint handling (E4). Written to match the CIRE's style: longer scenarios, options of similar
// length and detail, and more than one answer that sounds reasonable.
// Format: [question, [correct, wrong, wrong, wrong], explanation, kind?]. Options are shuffled when shown.
window.QB_HARD = window.QB_HARD || {};
(function () {
  const add = (k, list) => { window.QB_HARD[k] = (window.QB_HARD[k] || []).concat(list); };

  add("reg", [
    ["Dana has been a registered representative at Dealer A for eight years. She resigns on Friday and starts at Dealer B on Monday. Several long-time clients have said they'll follow her, and Dealer B has already filed her transfer, but it hasn't been approved yet. On Monday morning, one of those clients phones Dana at Dealer B to buy 500 shares of a bank stock. What should Dana do?",
      ["Decline to take the order until her registration with Dealer B is approved",
       "Take the order, since her approval stays with her personally when she moves",
       "Take the order once the client signs Dealer B's account transfer forms",
       "Take the order and route it through Dealer A until her approval arrives"],
      "Registration and CIRO approval are tied to the sponsoring firm. Until her registration with Dealer B is effective, Dana can't trade for clients there, and placing orders through her former firm would be trading without authority.", "s"],
    ["Mira holds three positions at a CIRO investment dealer that becomes insolvent: bonds held in her account that are now missing; shares that fell 40% in the month before the failure; and $50,000 she gave her advisor for a 'private deal' that was never recorded on the dealer's books. Which of these is CIPF most likely to cover?",
      ["The missing bonds that were held in her account at the dealer",
       "The 40% market decline in her shares before the dealer failed",
       "The $50,000 she gave her advisor for the off-book private deal",
       "All three, up to a combined limit of $1 million per client"],
      "CIPF covers client property held by an insolvent member firm that is missing. It doesn't cover market declines or off-book dealings that never went through the firm.", "s"],
    ["Raj is a client of a CIRO member that fails, and all of his property is missing. He held a margin account worth $700,000, a TFSA worth $400,000 and an RRSP worth $900,000. How does CIPF apply its limits?",
      ["The margin account and TFSA share one $1 million limit; the RRSP has a separate $1 million limit",
       "Each of the three accounts has its own separate $1 million limit, for $3 million in total",
       "All three accounts share a single $1 million limit for each individual client",
       "The TFSA and RRSP share one limit as registered plans; the margin account has its own limit"],
      "CIPF groups accounts by category. TFSAs (and FHSAs) fall in the general accounts category with cash and margin accounts. RRSPs, RRIFs and similar plans are a separate registered retirement category, and RESPs are another.", "c"],
    ["A compliance officer reviews a client's account. Large deposits from unrelated third parties arrive, are used to buy and quickly sell securities, and are then wired to a foreign account. She concludes there are reasonable grounds to suspect the transactions are related to money laundering. Where must the Suspicious Transaction Report be filed?",
      ["FINTRAC", "CIRO's enforcement department", "The provincial securities commission", "The client's bank"],
      "STRs are filed with FINTRAC, Canada's financial intelligence unit. The firm may have other obligations to its regulators, but the STR itself goes to FINTRAC.", "s"],
    ["Which statement best describes the relationship between CIRO and the provincial securities commissions?",
      ["The commissions recognize and oversee CIRO, and can review its decisions",
       "CIRO is a federal regulator whose rules override the commissions' rules",
       "CIRO operates independently, with no oversight from the commissions",
       "The commissions are CIRO members and vote on all of its rules"],
      "CIRO is a self-regulatory organization recognized by the provincial and territorial regulators. They oversee it, approve its rules and can review its hearing panel decisions."],
    ["After a disciplinary hearing, a CIRO hearing panel finds that Peter, an approved person, made unsuitable recommendations. It fines him $50,000 and suspends him for six months. Peter believes the panel misread the evidence and wants the decision reviewed. What is his usual route?",
      ["Apply for a hearing and review before the provincial securities commission",
       "File a complaint with OBSI and ask it to overturn the panel's decision",
       "Ask CIPF to review whether the hearing process was conducted fairly",
       "Appeal directly to the Supreme Court of Canada within thirty days"],
      "CIRO hearing panel decisions can be reviewed by the securities commission that oversees CIRO, and may then be appealed to the courts.", "s"],
    ["A large Canadian bank owns an investment dealer subsidiary that serves retail clients across Canada. The dealer's compliance staff are debating which regulators oversee the dealer's securities business. Which answer is correct?",
      ["CIRO and the provincial securities commissions",
       "OSFI, because a federally regulated bank owns the dealer",
       "The Bank of Canada and the federal Department of Finance",
       "CDIC, because the parent bank's deposits are insured"],
      "Bank ownership doesn't change who regulates securities dealing. The dealer is a CIRO member registered with provincial regulators; OSFI supervises the bank itself.", "s"],
    ["An investment dealer based in Toronto wants to serve clients in Alberta, British Columbia and Nova Scotia. Its CEO wants to avoid dealing separately with each province's regulator for routine matters such as registration and exemptive relief. Which arrangement is designed to help?",
      ["The passport system, which lets it deal mainly with its principal regulator",
       "A single national registration issued by the federal Department of Finance",
       "A CIPF membership certificate, which every province must recognize",
       "An OBSI membership, which covers all provinces under one regulator"],
      "Under the passport system, a firm deals mainly with its principal regulator, and those decisions are generally recognized in the other passport jurisdictions.", "s"],
    ["How is CIPF's coverage fund financed?",
      ["Mainly by assessments paid by its member firms", "Mainly by annual grants from the federal government", "Mainly by a small levy charged on every client trade", "Mainly by premiums that individual investors pay"],
      "CIPF is funded by the industry. Clients don't pay premiums for coverage."],
    ["After a sharp drop in metal prices, the shares of most Canadian mining companies fall. One company's shares drop 30%, although nothing has changed in its operations, assets, management or capital. Its investor relations team asks whether it must issue a press release and file a material change report. Which answer is correct?",
      ["No; a material change must be a change in the issuer's own business, operations or capital",
       "Yes; any share price drop of more than 25% is automatically treated as a material change",
       "Yes, but only if the share price stays down for more than ten consecutive trading days",
       "No; mining companies are exempt from timely disclosure while metal prices are falling"],
      "A material change refers to the issuer's own business, operations or capital. Market-wide events that only move the price aren't material changes of the issuer.", "s"],
    ["Alexei owns 8% of a TSX-listed company's voting shares. He isn't a director or officer, has no contracts with the company, and has never received non-public information from it. He asks his advisor what rules apply to his trading. Which answer is most accurate?",
      ["He isn't an insider, but can't trade if he learns undisclosed material information from the company",
         "He's an insider because he owns over 5%, so he must report each of his trades within five calendar days",
         "He must file an early warning report, because his holdings exceed 5% of the voting shares",
         "He's in a special relationship with the company, so he may never trade its shares"],
      "Insiders include directors, senior officers and holders of more than 10% of voting rights. Separately, anyone who learns material non-public information through a special relationship can't trade on it.", "s"],
    ["An investor files an early warning report after her holdings in a company reach 10% of its voting shares. Over the following month, she keeps buying on the market until she holds 12.5%. She isn't making a take-over bid. What reporting obligation does she now have?",
      ["File a further report, since her holdings have increased by 2% or more",
       "None, because her first report covers any later purchases she makes",
       "None, unless her holdings eventually reach the 20% take-over bid level",
       "Report the change only at the company's next annual shareholders' meeting"],
      "Once over 10%, further reports are required for each change of 2% or more, and when holdings fall below 10%.", "c"],
    ["A bidder launches a take-over bid for all the shares of a target company that it doesn't already own. The target's board opposes the bid. Which condition is mandatory under Canadian take-over bid rules?",
      ["More than 50% of the shares not owned by the bidder must be tendered before any are taken up",
       "The bidder must acquire at least 90% of the outstanding shares within the first 35 days",
       "The target's board must approve the bid before it can be launched to shareholders",
       "The bid must close no later than 105 days after it is first announced to the market"],
      "The minimum tender condition requires more than 50% of the securities not held by the bidder and its joint actors. Once it's met, the bid must be extended at least 10 more days. Bids generally stay open at least 105 days.", "s"],
    ["Which organization monitors trading on Canadian equity marketplaces in real time to detect possible UMIR violations?",
      ["CIRO", "The Canadian Securities Administrators", "The Toronto Stock Exchange", "FINTRAC"],
      "CIRO is the regulation services provider for Canadian equity marketplaces, including exchanges and ATSs."],
    ["Which statement correctly contrasts OBSI with CIRO?",
      ["OBSI resolves client disputes and can recommend compensation; CIRO disciplines firms and individuals",
         "OBSI disciplines advisors and firms; CIRO resolves client disputes and awards compensation",
         "Both can fine firms and suspend advisors, but only OBSI can award compensation directly to clients",
         "OBSI's decisions are binding on firms, while CIRO's decisions are only recommendations"],
      "OBSI is a dispute-resolution service. CIRO is a regulator with enforcement powers such as fines, suspensions and bans."],
    ["Lucia is a mutual fund dealing representative at a mutual fund dealer that is a CIRO member. Several clients ask her to buy individual bank stocks and government bonds for them. She assumes this is fine now that both dealer types are regulated by CIRO. What is required before she can do this?",
      ["Investment dealer proficiency and registration through an investment dealer",
         "Nothing further, because CIRO now regulates both kinds of dealer",
         "Written consent from each client before every stock or bond trade",
         "Approval from each of the fund companies whose products she currently sells to clients"],
      "CIRO regulates both dealer types, but each has its own registration category and proficiency. Trading stocks and bonds requires being an approved person at an investment dealer.", "s"],
    ["A CIRO investigation finds that Marcus, an approved person, churned several clients' accounts over two years, generating large commissions. His firm has fired him. CIRO now brings disciplinary proceedings. Which outcome is CIRO able to impose?",
      ["A fine, a suspension or a permanent ban from the industry",
       "A prison sentence, if the losses are large enough",
       "An order requiring OBSI to compensate each client",
       "Cancellation of all the clients' past trades by the exchange"],
      "CIRO's sanctions are regulatory: fines, suspensions, terms and conditions, and bans. Criminal penalties require prosecution in the courts.", "s"],
    ["Which statement best describes CIPF's objective?",
      ["To protect clients' property if a member firm becomes insolvent",
       "To compensate investors for losses from unsuitable recommendations",
       "To insure bank deposits and GICs held at member institutions",
       "To guarantee the market value of securities held by investors"],
      "CIPF's protection is limited to member insolvency. It isn't insurance against investment losses."],
    ["Nora bought shares in a new issue under a prospectus four months ago. A securities commission has since found that the prospectus overstated the company's revenue. The shares have fallen 50%, and Nora wants her money back. Which right most directly helps her?",
      ["Her statutory right of action for rescission or damages",
       "Her two-business-day right to withdraw from the purchase",
       "A claim to CIPF for the full amount she invested",
       "A request that CIRO cancel the trade at the original price"],
      "A misrepresentation in a prospectus gives purchasers a statutory right of action for rescission or damages. The withdrawal right only applies within 2 business days of receiving the prospectus.", "s"],
    ["A small private technology company wants to raise $2 million without filing a prospectus. Its CFO describes four ways it plans to find investors. Which is a proper use of a prospectus exemption?",
      ["Selling shares to an investor who meets the accredited investor test",
       "Selling shares to the public because a prospectus was filed last year",
       "Selling to a retail client who signs a waiver of prospectus rights",
       "Selling to the public after posting its financial statements online"],
      "Exemptions let issuers sell to certain investors (such as accredited investors) without a prospectus. A waiver signed by an ineligible investor doesn't create an exemption.", "s"]
  ]);

  add("onboard", [
    ["Eleanor is retired and has $15 million in securities spread across several dealers. She tells her new advisor she's experienced and would like to be treated as an institutional client, so that some retail-client requirements won't apply. She hasn't signed anything yet. Under CIRO rules, which statement is correct?",
      ["She can be classified as institutional only if she requests it and consents in writing",
       "She's automatically institutional, because her securities exceed $10 million",
       "Individuals can never be classified as institutional clients under CIRO rules",
       "She qualifies only if she's also an accredited investor with $1 million of income"],
      "Non-individuals with over $10 million under administration are institutional automatically. An individual over $10 million qualifies only by requesting it and consenting in writing.", "s"],
    ["Which of these clients is automatically an institutional client under CIRO rules, with no request or consent needed?",
      ["A corporation with $25 million of securities under administration",
       "An individual with $12 million who hasn't asked to be classified",
       "A family trust holding about $4 million of investments",
       "A small business that meets the accredited investor test"],
      "Non-individuals with more than $10 million of securities and bullion under administration or management are institutional clients, as are acceptable counterparties, acceptable institutions, regulated entities and non-individual registrants."],
    ["Martin is opening a new account. He wants to borrow from the dealer to buy stocks, and to trade listed equity options. He has already completed the new account application and received the relationship disclosure information. Which additional documents are most appropriate?",
      ["A margin agreement, an options account agreement and the options risk disclosure document",
       "A margin agreement only, since options are always traded within a margin account",
       "An options account agreement only, since margin rules don't apply to options trading",
       "A leverage risk disclosure only, since both margin and options involve leverage"],
      "Margin accounts need a margin agreement. Options trading needs a separate options agreement, approval and delivery of the options disclosure document.", "s"],
    ["A client calls her advisor and asks to buy $25,000 of units of a balanced mutual fund she has read about. The fund pays the dealer an ongoing trailing commission. Before accepting the order, what must the advisor disclose?",
      ["The charges she'll pay, and that the dealer receives trailing commissions",
       "Only the fund's MER, as shown in the most recent Fund Facts document",
       "The advisor's total annual compensation from the fund company",
       "The fund's top ten holdings as of the most recent quarter-end"],
      "Pre-trade disclosure requires telling the client the charges she'll pay on the purchase and whether the firm will receive trailing or other embedded compensation.", "s"],
    ["A numbered company opens an account to invest surplus cash. The dealer asks for its ownership details. The company's lawyer provides a chart showing several holding companies in different countries. Despite reasonable efforts, the dealer can't confirm who ultimately owns or controls the company. What should the dealer do?",
      ["Verify the identity of its most senior managing officer and treat it as higher risk",
         "Open the account normally, since it has already taken reasonable measures",
         "Refuse the account and file a Large Cash Transaction Report with FINTRAC",
         "Accept the lawyer's written statement that no individual owns or controls 25% or more"],
      "When beneficial ownership can't be confirmed, FINTRAC rules require verifying the identity of the most senior managing officer and applying enhanced measures.", "s"],
    ["Kwame's account isn't discretionary. He calls his advisor and says, 'Buy 500 shares of ABC sometime today when you think the price is right. I'm in meetings all afternoon.' The advisor wonders whether he can accept this. Which statement is most accurate?",
      ["This is limited time-and-price discretion on a client-specified order, which is generally allowed",
         "He can't accept it without written discretionary authority that the firm has reviewed and approved",
         "He must enter a market order right away, since he can't choose the timing",
         "He may also substitute a similar stock if ABC looks too expensive at any point today"],
      "Discretion over only the time and price of an order the client specified (security and quantity) is different from discretionary trading, where the advisor decides what to buy or sell.", "s"],
    ["Tasha, 25, is opening an account. Her new account application shows annual income of $40,000 from a part-time job and a net worth of $5 million. She doesn't explain the gap, and the advisor doesn't ask. Which approach is most appropriate?",
      ["Ask about the source of her wealth and confirm the figures before relying on them",
         "Record the figures as given, since KYC relies on what the client provides",
         "Reduce her net worth estimate to a figure consistent with her income",
         "Refuse to open the account, because the financial information she provided is inconsistent"],
      "KYC information must be accurate, and unexplained wealth is also an AML concern. Asking about the source of wealth addresses both.", "s"],
    ["Brenda, 82, has an investment account. Her son presents a power of attorney that Brenda signed three years ago, which gives him authority over her 'banking matters.' He asks the advisor to sell $40,000 of her bonds and transfer the money to her bank account. What should the firm do?",
      ["Check the POA's scope and act only if it clearly covers investment transactions",
       "Accept his instructions, because any POA covers all of the client's finances",
       "Accept his instructions for sales, but refuse any instructions to buy",
       "Have him sign the trade ticket on Brenda's behalf, then process the sale"],
      "An attorney can act only within the authority the POA grants. A POA limited to banking may not cover trading in a securities account.", "s"],
    ["Over several weeks, an 88-year-old client has made unusual withdrawals and seems confused about where the money went. The firm reasonably suspects financial exploitation and decides to contact her trusted contact person, her niece. What information should the firm share with the niece?",
      ["Only what's needed for the concern, such as her wellbeing or whether she has a POA",
         "Copies of all her recent statements, so the niece can review every withdrawal in detail",
         "Her online login details, so the niece can monitor the account directly",
         "Nothing at all, since the firm may not tell a trusted contact anything"],
      "A TCP may be contacted about suspected exploitation, capacity or contact details. The firm should share only what's necessary.", "s"],
    ["Ines works in operations at another CIRO investment dealer. She wants to open a personal trading account at your firm and has provided her employer's written consent. Which additional requirement typically applies?",
      ["Her employer gets access to copies of her statements and trade confirmations",
         "She may only hold mutual funds and GICs in the account, not individual stocks",
         "Each of her personal trades must be pre-approved by CIRO before it's entered",
         "She must close any accounts she already holds at her employer"],
      "Firms supervise their employees' trading, so accounts at other dealers need employer consent, and the employer gets access to the account records.", "s"],
    ["An advisor believes that Pierre, 45, who earns a stable salary, could benefit from borrowing $150,000 against his home to invest in a diversified equity portfolio. Pierre seems interested but hasn't decided. Apart from assessing suitability, what must the advisor do before Pierre acts on the recommendation?",
      ["Give him the leverage risk disclosure before he borrows to invest",
       "Give him the leverage disclosure within 30 days after he borrows",
       "Give him the leverage disclosure only if his investments lose value",
       "Give him the leverage disclosure only if he asks about the risks"],
      "Clients must receive the leverage risk disclosure before acting on a recommendation to borrow to invest, and the strategy itself must be suitable.", "s"],
    ["An order-execution-only dealer's website offers research reports, stock screeners and model portfolios. A client phones a representative and asks which of two technology stocks he should buy for his TFSA. What can the representative do?",
      ["Point him to the research and tools, without recommending either stock for him",
       "Recommend one of the stocks, as long as no fee is charged for the advice",
       "Recommend one of the stocks, provided a suitability assessment is documented",
       "Recommend one of the stocks, since the research on the website supports it"],
      "OEO dealers can provide general information and tools, but can't make personalized recommendations.", "s"],
    ["Luc and Amira are opening a joint account. Luc earns $180,000 and has a large pension. Amira is a student with no income, and the account will be funded mostly by Luc. Luc says he'll give most of the instructions. How should KYC be handled?",
      ["Collect KYC for both holders, and base suitability on both of their circumstances",
         "Collect KYC only for Luc, because he funds the account and will give most instructions",
         "Collect KYC only for the holder with the higher income and net worth",
         "Average the two holders' incomes and record a single combined figure"],
      "Suitability for a joint account must reflect all account holders.", "s"],
    ["A firm is updating its relationship disclosure information for new retail clients. Which item is required content?",
      ["The content and frequency of the reports the client will receive",
       "The advisor's personal sales targets for the coming year",
       "A promise that recommended products will always be the lowest cost",
       "The names of other clients with similar investment portfolios"],
      "RDI describes the relationship, products, costs, conflicts, suitability process, reporting and complaint handling."],
    ["A new client travels most of the year and wants her statements, trade confirmations and tax slips sent only by email, with no paper copies. The firm offers electronic delivery. What does it need before stopping paper delivery?",
      ["The client's informed consent to electronic delivery", "Nothing, since electronic delivery is the default for all clients", "CIRO's approval for the client to have a paperless account", "A signed waiver of her right to receive statements at all"],
      "Documents can be delivered electronically with the client's consent. She must still receive them.", "s"],
    ["While completing the account application, a new client describes herself as a 'sophisticated investor' who needs no explanations. During the conversation, she can't explain the difference between a stock and a bond, and she has never held either. How should her investment knowledge be recorded?",
      ["As limited, based on a reasonable assessment of what she actually knows",
       "As sophisticated, because KYC must reflect the client's own description",
       "As sophisticated, with a note in the file that the advisor disagrees",
       "As good, as a compromise between her view and the advisor's view"],
      "KYC must be accurate. The advisor should make a reasonable assessment and discuss it with the client, not just record her self-description.", "s"],
    ["A corporate client's board resolution, on file with the dealer, authorizes only its CFO to give trading instructions. One afternoon, the company's CEO calls the advisor to sell $200,000 of bonds in the corporate account, saying the CFO is on vacation. What should the advisor do?",
      ["Accept instructions only from persons authorized by the resolution",
       "Accept the order, since the CEO outranks the CFO in the company",
       "Accept the order once the CEO confirms the instructions by email",
       "Accept the order because it's a sale, not a purchase of securities"],
      "Corporate accounts follow the authority documented by the corporation. The firm needs an updated resolution to accept the CEO's instructions.", "s"],
    ["On Monday at 9 a.m., a client deposits $8,000 in cash at his advisor's branch. At 4 p.m. the same day, he returns and deposits another $3,000 in cash with a different employee, who doesn't know about the morning deposit. Which statement is correct?",
      ["A Large Cash Transaction Report is required, as the cash totals $10,000+ within 24 hours",
         "No report is required, because two different employees accepted the two cash deposits",
         "A report is required only if both deposits were made at the same teller",
         "A report is required only if the client's behaviour seems suspicious"],
      "The 24-hour rule aggregates cash transactions by or for the same person, whichever employee handled them.", "c"],
    ["During onboarding, Grace mentions that a family friend will 'help out' by depositing money into her investment account from time to time. She can't say how often or how much. What does the dealer need to do?",
      ["Make a third-party determination and record the friend's information",
       "Nothing further, since only the account holder's identity matters",
       "Reject any deposit that comes from anyone other than the client",
       "Report the friend to FINTRAC as a suspicious person right away"],
      "When a third party may be involved in transactions, the dealer must determine and record who that person is.", "s"],
    ["An advisor suggests that Joan, a new client, open a fee-based account charging 1.25% a year. Joan plans to buy a few ETFs and hold them for many years, trading perhaps once a year. Before Joan agrees, what must the advisor make sure she understands?",
      ["The fee, what it covers, and how it compares with paying per trade",
       "That the fee is tax-deductible in every type of account she holds",
       "That the fee already includes the MERs of any funds she buys",
       "That the fee will be charged quarterly rather than once a year"],
      "Account-type suitability includes whether the fee structure makes sense for the client's expected activity and needs.", "s"]
  ]);

  add("complaints", [
    ["A client writes to her dealer with several complaints. She says her advisor recommended a high-risk leveraged ETF for her conservative income account and described it as 'principal protected.' She also says he entered one purchase before she approved it, and that her account statement was mailed to another client. How should the firm handle this?",
      ["Treat it as one complaint, acknowledge it, investigate every allegation and respond on time",
       "Treat only the suitability issue as a complaint, and pass the mailing error to the branch",
       "Ask her to file a separate written complaint for each issue before beginning any review",
       "Refer the whole matter to OBSI right away, because several serious allegations are involved"],
      "Every allegation (suitability, misrepresentation, unauthorized trading, privacy breach) is part of the complaint and must be investigated and answered under the firm's process. Serious allegations may also need to be reported to CIRO.", "s"],
    ["A client phones his advisor, upset that he was never told about a 2% redemption fee charged when he sold a fund. He says he wants the fee refunded, but doesn't want to put anything in writing. What must the firm do?",
      ["Record the verbal complaint and handle it like a written complaint",
       "Treat it as a service inquiry, since only written complaints count",
       "Ask the client to submit his complaint in writing within ten days",
       "Let the advisor settle it informally with the client by phone"],
      "Complaints can be verbal or written, and both must be handled through the complaint process.", "s"],
    ["A client complains in writing that her branch manager pressured her into buying a structured product. The branch manager also supervises her advisor and approved the trade. Who should investigate the complaint?",
      ["Someone independent of the branch, such as compliance or another senior supervisor",
         "The branch manager, because he knows the client and the product best",
         "The client's advisor, because he entered the trade and knows the details of the account",
         "OBSI, because the complaint involves a manager rather than an advisor"],
      "Complaints must be handled fairly and objectively. A person who is the subject of a complaint shouldn't investigate it.", "s"],
    ["Thirty days after filing a written complaint, a client hears nothing beyond the firm's acknowledgment letter. Frustrated, she contacts OBSI and asks it to investigate immediately. What is OBSI most likely to tell her?",
      ["The firm generally has 90 days to respond before OBSI can take the case",
       "OBSI will start investigating right away, since she has already complained",
       "OBSI can't help her, because the firm is a member of CIRO",
       "She must go through arbitration first, before OBSI can review the case"],
      "Clients can go to OBSI if the firm doesn't provide a final response within 90 days, or within 180 days after receiving the final response.", "s"],
    ["When a retail client opens an account, which complaint-related information must the firm provide?",
      ["How to make a complaint and the options available, such as OBSI",
       "A list of every complaint the firm received in the past year",
       "The advisor's personal complaint history on file with CIRO",
       "A form waiving the client's right to take the firm to court"],
      "Clients receive complaint-handling information, including CIRO's complaint brochure, at account opening."],
    ["After investigating, a firm agrees to pay a client $15,000 to settle her complaint about unsuitable trades. Its draft settlement agreement contains four clauses. Which clause is NOT permitted?",
      ["A clause that prevents the client from reporting the matter to CIRO",
       "A release of any further claims about the same trades",
       "A requirement to keep the settlement amount out of the public eye",
       "A statement that the payment is not an admission of liability"],
      "Settlement agreements can't prevent clients from reporting to, or cooperating with, regulators or law enforcement.", "s"],
    ["A firm receives a written complaint alleging that an advisor signed a client's name on an account transfer form without permission. The firm opens an internal investigation. What else may the firm have to do?",
      ["Report the matter to CIRO", "Report the matter to CIPF", "Report it to FINTRAC as a cash transaction", "Nothing further until a court rules"],
      "Firms must report certain complaints and events, especially serious allegations such as theft, fraud, forgery or misappropriation, to CIRO.", "s"],
    ["A client reviews her annual charges and compensation report and sees $1,800 of trailing commissions she didn't know about. She calls, upset that she has been 'secretly charged.' What is the best first response?",
      ["Explain how trailers work, and treat it as a complaint if she's still dissatisfied",
         "Refund the full $1,800 right away to avoid any regulatory problem",
         "Tell her trailers are paid by the fund company, so they don't affect her returns at all",
         "Close the matter, since the report met all CRM2 disclosure requirements"],
      "Trailers are embedded in fund costs and do affect returns. The advisor should explain them, and treat continuing dissatisfaction as a complaint.", "s"],
    ["A firm is investigating a complaint about unsuitable trades. It needs records from a fund company that won't arrive for several weeks, so it won't be able to give a final response within 90 days. What must it do?",
      ["Tell the client about the delay, the reason, the expected timing and her right to go to OBSI",
       "Pause the 90-day deadline until the records arrive, since the delay isn't the firm's fault",
       "Close the complaint for now and reopen it once all of the records have arrived",
       "Pay the client the amount she claimed, so that the deadline no longer applies"],
      "If the firm can't respond within 90 days, it must tell the client why and remind her of her right to go to OBSI.", "s"],
    ["A client takes her complaint to OBSI, which recommends that the firm pay her $8,000. The firm agrees. She believes her losses were closer to $20,000. What options does she generally still have?",
      ["She may pursue other avenues, such as arbitration or the courts",
       "None, because OBSI's recommendation is final and binding on her",
       "She can ask CIRO to order the firm to pay her a larger amount",
       "She can claim the remaining $12,000 from CIPF as a covered loss"],
      "OBSI's process is free and voluntary for the client; it doesn't take away her other legal remedies (subject to any release she signs)."],
    ["Sonia, an advisor, realizes she bought the wrong fund for a client last week. The client hasn't noticed, and the wrong fund has fallen 3%. What should Sonia do?",
      ["Report the error so the firm can correct it and make the client whole",
       "Quietly switch the client into the correct fund and say nothing",
       "Wait to see whether the wrong fund recovers before doing anything",
       "Tell the client it was a recommendation and offer to switch funds"],
      "Errors must be reported and corrected by the firm, at the firm's expense, with the client informed.", "s"],
    ["A firm's complaint records show that three different clients of the same advisor complained about undisclosed fees within six months. Each complaint was resolved with a small refund. What do these records most likely call for?",
      ["A supervisory review of the advisor's practices, beyond each complaint",
         "No further action, since each of the three complaints was already resolved",
         "Moving the three clients to other advisors without any review",
         "Reporting the clients to CIRO for filing coordinated complaints"],
      "Firms must look for patterns in complaints and act on the underlying issue.", "s"]
  ]);
})();
