// Exam-style questions (CIRE practice exam format), part 4: Element 7 securities, managed products
// and mutual funds, and Element 8 derivatives. Format: [question, [correct, wrong, wrong, wrong], explanation, kind]
window.QB_HARD = window.QB_HARD || {};
(function () {
  const add = (k, list) => { window.QB_HARD[k] = (window.QB_HARD[k] || []).concat(list); };

  // ---------- Element 7: fixed income ----------
  add("fixed", [
    ["How do treasury bills give investors a return?",
      ["They're bought at a discount and mature at face value", "They pay interest coupons twice a year until maturity", "They pay quarterly dividends set by the government", "Their face value rises each year with the rate of inflation"],
      "T-bills pay no coupon. The return is the difference between the discounted purchase price and the face value paid at maturity.", "r"],
    ["What is commercial paper?",
      ["Short-term unsecured debt issued by corporations", "Long-term secured bonds issued by governments", "A certificate of deposit insured by CDIC", "A preferred share that pays a fixed dividend"],
      "Commercial paper is a short-term promissory note, usually sold at a discount by large, creditworthy companies.", "r"],
    ["A client holds a strip bond in a non-registered account. What is the tax issue?",
      ["Accrued interest is taxed yearly though no cash is paid", "No tax is payable until the bond matures or is sold", "The gain at maturity is taxed as an eligible dividend", "The interest is tax-free because there are no coupons"],
      "The CRA taxes the interest that accrues on a strip bond each year even though nothing is paid until maturity. Strips are often better held in registered accounts.", "s"],
    ["Compared with a coupon bond of the same maturity and yield, how does a strip bond's price behave?",
      ["It's more sensitive to rate changes", "It's less sensitive to rate changes", "It's unaffected by rate changes", "It responds only to credit changes"],
      "With no coupons, all of a strip's value comes at maturity, so it has a longer duration and more price volatility.", "r"],
    ["A bond with a 4% coupon trades at $95 per $100 of face value. Which statement is true?",
      ["Its yield is higher than its coupon rate", "Its yield is lower than its coupon rate", "Its yield is equal to its coupon rate", "Its coupon will rise to match the yield"],
      "A bond priced below par (at a discount) yields more than its coupon, because the buyer also gains the discount at maturity.", "r"],
    ["A bond with a 5% coupon ($50 a year per $1,000) trades at $1,040. What is its current yield?",
      ["4.81%", "5.00%", "5.20%", "4.00%"],
      "Current yield = annual coupon ÷ price = $50 ÷ $1,040 = 4.81%.", "c"],
    ["Market interest rates rise by 1%. Which bond's price will fall the most?",
      ["A 25-year bond with a 2% coupon", "A 3-year bond with a 6% coupon", "A 25-year bond with a 7% coupon", "A 3-year bond with a 2% coupon"],
      "Longer maturities and lower coupons mean higher duration, so the long, low-coupon bond is the most sensitive.", "r"],
    ["A bond has a modified duration of 6. If its yield rises by 0.5%, about how much will its price fall?",
      ["3%", "6%", "0.5%", "12%"],
      "Price change ≈ −duration × yield change = −6 × 0.5% = −3%.", "c"],
    ["Which of these is the lowest credit rating still considered investment grade?",
      ["BBB (low)", "BB (high)", "A (low)", "B (high)"],
      "Investment grade runs from AAA down to BBB (low), or BBB−. Anything below is high yield.", "r"],
    ["During a recession, what typically happens to the yield spread between corporate and government bonds?",
      ["It widens", "It narrows", "It disappears", "It reverses"],
      "Investors demand more compensation for default risk when the economy weakens, so corporate spreads widen.", "r"],
    ["Why does a callable bond usually yield more than a similar non-callable bond?",
      ["The issuer can redeem it early, usually after rates fall", "The investor can demand early repayment at any time, at par", "It's fully guaranteed by the federal government", "It can be converted into the issuer's common shares"],
      "The call feature benefits the issuer, which can refinance if rates fall. Investors want a higher yield for bearing that reinvestment risk.", "r"],
    ["What does a retractable bond let the holder do?",
      ["Sell it back to the issuer at par on set dates", "Convert it into the issuer's common shares", "Extend its maturity at the original coupon", "Switch to a floating-rate coupon at any time"],
      "A retraction feature lets the holder shorten the term by redeeming early. It benefits the holder, so the bond yields less.", "r"],
    ["A client buys a bond between coupon dates. What does she pay on top of the price?",
      ["Accrued interest owed to the seller", "The next full coupon, paid in advance", "A withholding tax on the next coupon", "A redemption fee to the issuer"],
      "The seller has earned interest since the last coupon date. The buyer pays it, then receives the full coupon on the next payment date.", "r"],
    ["How is bond interest taxed in a non-registered account?",
      ["Fully, at the investor's marginal rate", "Like a dividend, with a tax credit", "As a capital gain, half of it taxable", "Only when the bond reaches maturity"],
      "Interest income is fully taxable and gets no preferential treatment.", "r"],
    ["Which is a disadvantage of owning individual bonds compared with a bond fund?",
      ["Diversifying usually takes a larger amount of money", "Individual bonds pay no income until they mature", "Individual bonds have no fixed maturity date", "Individual bond prices never change before maturity"],
      "Bonds often trade in large minimums, so a small investor can't easily spread credit risk across many issuers.", "r"],
    ["Where can an investor find the credit rating of a Canadian corporate bond?",
      ["From agencies such as Morningstar DBRS or S&P", "From the Bank of Canada's rate announcements", "Only from the issuer's own marketing brochure", "From Statistics Canada's monthly CPI report"],
      "Credit rating agencies publish ratings on issuers and their debt. They are a key information source for bond investors.", "r"],
    ["How do most retail investors buy individual corporate bonds in Canada?",
      ["Through a dealer, which trades them over the counter", "On the TSX, in the same way as listed common shares", "Directly from the Bank of Canada at auction", "Only by buying units of a bond mutual fund"],
      "Most bonds trade over the counter through dealers' trading desks, often from the dealer's own inventory.", "r"],
    ["What does an inverted yield curve show?",
      ["Short-term yields are higher than long-term yields", "Long-term yields are higher than short-term yields", "All maturities have exactly the same yield", "Corporate yields are below government yields"],
      "An inverted curve often reflects expectations that rates will fall and is widely watched as a recession warning.", "r"]
  ]);

  // ---------- Element 7: equities and indices ----------
  add("equity", [
    ["Which feature distinguishes common shares from most preferred shares?",
      ["Voting rights", "A fixed dividend", "Priority on wind-up", "A maturity date"],
      "Common shareholders usually vote. Preferred shareholders usually have a fixed dividend and priority over common shares, but no vote.", "r"],
    ["If a company is liquidated, how do preferred shareholders rank?",
      ["After creditors, ahead of common shareholders", "Ahead of all creditors, including bondholders", "Equally with the company's common shareholders", "After the common shareholders have been repaid"],
      "Creditors (including bondholders) are paid first, then preferred shareholders, then common shareholders.", "r"],
    ["A company skips two years of dividends on its cumulative preferred shares. What must it do before paying common dividends again?",
      ["Pay all the missed preferred dividends", "Nothing; skipped dividends are lost", "Redeem all of the preferred shares", "Convert the preferred shares to common"],
      "Cumulative preferred dividends in arrears must be paid in full before any common dividend.", "s"],
    ["What is a rate-reset preferred share?",
      ["Its dividend resets periodically to a bond yield plus a spread", "Its share price is reset to $25 at the end of each year", "It converts into common shares every five years", "Its dividend rate is set each year by a vote of the common shareholders"],
      "Rate-reset preferreds reset their dividend (often every five years) based on a benchmark yield plus a fixed spread.", "r"],
    ["Why do straight perpetual preferred shares tend to fall when interest rates rise?",
      ["Their fixed dividends look less attractive than new yields", "Their dividends are always cut when interest rates rise", "They are usually redeemed early when rates go up", "They lose their voting rights when rates go up"],
      "Like long bonds, fixed-rate perpetual preferreds have long durations, so their prices fall when yields rise.", "r"],
    ["Which dividend date determines who is entitled to a declared dividend?",
      ["The record date", "The declaration date", "The payment date", "The ex-rights date"],
      "Shareholders on the company's books on the record date receive the dividend. With T+1 settlement, the ex-dividend date is the same day.", "r"],
    ["Why do Canadian investors pay less tax on eligible dividends than on the same amount of interest?",
      ["The dividend tax credit offsets tax paid by the corporation", "Dividends from Canadian companies aren't taxable at all", "Dividends are treated as capital gains for tax purposes", "Interest income is taxed twice, at two different levels"],
      "The gross-up and dividend tax credit recognize that the corporation has already paid tax on the profits it distributes.", "r"],
    ["A client receives $1,000 of eligible dividends from Canadian companies. With a 38% gross-up, how much is included in taxable income?",
      ["$1,380", "$1,000", "$620", "$1,500"],
      "Taxable amount = $1,000 × 1.38 = $1,380. The dividend tax credit is then applied against the tax on this amount.", "c"],
    ["How are dividends from US stocks held in a non-registered account taxed in Canada?",
      ["As ordinary income, with credit for US tax withheld", "With the Canadian dividend gross-up and tax credit", "As capital gains, with half included in income", "They aren't taxed in Canada at all"],
      "Foreign dividends don't qualify for the dividend tax credit. They're fully taxable, with a foreign tax credit for withholding tax.", "r"],
    ["A client owns 300 shares trading at $90. The company does a 3-for-1 stock split. What does she hold afterward?",
      ["900 shares at about $30", "100 shares at about $270", "900 shares at about $90", "300 shares at about $30"],
      "A split multiplies the shares and divides the price, leaving the value ($27,000) unchanged.", "c"],
    ["Why might a company consolidate its shares (a reverse split)?",
      ["To raise a low share price, e.g. to meet listing rules", "To increase the number of shares held by investors", "To pay shareholders a stock dividend this year", "To reduce the shareholders' equity on its books"],
      "A consolidation reduces the number of shares and raises the price per share proportionally. Value isn't changed.", "r"],
    ["How do Canadian investors usually buy shares of listed companies?",
      ["Through a dealer, on an exchange or ATS", "Directly from the company's treasury", "From the Bank of Canada", "Only through mutual funds"],
      "Investment dealers execute share purchases on exchanges and alternative trading systems on the client's behalf.", "r"],
    ["Where can investors see the trades reported by company insiders in Canada?",
      ["SEDI", "SEDAR+", "FINTRAC", "CDS"],
      "The System for Electronic Disclosure by Insiders (SEDI) holds insider trading reports. SEDAR+ holds company filings.", "r"],
    ["A client with $25,000 wants exposure to 200 large companies. Why might a managed product suit her better than buying individual stocks?",
      ["It gives broad diversification for a small amount", "It guarantees her a minimum annual return", "It removes all market risk from the portfolio", "It lets her vote at every company's meeting"],
      "Pooled products give small investors instant diversification and professional management that would be costly to replicate with individual stocks.", "s"],
    ["Which is an advantage of owning individual common shares directly?",
      ["Control over what to own and when to sell", "Dividends that are guaranteed every year", "Priority over creditors on liquidation", "A fixed value when the shares mature"],
      "Direct owners choose their holdings and control the timing of gains and losses for tax purposes. Dividends aren't guaranteed.", "r"],
    ["Which is a disadvantage of owning common shares?",
      ["Dividends can be cut and prices can fall sharply", "Losses can exceed the amount originally invested", "Companies are legally barred from paying dividends", "Shareholders are personally liable for company debts"],
      "Shareholders' losses are limited to their investment, but prices are volatile and dividends are paid at the board's discretion.", "r"],
    ["A client wants low-cost exposure that tracks the overall Canadian stock market. Which approach fits best?",
      ["A broad index ETF", "Active stock picking", "Sector rotation", "Market timing"],
      "Passive indexing aims to match a benchmark at low cost. Active approaches try to beat it, usually at higher cost.", "s"],
    ["What is the main argument for active equity management?",
      ["The chance to beat the benchmark after fees", "Lower fees than passive management", "Guaranteed outperformance of the market index", "No tracking difference from the index"],
      "Active managers aim to outperform through security selection or timing. Many don't, after their higher fees.", "r"],
    ["In a price-weighted index, which stock has the most influence on the index?",
      ["The highest-priced stock", "The largest by market cap", "The most heavily traded", "They all have equal weight"],
      "In a price-weighted index (like the Dow), a given percentage move in a high-priced stock moves the index more.", "r"],
    ["How is the S&P/TSX Composite Index weighted?",
      ["By float-adjusted market capitalization", "By each stock's share price", "Equally, by the number of companies in it", "By each stock's dividend yield"],
      "Larger companies (by the value of their freely tradable shares) have more influence on the index.", "r"],
    ["How does a total return index differ from a price return index?",
      ["It assumes dividends are reinvested", "It excludes all price changes", "It includes only dividend payers", "It's adjusted for inflation"],
      "A price index tracks price changes only. A total return index adds reinvested dividends and other distributions.", "r"],
    ["Which is a common use of a market index?",
      ["Benchmarking performance", "Guaranteeing returns", "Setting the policy rate", "Calculating client fees"],
      "Indices summarize market moves, serve as benchmarks and are the basis for index funds, ETFs and derivatives.", "r"],
    ["A price-weighted average of three stocks priced at $20, $50 and $80 uses a divisor of 3. If the $80 stock rises 10%, by about how much does the average rise?",
      ["5.3%", "3.3%", "10%", "1.8%"],
      "Old average = $150 ÷ 3 = $50. New average = ($20 + $50 + $88) ÷ 3 = $52.67, a rise of about 5.3%.", "c"],
    ["How does a stock index generally differ from a simple average of stock prices?",
      ["An index uses a base value and usually weights by market cap", "An index uses the median stock price rather than the mean stock price", "An index includes stocks from only one industry at a time", "An index ignores daily price changes in its constituents"],
      "An index expresses value relative to a base period and usually weights companies by size. A simple average just adds prices and divides.", "r"],
    ["An investor wants to measure stock market performance in developed countries outside North America. Which index fits?",
      ["The MSCI EAFE Index", "The S&P/TSX 60 Index", "The Dow Jones Industrial Average", "The FTSE Canada Universe Bond Index"],
      "MSCI EAFE covers developed markets in Europe, Australasia and the Far East.", "r"]
  ]);

  // ---------- Element 7: managed products, mutual funds, ETFs and other investments ----------
  add("funds", [
    ["A client places an order to buy a mutual fund at 2:00 p.m. ET. At what price is it filled?",
      ["The NAVPS calculated at that day's close", "The NAVPS calculated at the previous day's close", "The market price at 2:00 p.m.", "The NAVPS on the settlement date"],
      "Mutual funds use forward pricing: orders received before the cut-off get that day's closing net asset value per unit.", "s"],
    ["A fund has assets of $250 million, liabilities of $5 million and 10 million units outstanding. What is its NAVPS?",
      ["$24.50", "$25.00", "$25.50", "$24.00"],
      "NAVPS = (assets − liabilities) ÷ units = ($250M − $5M) ÷ 10M = $24.50.", "c"],
    ["Why can a closed-end fund trade at a discount to its net asset value?",
      ["Its fixed number of shares trade on an exchange at market prices", "It is priced once a day at NAV by the fund company", "Its units can be redeemed at NAV from the fund whenever investors want", "It must invest only in bonds, which pay low yields"],
      "Closed-end funds don't continuously issue or redeem shares, so the market price can drift above or below NAV.", "r"],
    ["What keeps an ETF's market price close to its net asset value?",
      ["Creation and redemption of units by authorized dealers", "A fixed number of units that never changes", "A single daily price that is set by the ETF manager", "A guarantee from the exchange that the ETF trades on"],
      "When the price strays from NAV, designated brokers create or redeem units, and that arbitrage pulls the price back.", "r"],
    ["What is a real estate investment trust (REIT)?",
      ["A trust that owns rental property and pays out most of its income", "A bank deposit that is secured by a mortgage on residential property", "A fund that holds only government-guaranteed mortgage bonds and cash", "A company that builds and sells new homes to buyers"],
      "REITs own properties such as offices, malls and apartments, and distribute most of their income to unitholders. Most trade on exchanges.", "r"],
    ["What is a key risk of income trusts?",
      ["Distributions can be cut if cash flow falls", "Distributions are guaranteed by government", "Their units can't trade on an exchange", "Their unit prices never change"],
      "Income trusts pay out most of their cash flow, so a weaker business can mean lower distributions and a lower unit price.", "r"],
    ["Which statement about mutual fund corporations is true?",
      ["They issue shares and can offer several classes of funds", "They issue units and must pay out all income each year", "They're the most common fund structure in Canada", "They can't pay out capital gains dividends to holders"],
      "Mutual fund corporations issue shares, often across several classes (corporate class funds). Mutual fund trusts, which issue units, are more common.", "r"],
    ["Why do mutual fund trusts usually distribute their net income and gains every year?",
      ["So the fund pays no tax; unitholders pay instead", "Because the law forbids funds to reinvest income", "To keep the fund's NAVPS fixed at $10", "So every distribution gets the dividend tax credit"],
      "A mutual fund trust is a flow-through vehicle. Distributing its income keeps tax at the unitholder level.", "r"],
    ["What is a wrap account?",
      ["An account with one asset-based fee covering advice and trading", "A fund that invests only in short-term government bonds", "An account that wraps insurance protection around a fund", "An account that charges a separate commission on every trade"],
      "A wrap program bundles portfolio management, advice, custody and trading into a single fee based on assets.", "r"],
    ["What is a fund of funds?",
      ["A fund that invests in other funds", "A fund that only holds cash", "A fund sold only to pension plans", "A fund that tracks a fund index"],
      "Funds of funds (including many portfolio solutions) hold other funds to build a diversified mix in one product.", "r"],
    ["How do pooled funds typically differ from retail mutual funds?",
      ["They're sold under exemptions to larger investors, often at lower fees", "They must be sold under a prospectus to any investor who wants them", "They're guaranteed by CDIC up to $100,000 per investor", "They trade throughout the day on the Toronto Stock Exchange"],
      "Pooled funds are usually offered without a prospectus to institutions and wealthy investors, with high minimums and lower fees.", "r"],
    ["How is the risk rating in a mutual fund's Fund Facts determined?",
      ["Using the CSA methodology, mainly 10-year return volatility", "Using the fund manager's forecast of future returns", "Using the credit rating of the fund's single largest holding", "Using the number of investors who hold the fund"],
      "The CSA's standardized methodology uses the standard deviation of 10 years of returns (using a reference index if the fund is newer).", "r"],
    ["How many risk categories does the CSA's fund risk classification methodology use?",
      ["Five, from low to high", "Three, from low to high", "Seven, from low to high", "Ten, from low to high"],
      "The categories are low, low to medium, medium, medium to high, and high.", "r"],
    ["What information does a Fund Facts document provide?",
      ["Costs, past returns, the risk rating and top holdings", "The portfolio manager's own personal holdings and trades", "A guarantee of the fund's future returns", "The names and holdings of other unitholders"],
      "Fund Facts is a short, plain-language summary of a fund's investments, performance, risk, costs and suitability.", "r"],
    ["When must a dealer generally deliver Fund Facts for a mutual fund purchase?",
      ["Before the purchase", "Within 30 days after", "Once a year only", "Only on request"],
      "Fund Facts must generally be delivered before the purchase. Limited exceptions allow delivery shortly afterward when the client needs the trade done right away.", "r"],
    ["When must ETF Facts be delivered to a client who buys an ETF?",
      ["Within two days after the purchase", "Before the order can be accepted", "With the client's year-end statement", "Only if the client asks for it"],
      "Because ETFs trade on exchanges, ETF Facts is delivered within two days after the purchase.", "r"],
    ["What does a fund's management expense ratio (MER) include?",
      ["Management fees, operating costs and taxes", "Commissions on the fund's portfolio trades", "Front-end sales charges paid by investors", "Taxes investors pay on fund distributions"],
      "The MER covers management fees, operating expenses and sales taxes. Trading costs are reported separately as the trading expense ratio (TER).", "r"],
    ["Which fund cost is reported separately from the MER?",
      ["The trading expense ratio", "The management fee", "The fund's legal fees", "The custodian's fees"],
      "The TER shows the cost of buying and selling the fund's portfolio securities.", "r"],
    ["What is a trailing commission?",
      ["An ongoing payment from the fund company to the dealer", "A fee the investor pays when redeeming fund units", "A one-time fee the investor pays at the time of purchase", "A penalty for selling fund units within 90 days"],
      "Trailing commissions are paid out of the management fee for as long as the client holds the fund.", "r"],
    ["Which mutual fund purchase option has been banned in Canada since June 2022?",
      ["Deferred sales charges", "Front-end sales charges", "No-load purchases", "Fee-based series"],
      "The CSA banned deferred sales charge (DSC) options, including low-load, because of the conflicts and redemption costs they created.", "r"],
    ["Which statement about trailing commissions has been true since June 2022?",
      ["They can't be paid to order-execution-only dealers", "They're banned for every type of dealer in Canada", "Clients must now pay them directly to the dealer", "They're paid only on bond funds"],
      "OEO dealers don't give advice, so fund companies may no longer pay them trailers.", "r"],
    ["Three funds' assets changed over a year: Fund X from $400M to $440M, Fund Y from $1,200M to $1,140M, Fund Z from $800M to $832M. Assuming no flows in or out, what is the simple average return of the three funds?",
      ["3.0%", "0.5%", "9.0%", "4.0%"],
      "Returns: X +10%, Y −5%, Z +4%. Simple average = (10 − 5 + 4) ÷ 3 = 3.0%. (0.5% is the combined asset-weighted change.)", "c"],
    ["An investor buys 200 shares at $18.50 and later sells them at $21.75 through an online account that charges $9.95 per trade. What is the approximate return after fees?",
      ["17.0%", "17.6%", "15.5%", "18.1%"],
      "Cost = $3,700 + $9.95 = $3,709.95. Proceeds = $4,350 − $9.95 = $4,340.05. Gain = $630.10, or about 17.0%. Without fees the return would be 17.6%.", "c"],
    ["A fund manager first forecasts the economy, then picks sectors, then chooses companies within them. What is this approach called?",
      ["Top-down", "Bottom-up", "Indexing", "Technical"],
      "Top-down starts with the economy; bottom-up starts with individual companies regardless of sector.", "r"],
    ["Which is an advantage of mutual funds for small investors?",
      ["Professional management and diversification", "Trading all day long at current market prices", "Returns that are guaranteed by the fund issuer", "No ongoing fees of any kind"],
      "Funds give small investors diversification, professional management, low minimums and easy redemption.", "r"],
    ["A client buys a mutual fund in a non-registered account in early December, just before its annual distribution. What is the drawback?",
      ["She'll be taxed on gains she didn't benefit from", "She'll lose her units when the distribution is paid", "The distribution can't be reinvested in new units", "She can't redeem her units for a year afterward"],
      "The distribution includes gains earned before she bought, but she's taxed on it ('buying a tax bill'), even though the NAV falls by the same amount.", "s"],
    ["How are distributions from a mutual fund trust held in a non-registered account taxed?",
      ["By type: interest, dividends, capital gains or return of capital", "All as interest income, fully taxable at the investor's marginal rate", "They're all tax-free, since the fund has already paid tax", "All as capital gains, with half included in income"],
      "Each type keeps its tax character in the investor's hands. Return of capital isn't taxed right away but reduces the adjusted cost base.", "r"],
    ["A fund distribution includes return of capital (ROC). How is the ROC treated for tax?",
      ["It's not taxed when received but reduces the ACB", "It's taxed in full as interest income when received", "It's taxed as an eligible dividend when received", "It increases the adjusted cost base of the units"],
      "ROC is a return of the investor's own money. It lowers the adjusted cost base, which increases the capital gain when the units are sold.", "r"],
    ["Which is an advantage of ETFs over most mutual funds?",
      ["Intraday trading and generally lower MERs", "No commissions when buying or selling", "Pricing only once a day at the closing NAV", "A guarantee that the price will equal NAV"],
      "ETFs trade throughout the day and are usually cheaper to own, but buying and selling them involves commissions and bid-ask spreads.", "r"],
    ["A client plans to hold a 2x leveraged ETF for several years. What is the key risk?",
      ["Daily resets mean long-term returns can stray far from 2x", "Leveraged ETFs can't be sold before they mature", "Leveraged ETFs pay fixed coupons instead of index returns", "They're guaranteed to lose no more than the index"],
      "Leveraged and inverse ETFs reset daily, so over longer periods compounding can make results very different from two times the index return.", "s"],
    ["An ETF's market price is $20.15 while its NAV is $20.00. How is it trading?",
      ["At a premium to NAV", "At a discount to NAV", "Exactly at NAV", "At its redemption value"],
      "A market price above NAV is a premium; below is a discount.", "r"],
    ["For someone investing $100 a month, which is a disadvantage of ETFs compared with mutual funds?",
      ["Commissions and spreads on each purchase", "Higher management expense ratios", "Less transparency about holdings", "Buying only at the end-of-day net asset value"],
      "Trading costs on small, frequent purchases can eat into returns, though many platforms now offer commission-free ETF purchases.", "r"],
    ["How can a Canadian investor buy ETFs?",
      ["Through a dealer, on an exchange", "Only from the ETF's manager", "Only through a bank savings account", "Only in registered accounts"],
      "ETFs are listed securities bought and sold through dealers on exchanges, like shares.", "r"],
    ["A client wants exposure to emerging-market bonds without buying individual foreign bonds. What is the main benefit of a managed product here?",
      ["Access to an asset class and region that's hard to reach", "Complete elimination of the foreign currency risk on the bonds", "A guaranteed level of income each year", "Exemption from tax on all distributions"],
      "Managed products give access to asset classes, sectors and regions that would be hard or costly to invest in directly.", "s"],
    ["A sector ETF holds only Canadian bank stocks. Which risk does it present?",
      ["Concentration risk", "Currency risk only", "No market risk", "Credit risk only"],
      "Focusing on one sector reduces diversification, so the fund is exposed to problems affecting that industry.", "r"],
    ["Which feature is typical of a hedge fund?",
      ["Leverage, short selling and performance fees", "Daily liquidity and very low fees", "Sale to all retail investors by prospectus", "Holdings limited to treasury bills"],
      "Hedge funds use flexible strategies and charge performance fees. They're usually sold under exemptions, with limited liquidity and less disclosure.", "r"],
    ["A hedge fund charges a 20% performance fee subject to a high-water mark. What does the high-water mark do?",
      ["It allows fees only on gains above the previous peak value", "It caps the losses the fund can suffer in a single year", "It sets a minimum return the fund must earn each year", "It limits the amount of leverage the fund may use"],
      "After a loss, the manager earns no performance fee until the fund recovers past its previous high.", "r"],
    ["What are alternative mutual funds ('liquid alts')?",
      ["Prospectus funds allowed more leverage and shorting", "Hedge funds sold only to accredited investors under exemptions", "Funds that hold only physical real estate and mortgages", "Funds whose principal is guaranteed by the issuing bank"],
      "Under NI 81-102, alternative mutual funds are available to retail investors by prospectus but may use more leverage, short selling and concentration.", "r"],
    ["A principal-protected note guarantees the client's principal at maturity. What is a key risk?",
      ["The guarantee depends on the issuer; selling early may mean a loss", "The principal is insured by CDIC in every circumstance, without limit", "It always pays the full index return at maturity", "Its value can't fall before it reaches maturity"],
      "The guarantee is only as good as the issuer and applies only at maturity. Returns may be capped, and there may be no active market to sell early.", "r"],
    ["A market-linked note pays 70% of an index's gain, capped at a 30% total return over five years. The index rises 50%. What does the note pay?",
      ["30%", "35%", "50%", "15%"],
      "70% × 50% = 35%, but the cap limits the return to 30%.", "c"],
    ["Which is a key risk of investing in crypto assets?",
      ["High volatility and losses from hacks or custody failures", "Values that are guaranteed by the Bank of Canada at all times", "Fixed interest payments that may be delayed", "CDIC insurance limits on large holdings"],
      "Crypto assets are highly volatile, have no intrinsic cash flows and carry platform, custody and fraud risks.", "r"],
    ["How can a client get exposure to Bitcoin through a Canadian investment dealer?",
      ["Through a Bitcoin ETF listed in Canada", "Only through foreign online platforms", "Only by mining it on her own computer", "Through a bank's market-linked GIC"],
      "Canadian-listed crypto ETFs can be bought through dealers like any other ETF, with prospectus disclosure.", "r"],
    ["A fund excludes tobacco and weapons makers from its holdings. Which ESG strategy is this?",
      ["Negative screening", "Impact investing", "Positive screening", "Shareholder engagement"],
      "Exclusionary (negative) screening removes companies or sectors. Positive screening picks ESG leaders; impact investing targets measurable outcomes.", "r"],
    ["What is greenwashing?",
      ["Overstating a product's ESG credentials", "Investing only in certified green bonds", "Screening out the largest polluters", "Laundering money through ESG funds"],
      "Greenwashing misleads investors about how sustainable a product really is. The CSA expects funds' names, objectives and disclosure to match their actual ESG practices.", "r"],
    ["Under CSA guidance on ESG-related funds, which practice is expected?",
      ["The name and objectives must reflect its actual ESG focus", "ESG funds must outperform conventional funds each year", "ESG funds can't hold any energy company stocks at all", "ESG funds can be sold without a prospectus or Fund Facts"],
      "Disclosure must accurately describe how ESG factors are used, so investors aren't misled by a fund's name or marketing.", "r"],
    ["Which asset class is generally the most liquid and lowest risk?",
      ["Cash and cash equivalents", "Commodities such as oil", "Common equities", "Long-term government bonds"],
      "Cash equivalents such as T-bills and money market funds offer stability and liquidity but low returns.", "r"],
    ["How do most investors get exposure to commodities such as oil?",
      ["Through futures, ETFs or producers' shares", "By storing the physical commodity themselves", "Through Government of Canada savings bonds", "Only through private placements with producers"],
      "Few investors hold physical commodities. Exposure usually comes through derivatives, commodity ETFs or shares of producers.", "r"]
  ]);

  // ---------- Element 7: taxation of investments ----------
  add("tax", [
    ["A client sells shares in a non-registered account for a $10,000 capital gain. How much is added to his taxable income?",
      ["$5,000", "$10,000", "$6,667", "$0"],
      "Half of a capital gain is taxable. (The proposed increase to two-thirds was cancelled in 2025.)", "c"],
    ["How can a net capital loss be used?",
      ["Against capital gains, back 3 years or forward indefinitely", "Against employment income in the same year that the loss occurs", "Only against gains realized in the same calendar year", "Only against gains realized within the next 7 years"],
      "Capital losses can only offset capital gains. Net losses can be carried back three years or forward indefinitely.", "r"],
    ["A client sells a stock at a loss and buys it back 10 days later. What happens to the loss?",
      ["It's denied as a superficial loss and added to the new ACB", "It's allowed in full, since he sold before buying back", "It's doubled, because the shares were bought back within the month", "It's converted into ordinary income for that tax year"],
      "Buying the same security within 30 days before or after the sale makes it a superficial loss. The loss is added to the cost of the new shares.", "s"]
  ]);

  // ---------- Element 8: derivatives ----------
  add("deriv", [
    ["What right does the buyer of a call option have?",
      ["To buy the underlying at the strike price", "To sell the underlying at the strike price", "To receive the option premium from the writer", "To require the writer to buy the underlying"],
      "A call buyer has the right, but not the obligation, to buy the underlying at the strike price. The writer must sell if assigned.", "r"],
    ["What obligation does the writer of a put option take on?",
      ["To buy the underlying at the strike if assigned", "To sell the underlying at the strike if assigned", "To pay the premium to the buyer of the option", "None, since only the buyer has obligations"],
      "The put writer receives the premium and must buy the underlying at the strike price if the holder exercises.", "r"],
    ["When can a European-style option be exercised?",
      ["Only at expiry", "Any time until expiry", "Only on European exchanges", "Only before the first month"],
      "European options can be exercised only at expiry; American options can be exercised at any time up to and including expiry.", "r"],
    ["A put option has a $50 strike, and the stock trades at $44. How would you describe the put?",
      ["In the money by $6", "Out of the money by $6", "At the money", "In the money by $50"],
      "A put is in the money when the stock price is below the strike. Intrinsic value = $50 − $44 = $6.", "c"],
    ["All else equal, which change would increase the premium of a call option?",
      ["Higher volatility in the underlying", "A drop in the underlying's price", "Less time remaining until expiry", "A higher strike price"],
      "Premiums rise with volatility and time to expiry. A call is also worth more when the underlying rises or the strike is lower.", "r"],
    ["A call with a $30 strike trades for $4.50 when the stock is at $33. What is its time value?",
      ["$1.50", "$3.00", "$4.50", "$7.50"],
      "Intrinsic value = $33 − $30 = $3.00. Time value = premium − intrinsic value = $4.50 − $3.00 = $1.50.", "c"],
    ["Which statement correctly contrasts forward contracts with futures contracts?",
      ["Forwards are customized OTC contracts with counterparty risk", "Forwards are standardized and trade on regulated exchanges", "Forwards are marked to market and settled every day", "Forwards are cleared and guaranteed by the CDCC"],
      "Futures are standardized, exchange-traded, marked to market daily and cleared. Forwards are private, customizable and carry counterparty risk.", "r"],
    ["What happens when a futures position is marked to market each day?",
      ["Daily gains and losses are settled through margin", "The contract is closed out and reopened daily", "The price is locked until the contract expires", "The exchange guarantees the position will profit"],
      "Each day's gains are credited and losses debited to the margin account. If margin falls too low, the trader must top it up.", "r"],
    ["A company with floating-rate debt wants predictable, fixed interest payments. Which derivative fits best?",
      ["An interest rate swap: pay fixed, receive floating", "A long call option on government bonds", "A currency forward contract", "A contract for difference on the company's own shares"],
      "The swap's floating receipts offset the floating payments on its debt, leaving the company with fixed payments.", "s"],
    ["What is a contract for difference (CFD)?",
      ["An OTC contract paying the change in an asset's price", "A listed option with a fixed strike price", "A bond whose coupon varies with an index", "A futures contract that requires physical delivery"],
      "A CFD pays the difference between the opening and closing price of an underlying asset without the holder owning it. CFDs are leveraged OTC products.", "r"],
    ["Which is a key risk of contracts for difference (CFDs)?",
      ["Leverage can magnify losses beyond the initial margin", "They're guaranteed by the CDCC against all losses", "There's no counterparty risk with the provider", "Losses are limited to the premium paid upfront"],
      "CFDs are leveraged, so losses can exceed the deposit. The client also depends on the provider as counterparty.", "r"],
    ["A Canadian exporter expecting US-dollar revenue in six months sells US dollars forward. Why?",
      ["To hedge against a fall in the US dollar", "To speculate that the US dollar will rise", "To earn an arbitrage profit between markets", "To increase its exposure to the US dollar"],
      "Locking in the exchange rate now protects the exporter's Canadian-dollar revenue if the US dollar weakens.", "s"],
    ["An investor with no position buys call options on a stock she expects to rise. What is she doing?",
      ["Speculating", "Hedging", "Arbitraging", "Writing"],
      "With no underlying exposure to protect, buying calls is a leveraged bet on the price rising.", "s"],
    ["A stock trades at C$50.00 on the TSX and US$36.50 on the NYSE, and the exchange rate is C$1.38 per US dollar. A trader buys in Toronto and sells in New York at the same time. What is this?",
      ["Arbitrage", "Hedging", "Speculation", "Front running"],
      "US$36.50 × 1.38 = C$50.37, so the stock is cheaper in Toronto. Buying there and selling in New York at the same time locks in the difference: arbitrage.", "s"],
    ["What is initial margin in futures trading?",
      ["A good-faith deposit to open a position", "The full value of the futures contract", "A premium paid to the seller of the contract", "A fee charged by the exchange per trade"],
      "Initial margin is collateral to cover potential losses. It's a fraction of the contract value, which is what creates leverage.", "r"],
    ["A futures contract is worth $100,000 and the initial margin is $8,000. If the contract's value rises 4%, what is the return on the margin deposited?",
      ["50%", "4%", "8%", "12.5%"],
      "Gain = 4% × $100,000 = $4,000. Return on margin = $4,000 ÷ $8,000 = 50%. Leverage magnifies losses the same way.", "c"],
    ["Which is a feature of listed derivatives compared with OTC derivatives?",
      ["Standardized terms and central clearing", "Fully customized terms set by the two parties", "Greater counterparty risk", "Little or no price transparency"],
      "Listed derivatives are standardized, cleared through a clearing house such as CDCC, liquid and transparent. OTC contracts are flexible but less liquid and carry counterparty risk.", "r"],
    ["Which strategy profits if the underlying stock rises?",
      ["Buying a call", "Buying a put", "Writing a call", "Writing a straddle"],
      "Long calls are bullish. Long puts are bearish; writing calls is neutral-to-bearish; a short straddle is neutral.", "r"],
    ["An investor owns 500 shares and writes five call options on them. What is the main goal?",
      ["Earning premium income, giving up gains above the strike", "Protecting the shares fully against a large price drop", "Profiting from a large move in either direction", "Leveraging the gains if the stock rises sharply"],
      "A covered call is an income strategy. The premium adds return but caps the upside, and it offers only limited downside protection.", "r"],
    ["What is buying a put on a stock you already own called?",
      ["A protective put", "A covered call", "A bear spread", "A long straddle"],
      "A protective put sets a floor under the stock's value for the life of the option. It's a hedge.", "r"],
    ["An investor expects a big price move after an earnings release but doesn't know the direction. Which strategy fits?",
      ["A long straddle", "A covered call", "A short straddle", "A bull call spread"],
      "Buying a call and a put with the same strike and expiry profits from a large move either way. It's a volatility strategy.", "s"],
    ["An investor buys a $40 call and sells a $45 call on the same stock with the same expiry. What strategy is this?",
      ["A bull call spread", "A bear put spread", "A long straddle", "A calendar spread"],
      "A bull call spread profits from a moderate rise. Writing the higher-strike call lowers the cost but caps the gain at the $45 strike.", "r"],
    ["Which strategy profits most if the stock stays close to its current price?",
      ["A short straddle", "A long straddle", "Buying calls", "Buying puts"],
      "Writing a call and a put at the same strike collects two premiums, which are kept if the price doesn't move much. The risk is large if it does.", "r"],
    ["Before a client's first options trade, which document must the dealer give the client?",
      ["A derivatives risk disclosure statement", "A take-over bid circular for the underlying", "A Fund Facts document", "The CIPF annual report and coverage brochure"],
      "Clients must receive risk disclosure explaining the risks of derivatives before trading, along with signing the derivatives account documents.", "r"],
    ["Who must approve a new derivatives account before trading begins?",
      ["A qualified designated supervisor", "The client's trusted contact person", "The CDCC", "The Montréal Exchange"],
      "A supervisor qualified for derivatives must review and approve the account application before any trade.", "r"],
    ["A client's futures account is under-margined. Which action is prohibited?",
      ["Letting her open new positions", "Issuing her a margin call", "Liquidating positions to cover", "Sending her a monthly statement"],
      "Trading while under margin, or beyond margin or credit limits, is a prohibited practice. The dealer must call for margin and may liquidate.", "s"],
    ["A client's cumulative derivatives losses exceed the risk limit the firm set for her account. What should the firm do?",
      ["Stop new risk-increasing trades and review the account", "Let her keep trading so she can recover the losses", "Raise her risk limit automatically to fit the losses", "Ignore it until her next monthly statement is issued"],
      "Cumulative losses beyond the account's risk limits must trigger supervisory action. Allowing more trading would be a prohibited practice.", "s"],
    ["What must a client sign before trading derivatives on margin?",
      ["A margin agreement", "A trust deed", "A managed account agreement", "A risk acknowledgement form"],
      "A margin agreement sets out the client's obligations when using leverage, including meeting margin calls.", "r"]
  ]);
})();
