// Exam-style questions (CIRE practice exam format), part 3: Element 5 market and company analysis
// and Element 6 market integrity, trade execution and settlement.
// Format: [question, [correct, wrong, wrong, wrong], explanation, kind]
window.QB_HARD = window.QB_HARD || {};
(function () {
  const add = (k, list) => { window.QB_HARD[k] = (window.QB_HARD[k] || []).concat(list); };

  // ---------- Element 5: economics ----------
  add("econ", [
    ["Which economic theory argues that governments should raise spending during a recession to boost aggregate demand?",
      ["Keynesian economics", "Monetarism", "Supply-side economics", "Rational expectations theory"],
      "Keynesians see insufficient demand as the cause of recessions and favour active fiscal policy. Monetarists focus on the money supply; supply-siders on incentives to produce.", "r"],
    ["A policymaker believes inflation is caused mainly by the money supply growing faster than the economy. Which school of thought is this?",
      ["Monetarism", "Keynesian economics", "Supply-side economics", "Modern portfolio theory"],
      "Monetarists (such as Milton Friedman) argue that steady, predictable money supply growth is the key to stable prices.", "r"],
    ["A government cuts marginal tax rates to encourage people to work, save and invest. Which theory supports this?",
      ["Supply-side economics", "Keynesian economics", "Monetarism", "The quantity theory of money"],
      "Supply-side economics holds that lower taxes and less regulation increase incentives and the economy's productive capacity.", "r"],
    ["The government launches a large stimulus program while the Bank of Canada raises interest rates to fight inflation. What is the likely combined effect?",
      ["The policies partly offset each other", "Both policies push demand sharply higher", "Both policies push demand sharply lower", "Neither policy has any effect on demand"],
      "Expansionary fiscal policy adds to demand while tighter monetary policy restrains it, so the two work against each other.", "s"],
    ["Heavy government borrowing pushes up interest rates and reduces private business investment. What is this called?",
      ["The crowding-out effect", "The multiplier effect", "Stagflation", "Quantitative easing"],
      "When government borrowing competes for savings, higher rates can 'crowd out' private borrowing and investment.", "r"],
    ["Which factor would most likely push long-term interest rates higher?",
      ["Rising inflation expectations", "Weaker demand for credit", "A recession that cuts borrowing", "Lower government borrowing"],
      "Lenders demand higher nominal rates to protect their real return when they expect more inflation.", "r"],
    ["A product's price is set above its market equilibrium price. What will most likely happen?",
      ["A surplus, as supply exceeds demand", "A shortage, as demand exceeds supply", "A new equilibrium at the higher price", "An immediate rise in buyers' demand"],
      "Above equilibrium, sellers offer more than buyers want, creating a surplus that puts downward pressure on price.", "r"],
    ["Which is a key determinant of long-term economic growth?",
      ["Productivity gains from technology and investment", "A temporary cut in the central bank's policy rate", "A one-time increase in government spending", "A short-term rise in consumer confidence"],
      "Long-run growth depends on growth in the labour force and productivity (capital investment, technology, education). Short-term stimulus affects the business cycle, not long-run capacity.", "r"],
    ["In which phase of the business cycle is output at its lowest and unemployment typically near its highest?",
      ["Trough", "Peak", "Expansion", "Early contraction"],
      "The trough is the bottom of the cycle. Unemployment, a lagging indicator, often peaks around or just after it.", "r"],
    ["Which of the following is a leading economic indicator?",
      ["Housing starts", "The unemployment rate", "Real GDP", "Unit labour costs"],
      "Leading indicators (housing starts, stock prices, money supply, new orders) change before the economy. GDP is coincident; unemployment and unit labour costs lag.", "r"],
    ["How is the unemployment rate generally classified as an economic indicator?",
      ["Lagging", "Leading", "Coincident", "Sentiment"],
      "Firms tend to delay hiring and firing, so unemployment changes after the economy has already turned.", "r"],
    ["Workers laid off by a closing coal plant lack the skills needed for the available tech jobs in the region. What type of unemployment is this?",
      ["Structural", "Frictional", "Cyclical", "Seasonal"],
      "Structural unemployment comes from a mismatch between workers' skills or location and available jobs. Frictional is short-term job searching; cyclical comes from recessions.", "s"],
    ["What does the labour force participation rate measure?",
      ["The share of working-age people working or looking for work", "The share of employed workers who have full-time, permanent jobs", "The share of the labour force that is unemployed", "The share of jobs that are in the public sector"],
      "Participation = labour force ÷ working-age population. The labour force includes the employed and the unemployed who are actively looking for work.", "r"],
    ["What does the Consumer Price Index (CPI) measure?",
      ["The cost of a fixed basket of consumer goods and services", "The total output of goods and services in the economy", "The prices that manufacturers receive for their goods", "The average hourly wages paid to Canadian workers"],
      "The CPI tracks the price of a representative basket over time, which is how inflation is measured.", "r"],
    ["A GIC pays 4.5% and inflation is running at 2.8%. What is the approximate real rate of return?",
      ["1.7%", "7.3%", "2.8%", "4.5%"],
      "Real return ≈ nominal return − inflation = 4.5% − 2.8% = 1.7%.", "c"],
    ["What is the Bank of Canada's main monetary policy tool?",
      ["Setting the target for the overnight rate", "Changing personal income tax rates", "Setting limits on bank mortgage lending", "Buying shares of Canadian companies"],
      "The policy interest rate (target for the overnight rate) influences other rates, borrowing, spending and inflation.", "r"],
    ["What is the Bank of Canada's inflation target?",
      ["2%, the midpoint of a 1% to 3% range", "0%, to keep prices completely stable", "3%, the midpoint of a 2% to 4% range", "Whatever rate the government sets each year"],
      "The Bank aims to keep CPI inflation at 2%, the midpoint of a 1% to 3% control range, under an agreement with the federal government.", "r"],
    ["The Bank of Canada raises its policy rate. What is the most likely effect on the Canadian dollar?",
      ["It tends to rise, as Canadian yields attract investors", "It tends to fall, as investors move money elsewhere", "It's unaffected, since rates don't move currencies", "It becomes fixed against the US dollar"],
      "Higher Canadian rates make Canadian investments more attractive to foreign buyers, which increases demand for the dollar.", "r"],
    ["Which of the following is recorded in Canada's current account?",
      ["Exports and imports of goods and services", "Foreign purchases of Canadian government bonds", "Direct investment by Canadians abroad", "Changes in Canada's official reserves"],
      "The current account covers trade in goods and services, investment income and transfers. Purchases of financial assets are in the financial account.", "r"],
    ["The Canadian dollar rises sharply against the US dollar. Which group is most likely to be hurt?",
      ["Canadian exporters selling to the US", "Canadians travelling in the US", "Canadian firms importing US goods", "Canadians buying US-listed stocks"],
      "A stronger dollar makes Canadian goods more expensive for American buyers, which hurts exporters. Importers and travellers benefit.", "s"],
    ["How do investor expectations affect securities prices?",
      ["Prices reflect expected cash flows, so new expectations move them", "Prices depend only on a company's earnings over the past year", "Expectations affect bond prices but have no real effect on stock prices", "Prices only change on the days companies report their results"],
      "Securities are valued on expected future cash flows and the return investors require. When expectations change, prices adjust, often before the economic data does.", "r"],
    ["Which sector has typically held up best during recessions?",
      ["Consumer staples", "Information technology", "Consumer discretionary", "Industrials"],
      "Demand for necessities like food and household products is stable, so staples (with utilities and health care) are defensive. Cyclical sectors suffer more.", "r"],
    ["Late in an economic expansion, as inflation and commodity prices rise, which sectors have historically done relatively well?",
      ["Energy and materials", "Utilities and telecom", "Financials and real estate", "Staples and health care"],
      "Commodity producers benefit from rising prices late in the cycle. Rate-sensitive sectors tend to lag as rates rise.", "r"],
    ["Which system classifies companies into sectors and industries so analysts can compare peers?",
      ["The Global Industry Classification Standard (GICS)", "The Consumer Price Index (CPI) basket weightings by sector", "The Labour Force Survey from Statistics Canada", "SEDAR+"],
      "GICS groups companies into sectors, industry groups, industries and sub-industries. It's used by index providers and analysts.", "r"],
    ["Which publication sets out the Bank of Canada's economic outlook and inflation projections?",
      ["The Monetary Policy Report", "The federal budget", "The Labour Force Survey", "The CPI release"],
      "The Bank publishes its Monetary Policy Report four times a year, alongside some of its rate decisions.", "r"]
  ]);

  // ---------- Element 5: company analysis, disclosure, takeovers, market theories ----------
  add("fin", [
    ["Which financial statement shows a company's assets, liabilities and equity at a point in time?",
      ["Statement of financial position", "Statement of comprehensive income", "Statement of cash flows", "Statement of changes in equity"],
      "The statement of financial position (balance sheet) is a snapshot: assets = liabilities + equity.", "r"],
    ["A company raises money by issuing bonds. Where does this appear in its statement of cash flows?",
      ["Financing activities", "Operating activities", "Investing activities", "Comprehensive income"],
      "Issuing debt or shares, repaying debt and paying dividends are financing activities. Buying equipment is investing.", "r"],
    ["Why should an analyst read the notes to the financial statements?",
      ["They explain accounting policies and details like debt terms", "They contain the auditor's guarantee of future profits", "They replace the need to read the statements themselves", "They give the CEO's recommendations on the company's stock"],
      "The notes disclose accounting policies, debt terms, contingencies, commitments and other details that the statements alone don't show.", "r"],
    ["An auditor gives a qualified opinion on a company's financial statements. What does this indicate?",
      ["They're fairly presented except for a specific issue", "They're fully reliable, with no exceptions at all", "The auditor couldn't form any opinion on them", "They're materially misstated throughout"],
      "A qualified opinion flags a specific exception. An adverse opinion means the statements are materially misstated; a disclaimer means no opinion could be formed.", "r"],
    ["A non-venture reporting issuer must file its annual audited financial statements within how long of its year-end?",
      ["90 days", "45 days", "120 days", "Six months"],
      "Non-venture issuers have 90 days (venture issuers 120). Interim statements are due within 45 days (60 for venture issuers).", "r"],
    ["A listed company signs an agreement to sell its main business. What do the timely disclosure rules require?",
      ["A news release now and a material change report within 10 days", "Disclosure of the sale in the company's next annual report", "Keeping the deal confidential until the sale has formally closed", "Notice to the company's largest shareholders only"],
      "A material change requires an immediate news release and a material change report filed within 10 days.", "s"],
    ["A company has net income of $12 million and shareholders' equity of $80 million. What is its return on equity?",
      ["15%", "6.7%", "12%", "8%"],
      "ROE = net income ÷ equity = $12M ÷ $80M = 15%. ROE measures profitability relative to shareholders' investment.", "c"],
    ["A company has current assets of $45 million and current liabilities of $30 million. What is its current ratio, and what does it measure?",
      ["1.5 to 1, a measure of liquidity", "0.67 to 1, a measure of profitability", "1.5 to 1, a measure of profitability", "0.67 to 1, a measure of liquidity"],
      "Current ratio = current assets ÷ current liabilities = 1.5. It measures the ability to pay short-term obligations.", "c"],
    ["What does a rising debt-to-equity ratio most likely indicate?",
      ["More financial risk from leverage", "Better short-term liquidity", "Higher net profit margins on sales", "Lower interest costs on its debt"],
      "More debt relative to equity means higher fixed obligations and more risk if earnings fall.", "r"],
    ["A company's EBIT is $24 million and its interest expense is $6 million. What is its interest coverage ratio?",
      ["4 times", "0.25 times", "18 times", "30 times"],
      "Interest coverage = EBIT ÷ interest expense = $24M ÷ $6M = 4 times.", "c"],
    ["A stock trades at $42 and its earnings per share are $3.50. What is its P/E ratio?",
      ["12", "8.3", "14.7", "38.5"],
      "P/E = price ÷ EPS = $42 ÷ $3.50 = 12.", "c"],
    ["A company has net income of $10 million, pays $2 million in preferred dividends and has 4 million common shares outstanding. What is its EPS?",
      ["$2.00", "$2.50", "$3.00", "$0.50"],
      "EPS = (net income − preferred dividends) ÷ common shares = ($10M − $2M) ÷ 4M = $2.00.", "c"],
    ["A stock pays $1.80 a year in dividends and trades at $45. What is its dividend yield?",
      ["4.0%", "2.5%", "25%", "1.8%"],
      "Dividend yield = annual dividend ÷ price = $1.80 ÷ $45 = 4.0%.", "c"],
    ["A company's EPS is $4.00 and it pays dividends of $1.60 per share. What is its dividend payout ratio?",
      ["40%", "60%", "250%", "2.5%"],
      "Payout ratio = dividends per share ÷ EPS = $1.60 ÷ $4.00 = 40%.", "c"],
    ["A stock is expected to pay a $2.00 dividend next year, growing at 4% a year indefinitely. Investors require a 9% return. What is its value using the dividend discount model?",
      ["$40.00", "$22.22", "$50.00", "$41.60"],
      "Value = D1 ÷ (r − g) = $2.00 ÷ (0.09 − 0.04) = $40.00.", "c"],
    ["An analyst studies a company's earnings, management and industry to estimate what its shares are really worth. Which approach is this?",
      ["Fundamental analysis", "Technical analysis", "Quantitative analysis", "Sentiment analysis"],
      "Fundamental analysis estimates intrinsic value from the economy, the industry and the company's financial health and prospects.", "r"],
    ["Which approach is most characteristic of quantitative analysis?",
      ["Using statistical models with measures like beta", "Studying chart patterns such as head and shoulders", "Interviewing management about its business strategy", "Reading the auditor's report for any qualifications"],
      "Quantitative analysis uses mathematical and statistical tools (standard deviation, beta, correlation, factor models) to analyze securities.", "r"],
    ["A stock has a beta of 1.4. If the market rises 10%, what would you expect the stock to do?",
      ["Rise about 14%", "Rise about 4%", "Fall about 14%", "Rise about 10%"],
      "Beta measures sensitivity to market moves: 1.4 × 10% = 14%.", "c"],
    ["A stock has repeatedly stopped falling at about $30 and then rebounded. What would a technical analyst call the $30 level?",
      ["Support", "Resistance", "A moving average", "Intrinsic value"],
      "Support is a price level where buying tends to stop declines. Resistance is a level where selling tends to stop advances.", "r"],
    ["A stock's relative strength index (RSI) is 82. How would a technical analyst most likely read this?",
      ["Overbought, so a pullback is possible", "Oversold, so a rebound is possible", "Fairly valued based on its earnings", "Stuck in a stable, trendless market"],
      "RSI above 70 is usually read as overbought and below 30 as oversold.", "r"],
    ["A stock's 50-day moving average crosses above its 200-day moving average. How do technical analysts usually read this?",
      ["As a bullish signal", "As a bearish signal", "As a sign of falling volume", "As irrelevant to the trend"],
      "A short-term average crossing above a long-term one (a 'golden cross') suggests an uptrend is building.", "r"],
    ["Which tool do technical analysts use to measure market breadth?",
      ["The advance-decline line", "The price-to-earnings ratio", "The current ratio", "The dividend payout ratio"],
      "Breadth indicators like the advance-decline line show how many stocks are taking part in a market move.", "r"],
    ["Under Canadian take-over bid rules, an offer becomes a formal take-over bid when it would bring the buyer's holdings to at least what percentage of a class of voting or equity securities?",
      ["20%", "10%", "50%", "66⅔%"],
      "An offer that would take the buyer to 20% or more of a class is a take-over bid. It must be made to all holders on equal terms, with a circular.", "r"],
    ["How long must a formal take-over bid generally stay open, unless the target's board agrees to a shorter period?",
      ["105 days", "35 days", "10 days", "180 days"],
      "The minimum deposit period is 105 days. The target's board can shorten it to as little as 35 days.", "r"],
    ["An investor's holdings of a listed company's voting shares reach 10%. What is required?",
      ["Early warning disclosure", "A formal take-over bid", "Shareholder approval", "Nothing until 20%"],
      "At 10%, the early warning system requires a news release and a report, which gives the market notice that a large position is building.", "s"],
    ["A company buys back its own shares under a normal course issuer bid. What is an issuer bid?",
      ["An offer by a company to buy back its own securities", "An offer by an insider to buy all of the company's shares", "An offer of new shares to the company's existing holders", "A bid by a dealer to underwrite a new share issue"],
      "An issuer bid is an issuer's offer to acquire its own securities. Normal course issuer bids on an exchange are exempt from the formal bid rules within limits.", "r"],
    ["Why do insider bids generally require an independent valuation?",
      ["Insiders may know more than other shareholders", "Insiders can't own more than 10% of the shares", "Insider bids are exempt from disclosure rules", "The valuation sets the dividend after the bid"],
      "Insiders may have an information advantage. An independent valuation, overseen by independent directors, protects minority shareholders.", "r"],
    ["What is a key purpose of take-over bid rules?",
      ["Equal treatment of holders, with enough time and information to decide", "Stopping every hostile bid before it reaches the target's shareholders", "Guaranteeing shareholders a premium of at least 20% on their shares", "Letting bidders buy from large holders at privately negotiated prices"],
      "The rules aim to treat all shareholders of the class equally and give them adequate time and information to decide.", "r"],
    ["A client bought shares in an IPO and later learns the prospectus contained a misrepresentation. What right may she have?",
      ["Rescission or damages", "A refund from CIPF", "Automatic compensation from the exchange", "A right to convert her shares to bonds"],
      "Securities law gives purchasers a statutory right of action for rescission or damages when a prospectus contains a misrepresentation.", "s"],
    ["Within what time can a buyer of a new issue withdraw from the purchase after receiving the final prospectus?",
      ["Two business days", "Ten business days", "30 days", "90 days"],
      "The right of withdrawal lets a purchaser cancel within two business days of receiving the prospectus.", "r"],
    ["Which of the following is a right of common shareholders?",
      ["Voting to elect the board of directors", "Receiving a fixed dividend every year", "Being repaid before creditors on wind-up", "Redeeming their shares at book value"],
      "Common shareholders vote on major matters, including electing directors. Dividends aren't guaranteed, and they rank last on liquidation.", "r"],
    ["Within what time must a newly appointed director of a listed company file an initial insider report?",
      ["10 days", "5 business days", "30 days", "Only when they trade"],
      "An initial report is due within 10 days of becoming an insider; later trades must be reported within 5 days.", "r"],
    ["Where can investors find a Canadian public company's financial statements and other filings?",
      ["SEDAR+", "SEDI", "FINTRAC's website", "The Bank of Canada's website"],
      "SEDAR+ is the CSA's filing system for issuer documents. SEDI holds insider trading reports.", "r"]
  ]);

  // ---------- Element 6: UMIR, gatekeeping and market integrity ----------
  add("umir", [
    ["Under UMIR, what does best execution require?",
      ["Diligently seeking the most advantageous terms for the client", "Always taking the single best displayed price, whatever it costs", "Executing every client order immediately at the market price", "Routing every client order to the Toronto Stock Exchange"],
      "Best execution weighs price, speed, certainty of execution and the overall cost of the transaction.", "r"],
    ["A dealer receives a large client order in a thinly traded stock. Which approach best reflects best execution?",
      ["Working the order to balance price, speed and market impact", "Entering it all at once as a market order to get it done", "Holding it until the next day without telling the client", "Filling it from the dealer's own inventory at a price the dealer chooses"],
      "For large or illiquid orders, best execution may mean working the order over time to limit market impact while staying within the client's instructions.", "s"],
    ["A Participant has a client order and a principal order at the same price. Under UMIR, which must be entered first?",
      ["The client order", "The principal order", "Whichever is larger", "Whichever arrived last"],
      "Client priority: a Participant must give a client order priority over its own principal or non-client orders at the same price.", "r"],
    ["A trader learns a pension fund client is about to sell a large block of XYZ, and buys put options on XYZ for his own account first. What is this?",
      ["Front running", "Arbitrage", "Hedging", "Market making"],
      "Front running is trading ahead of a client order using knowledge of it that isn't public. It covers related securities such as options.", "s"],
    ["A client buys and sells the same stock between two accounts she controls to make the stock look actively traded. What is this?",
      ["A wash trade", "A cross trade", "A short sale", "A basket trade"],
      "A wash trade involves no change in beneficial ownership. It creates a false appearance of trading activity and is manipulative.", "s"],
    ["A trader enters large buy orders he doesn't intend to fill, sells into the price rise, then cancels the buy orders. What is this?",
      ["Spoofing", "Iceberg ordering", "Market making", "Best execution"],
      "Spoofing (or layering) uses orders that aren't meant to execute to mislead others about supply and demand.", "s"],
    ["A portfolio manager places small buy orders at rising prices in the last minutes of trading on the last day of the quarter. What is the concern?",
      ["Marking the close to inflate the portfolio's value", "Front running the manager's own client orders", "Short selling the stock without first arranging to borrow it", "Failing to give clients price improvement"],
      "Orders meant to set an artificial closing price ('high closing') are manipulative, especially when they inflate a portfolio's reported value.", "s"],
    ["Under UMIR's gatekeeper provisions, when must a Participant report to CIRO?",
      ["When it has reasonable grounds to suspect a violation", "Only after a court has convicted the trader involved in it", "Only when a client files a written complaint", "Whenever a client's order ends up losing money"],
      "Gatekeeping requires reporting manipulative and deceptive activity, front running, insider trading and other violations when the Participant knows of, or has reasonable grounds to suspect, them.", "r"],
    ["A trader receives a client order that would clearly create an artificial closing price. What should the trader do?",
      ["Question or refuse it and escalate it", "Enter it; the client is responsible", "Enter it but fill only part of it", "Hold it until the next trading day"],
      "Under gatekeeping, Participants must not enter orders they know or ought to know are manipulative, and must escalate concerns to compliance.", "s"],
    ["A client who works at a drug company buys short-dated calls on her employer the day before a regulatory approval is announced. What should her advisor do?",
      ["Report it internally as possible insider trading", "Congratulate her on the trade and take no further action", "Buy the same calls for his other clients", "Warn her to sell before the news is public"],
      "Unusual trading by an insider ahead of material news is a red flag. The advisor must escalate it to compliance, which decides whether to report it.", "s"],
    ["An employee reports possible securities law breaches to a regulator's whistleblower program. What protection exists?",
      ["Employers can't retaliate against the whistleblower", "The employee must first wait 90 days for the firm to act", "The employee gives up any right to a financial award", "The firm must publicly name the whistleblower"],
      "Programs such as the OSC's protect whistleblowers' identity, prohibit reprisals and may pay financial awards. Employees don't have to report inside the firm first.", "r"],
    ["A firm's employment contracts forbid employees from reporting misconduct to regulators. What is the problem?",
      ["Contracts can't stop employees from reporting to regulators", "Nothing; firms may control all disclosure made by their employees", "Only CIRO is allowed to approve such clauses", "Such clauses can only bind the firm's senior officers"],
      "Whistleblower protections make provisions that prevent or discourage reporting to regulators unenforceable.", "r"],
    ["A Participant gives an institutional client direct electronic access (DEA). Who remains responsible for the client's orders complying with UMIR?",
      ["The Participant providing the access", "Only the DEA client", "The marketplace where the orders trade", "CIRO's market surveillance team"],
      "The Participant stays responsible for orders entered under its identifier, so it must set standards for DEA clients and supervise their trading.", "r"],
    ["Which control must a Participant have before providing direct electronic access?",
      ["Pre-trade controls such as credit and order limits", "A complete ban on algorithmic orders", "A rule that all DEA trades must settle on the same day", "Approval from the client's auditor"],
      "Participants must have risk management and supervisory controls, including automated pre-trade limits, to prevent erroneous or manipulative orders.", "r"],
    ["A dealer's trading algorithm malfunctions and sends a flood of erroneous orders. Which statement is correct?",
      ["The dealer is responsible and must have controls to prevent and stop it", "The marketplace bears full responsibility for any orders it accepts", "Algorithmic orders aren't subject to UMIR, so no rule is breached", "The dealer can cancel any resulting trades on its own authority"],
      "Algorithmic orders are treated like any other orders. The dealer must test its algorithms and have controls to prevent and halt malfunctions.", "s"],
    ["What concern arises when a dealer trades as principal against a client's order?",
      ["A conflict between the dealer's profit and the client's price", "The client's account loses CIPF protection for that particular trade", "The trade can't settle through CDS", "The client must also pay the counterparty's commission"],
      "When the dealer is the counterparty, it gains from a worse price for the client. UMIR has specific rules for client-principal trades.", "r"],
    ["How must a short sale order be entered under UMIR?",
      ["Marked as a short sale", "Only as a market order", "Only at the opening", "After notifying the CSA"],
      "Short sales must be marked as such. This lets regulators monitor short selling.", "r"],
    ["How often do dealers report their total short positions in each security to CIRO?",
      ["Twice a month", "Every trading day", "Once a year", "Only when closed"],
      "Short position reports are made twice monthly, and CIRO publishes the aggregate data.", "r"],
    ["The order protection rule requires marketplaces to have policies that prevent what?",
      ["Trade-throughs of better-priced visible orders", "Short sales in a security during falling markets", "Clients from using limit orders", "Any trading in listed securities after 4:00 p.m."],
      "A trade-through happens when an order executes at a worse price than a visible order on another protected marketplace.", "r"],
    ["What is the main function of a dealer's equity research department?",
      ["Analyzing securities and publishing opinions for investors", "Matching client buy and sell orders on the exchange each day", "Approving new client accounts at the branches", "Underwriting new share issues for corporate clients"],
      "Research analysts study companies and industries and publish reports and ratings. Information barriers separate them from investment banking.", "r"],
    ["What is the main function of investment banking?",
      ["Helping issuers raise capital and advising on transactions", "Taking deposits from the public and making loans to consumers", "Executing retail clients' online trades", "Monitoring trading activity on marketplaces for manipulation"],
      "Investment banking (corporate finance) underwrites new issues and advises on mergers, acquisitions and restructurings.", "r"]
  ]);

  // ---------- Element 6: orders, accounts, margin, confirmations and settlement ----------
  add("trade", [
    ["A trader enters an immediate-or-cancel (IOC) order to buy 5,000 shares, but only 3,000 are available at the limit price. What happens?",
      ["3,000 fill and the other 2,000 are cancelled", "Nothing fills, since 5,000 aren't available", "3,000 fill and 2,000 stay open until filled", "All 5,000 fill at the next available price"],
      "An IOC order fills whatever it can immediately and cancels the rest.", "s"],
    ["How does a fill-or-kill (FOK) order differ from an immediate-or-cancel (IOC) order?",
      ["FOK must fill in full at once or be cancelled; IOC allows partial fills", "IOC must fill in full at once or be cancelled; FOK allows partial fills", "FOK stays open until it fills completely; IOC expires at the close", "FOK becomes a market order once the stop price is reached"],
      "Both are immediate. FOK is all or nothing; IOC accepts a partial fill.", "r"],
    ["An institutional trader wants to sell 200,000 shares without showing the full size to the market. Which order type helps?",
      ["An iceberg order", "A fill-or-kill order", "A market order", "An on-stop order"],
      "An iceberg order shows only part of its size; the hidden balance is revealed as the visible part fills.", "s"],
    ["A client owns shares trading at $40 and wants to limit her loss if the price falls to $35. Which order fits?",
      ["A sell on-stop order with a $35 trigger", "A sell limit order at $35", "A buy on-stop order with a $35 trigger price", "A fill-or-kill order to sell at $40 or better"],
      "A sell stop (on-stop) order becomes active only if the price falls to the trigger. A sell limit at $35 would fill right away at $40, since $40 is above the limit.", "s"],
    ["What is the main risk of a stop-limit order compared with a stop-loss order?",
      ["It may not fill if the price gaps past the limit", "It always fills at a worse price than expected", "It can't be used to sell shares a client owns", "It can fill before the stop price is reached"],
      "Once triggered, a stop-limit order becomes a limit order, so it may not fill in a fast market. A stop-loss becomes a market order and will fill, but at an uncertain price.", "r"],
    ["What is the main feature of a market order?",
      ["It fills quickly, but the price isn't guaranteed", "It fills only at a set price or better", "It shows only part of the order's size", "It stays open until the client chooses to cancel it"],
      "A market order trades at the best available prices right away. The client gets speed and certainty of execution, not a guaranteed price.", "r"],
    ["If a client doesn't say how long an order should stay open, how is it usually treated?",
      ["As a day order", "As good-till-cancelled", "As fill-or-kill", "As open for 30 days"],
      "Unless otherwise specified, orders are day orders and expire at the end of the trading day.", "r"],
    ["A client enters a limit order to sell 500 shares at $25.50 while the stock trades at $25.10. What will happen?",
      ["It fills only if the price reaches $25.50 or more", "It fills at once at the current market price of $25.10", "It fills at once, at a price of $25.50", "It becomes a market order at the close"],
      "A sell limit sets the minimum acceptable price. The order waits until a buyer will pay $25.50 or more.", "s"],
    ["A client calls to change the limit price on an order that hasn't filled yet. What should the representative do?",
      ["Confirm it's unfilled, then enter the change", "Tell her orders can't be changed once entered", "Enter a second order and leave the first open", "Wait until the end of the day to change it"],
      "Unfilled orders can be changed or cancelled. Confirming first prevents a double fill.", "s"],
    ["A client asks to cancel an order that has already been executed. Which statement is correct?",
      ["It can't simply be cancelled; she'd need an offsetting trade", "The representative can cancel it, as long as the client consents in writing", "The exchange cancels it automatically when the client asks", "Any trade can be cancelled at any time before it settles"],
      "Executed trades are binding. They can be varied or cancelled only in limited cases (such as clear errors) through the marketplace with the Market Regulator's involvement.", "s"],
    ["A trade executes at a clearly erroneous price because of a system error. How can it be corrected?",
      ["Through the marketplace, with CIRO's consent as Market Regulator", "By the two traders privately agreeing on a new and fairer price", "By the dealer changing the price in its own trade records afterward", "It can't be corrected, since every trade is final"],
      "Under UMIR, a marketplace trade may be varied or cancelled only with the consent or at the direction of the Market Regulator, which is CIRO.", "s"],
    ["What must a trade confirmation for an equity trade show?",
      ["Charges paid, and whether the dealer acted as principal or agent", "The client's net worth and risk tolerance as shown on the KYC form", "The representative's personal holdings in the same stock", "The representative's own target price for the stock over the next 12 months"],
      "Confirmations show the security, quantity, price, commission and other charges, settlement date, whether the dealer acted as principal or agent, and the representative.", "r"],
    ["By when must a dealer send a client the confirmation for a trade?",
      ["Promptly, usually by the next business day", "With the client's next quarterly statement", "Within 30 days of the trade date", "Only if the client asks for one"],
      "Confirmations must be sent promptly after the trade so the client can catch any error quickly.", "r"],
    ["A client buys a corporate bond from the dealer's inventory. What must the confirmation disclose?",
      ["The yield and the dealer's total compensation", "The bond's credit rating history for ten years", "The client's marginal tax rate on the interest", "The names of other clients who bought the bond"],
      "Debt confirmations must show the yield and the dealer's total compensation (markup or commission) on the trade.", "r"],
    ["A client buys shares on a Tuesday. When does the trade normally settle?",
      ["Wednesday (T+1)", "Tuesday (T+0)", "Thursday (T+2)", "Friday (T+3)"],
      "Since May 2024, Canadian equities and most bonds settle one business day after the trade.", "r"],
    ["When do trades in Government of Canada treasury bills normally settle?",
      ["The same day", "One day later", "Two days later", "Five days later"],
      "Money market instruments such as T-bills normally settle on the trade date.", "r"],
    ["A stock's dividend record date is Friday. With T+1 settlement, what is the last day to buy the stock and receive the dividend?",
      ["Thursday", "Friday", "Wednesday", "The following Monday"],
      "Under T+1, the ex-dividend date is the record date (Friday). A buyer must buy before it, on Thursday, to settle in time to be on the record.", "c"],
    ["Which part of a dealer typically handles trade settlement and the delivery of securities and cash?",
      ["The back office", "The front office", "The research team", "The underwriting desk"],
      "The back office (operations) handles settlement, custody, record-keeping and client statements.", "r"],
    ["Which best describes the role of a dealer's middle office?",
      ["Risk management and compliance oversight", "Selling securities to the dealer's clients", "Settling trades and holding client assets", "Underwriting new securities for issuers"],
      "The middle office monitors the front office through risk management, compliance and controls. The back office settles trades.", "r"],
    ["What is the main role of an institutional sales trader?",
      ["Executing large institutional orders while limiting market impact", "Opening new retail accounts for walk-in clients at the branch", "Writing research reports on companies in a given industry", "Approving new products before they are offered to clients"],
      "Sales traders work institutional orders, finding liquidity and managing price impact on behalf of clients.", "r"],
    ["A pension fund wants to buy a basket of 60 stocks at once to match an index. Which desk would most likely handle the order?",
      ["The program (portfolio) trading desk", "The fixed income and money market desk", "The retail order desk", "The prime brokerage desk"],
      "Program trading desks execute baskets of securities at the same time, often for index-related or rebalancing trades.", "s"],
    ["In which type of account must the client pay in full by the settlement date?",
      ["A cash account", "A margin account", "A short account", "A futures account"],
      "In a cash account the client pays the full purchase price by settlement. A margin account lets the client borrow part of it.", "r"],
    ["A client buys 1,000 shares at $30 in a margin account where the margin requirement is 50%. How much must she deposit?",
      ["$15,000", "$30,000", "$10,000", "$7,500"],
      "Margin required = 50% × $30,000 = $15,000. The dealer lends the other $15,000.", "c"],
    ["A client's margin account falls below the required margin. What happens?",
      ["A margin call, and positions may be sold if not met", "Nothing happens until the next settlement date arrives", "The dealer forgives the shortfall on the loan", "CIPF covers the shortfall for the client"],
      "The client must deposit cash or securities. If she doesn't, the dealer can sell positions to restore the margin.", "r"],
    ["A client sells short 500 shares at $40. The short margin requirement is 150% of market value. How much must she deposit beyond the $20,000 of sale proceeds?",
      ["$10,000", "$20,000", "$30,000", "$5,000"],
      "Total required = 150% × $20,000 = $30,000. The proceeds supply $20,000, so she deposits $10,000.", "c"],
    ["What is the main risk of a short position?",
      ["Unlimited loss if the price keeps rising", "A loss limited to the sale proceeds", "No risk, because the shares are borrowed", "The loss of the dividend tax credit"],
      "There's no ceiling on how high a price can rise, so a short seller's potential loss is unlimited.", "r"],
    ["Why do margin requirements exist?",
      ["To protect against losses on borrowed positions", "To limit how many shares of one company a client may own", "To set the commission on margin trades", "To ensure trades settle on time"],
      "Margin requirements make sure there's enough equity to cover losses on borrowed or short positions, which protects the client, the dealer and the market.", "r"],
    ["Before a client can trade futures, what must the dealer have besides the usual account documents?",
      ["A specialized derivatives trading agreement", "A letter from CIRO approving the client", "Proof the client has traded futures before", "A guarantee from the client's bank"],
      "Derivatives accounts need specific documents, including a derivatives trading agreement and risk disclosure, approved by a qualified supervisor.", "r"],
    ["A dealer's capital falls below CIRO's early warning level. What must it do?",
      ["Notify CIRO, which may impose restrictions", "Nothing until its annual audit is done", "Notify each client within 30 days", "Halt all client trading at once"],
      "The early warning system makes a dealer whose capital is weakening report to CIRO. It then faces restrictions, such as limits on paying dividends or reducing capital.", "r"]
  ]);
})();
