// Exam-level questions, set 3: market integrity, trade execution & settlement (E6) and derivatives (E8).
// The CIRE syllabus tests derivatives at the "remember" level, so those questions are shorter.
window.QB_HARD = window.QB_HARD || {};
(function () {
  const add = (k, list) => { window.QB_HARD[k] = (window.QB_HARD[k] || []).concat(list); };

  add("umir", [
    ["For three straight days, Victor has phoned in small buy orders for a thinly traded stock in the last two minutes of trading. Each order is priced slightly above the last trade. He holds a large position and says he 'likes to see the stock close strong' before his month-end statement. What should his advisor do?",
      ["Recognize possible manipulation of the closing price and escalate to compliance first",
       "Enter the orders, since Victor is buying with his own money and taking his own risk",
       "Enter the orders, but split them across several marketplaces to reduce their impact",
       "Suggest he place the orders at the open instead, and enter them there without comment"],
      "Repeatedly trading at the close to lift the closing price is 'high closing,' a manipulative practice. Advisors act as gatekeepers and must escalate.", "s"],
    ["A new client receives 2 million shares of a thinly traded company, transferred from an unrelated third party he says is a 'business contact.' Within days, a promotional newsletter about the company circulates online, the price triples, and he asks to sell all of the shares at once. What is the best course of action?",
      ["Treat it as a possible pump-and-dump, ask where the shares came from, and escalate",
       "Sell the shares quickly, before the promotion ends and the price starts to fall",
       "Sell the shares, since the client legally owns them and has asked for the sale",
       "Sell half of the shares now and the rest next week to reduce the market impact"],
      "Shares deposited from unrelated parties and sold into promotional activity are red flags for manipulation and possibly illegal distributions.", "s"],
    ["Tomas's wife is the CFO of a TSX-listed company. Two days before the company announces unexpectedly strong earnings, Tomas buys a large position in its short-dated call options, his first-ever options trade. After the announcement, the options rise 400%. What should his advisor do?",
      ["Report the trading to compliance as possible insider trading",
       "Nothing, since Tomas placed the trade rather than his wife",
       "Nothing, since options aren't covered by insider trading rules",
       "Ask Tomas to sell right away so that it doesn't look suspicious"],
      "Trading on material non-public information obtained from someone in a special relationship is illegal. Gatekeeping requires escalation.", "s"],
    ["A dealer gives an institutional client direct electronic access (DEA), so the client's own trading system sends orders straight to a marketplace under the dealer's identifier. The dealer's staff don't see the orders before they reach the market. Who is responsible for those orders complying with UMIR?",
      ["The dealer remains responsible, with risk controls and a written agreement",
         "The client alone, once it has been given direct electronic access",
         "The marketplace, which is responsible for every order it receives",
         "No one, because DEA orders aren't subject to UMIR"],
      "A participant that provides DEA stays responsible for orders entered under its identifier, and must set standards, controls and supervision.", "s"],
    ["A small dealer isn't a participant on any marketplace. To execute its clients' orders, it sends them through a larger participant dealer under a routing arrangement. How are these orders typically identified, and who is accountable for them under UMIR?",
      ["As jitney orders, with the participant still responsible for compliance",
       "As principal orders of the participant, which owns them until they're filled",
       "As non-client orders, since they come from another dealer's employees",
       "As short-marking-exempt orders, since they come from a registered dealer"],
      "Orders entered for another dealer are 'jitney' orders. The participant handling them remains accountable under UMIR.", "s"],
    ["A pension fund asks its dealer to buy 2 million shares of a mid-cap stock that trades about 300,000 shares a day. Instead of buying at the best displayed offer immediately, the dealer's trader works the order over several days. Is this consistent with best execution?",
      ["Yes; best execution weighs price, speed, certainty and total cost, including market impact",
       "No; best execution always requires taking the best displayed price as soon as possible",
       "No; large client orders must always be completed within the same trading day",
       "Yes, but only if the pension fund agrees to pay a lower commission on the order"],
      "For large orders, limiting market impact and total cost can matter more than the price displayed at one moment.", "s"],
    ["A client places an order to buy 1,000 shares of a stock that the dealer happens to hold in its own inventory. The dealer fills the client's order from its inventory instead of buying on the market. Which requirement applies?",
      ["The price must be fair, and the confirmation must show it acted as principal",
         "The dealer must charge exactly the stock's closing price on the trade date",
         "The dealer may charge any price it chooses, since it owns the shares",
         "CIRO must approve the trade before it can settle on the following day"],
      "Principal trades must be fairly priced, and the dealer's capacity must be disclosed to the client.", "s"],
    ["A stock's best ask is $20.05 and its best bid is $20.00. A client who wants to be sure of getting the stock enters a buy limit order at $20.50. What will most likely happen?",
      ["It will fill right away at about $20.05", "It will fill only once the price rises to $20.50", "It will be rejected for being above the market", "It will be converted into a stop order at $20.50"],
      "A buy limit above the current ask is immediately executable; it fills at the best available price, up to the limit.", "s"],
    ["A dealer arranges a block trade, crossing 100,000 shares between two unrelated institutional clients. One wants to sell, the other wants to buy, and the trade is done at the current market price. Which statement is correct?",
      ["It's a legitimate cross, since ownership really changes between independent parties",
         "It's a wash trade, because the same dealer is acting on both sides of the transaction",
         "It's prohibited unless the cross is executed through a dark pool",
         "It's manipulative, because the volume is unusually large for the stock"],
      "Wash trades involve no change in beneficial ownership. A genuine cross between unrelated clients at a fair price is normal.", "s"],
    ["Two traders each cancel dozens of orders in the same stock on the same day. Regulators are deciding whether either was spoofing. What most clearly distinguishes spoofing from legitimate cancellations?",
      ["Whether the trader intended to execute the orders when entering them",
         "How many orders the trader cancelled over the course of that trading day",
         "Whether the orders were entered on an exchange or on an ATS",
         "Whether each order was for more than one board lot of shares"],
      "Spoofing is entering orders with no intention of executing them, to mislead others. Cancelling because conditions changed is legitimate.", "s"],
    ["Kelly, an advisor, buys a small-cap stock for her own account. Over the next two weeks, she recommends it enthusiastically to dozens of clients. As their buying pushes the price up 35%, she quietly sells her own shares. What is this practice called?",
      ["Scalping", "Churning", "Front running", "Spoofing"],
      "Scalping is recommending a security in order to profit from the price move by selling into the demand you create.", "s"],
    ["A client places an order to buy 300 shares of a large, liquid TSX stock at the market. She gives no special instructions. The advisor considers holding the order until another client wants to sell, so the trade can be crossed internally. Under UMIR, what should generally happen?",
      ["The order should be entered on a marketplace promptly",
       "The order should be held until a matching client can be found",
       "The order should be filled from inventory at the day's close",
       "The order should go to a dark pool first, then to an exchange"],
      "Small client orders must generally be exposed on a marketplace immediately, unless the client instructs otherwise or another exception applies.", "s"],
    ["A client buys shares of a TSX-listed company on a Friday. The following Monday is a regular business day. When does the trade settle, and how is it usually completed?",
      ["Monday, by book entry through CDS", "Wednesday, by delivering share certificates", "Friday, by paying cash to the exchange", "Tuesday, through the Bank of Canada"],
      "Canadian equities settle T+1, mostly by book entry through CDS, the clearing and depository system.", "s"],
    ["A seller fails to deliver shares by the settlement date. The buying dealer initiates a buy-in and has to pay more than the original price to get the shares. Who bears the extra cost?",
      ["The seller that failed to deliver", "The buying client who placed the order", "CDS, as the clearing house", "CIPF, as the investor protection fund"],
      "Buy-ins protect the buyer. The defaulting side pays any additional cost.", "s"],
    ["Which account would most likely be allowed to mark its short sale orders as 'short-marking exempt'?",
      ["A market maker or arbitrage account that meets the UMIR conditions", "Any retail client's margin account that is held at the dealer", "A client's TFSA, because it's a registered account", "Any client account holding more than $1 million of assets"],
      "Certain accounts, such as market makers and arbitrage accounts, can mark orders short-marking exempt; regular short sales must be marked 'short.'"],
    ["A research analyst at a dealer is about to publish an upgrade on a stock. A trader at the same firm hears about it before it's released and buys the stock for the firm's own account, planning to sell after the report comes out. What is the main problem?",
      ["Trading on advance, non-public knowledge of the firm's research",
       "Nothing, because the trade was for the firm and not the trader personally",
       "The trader should have bought the stock for clients' accounts first",
       "The upgraded research should have been filed with CIRO before release"],
      "Using advance knowledge of research or client orders unfairly is prohibited. Firms use information barriers and trading restrictions to prevent it.", "s"],
    ["A dealer's surveillance system flags a client's pattern of orders that, if executed, would create a misleading appearance of active trading in a small stock. The dealer refuses to enter the orders. What else may it have to do?",
      ["Report the activity to CIRO", "Report the client to OBSI", "File a Large Cash Transaction Report", "Nothing more, once the orders are refused"],
      "Under UMIR gatekeeping obligations, participants must report suspected manipulative or deceptive activity.", "s"],
    ["A client holds 15% of a listed company's voting shares and asks his advisor to sell part of the position. How must the advisor enter the order?",
      ["With the significant shareholder designation", "With no special marking, as for any client", "As a jitney order through another dealer", "As a short-marking-exempt order"],
      "UMIR requires specific markers so regulators can monitor trading by insiders and significant shareholders.", "s"]
  ]);

  add("trade", [
    ["Gloria has a stop-limit sell order on a stock now trading at $50: stop $45, limit $44. Overnight, the company announces a major lawsuit. The stock opens at $40 the next morning and keeps falling through the day. What is the most likely outcome?",
      ["The order is triggered but won't fill unless the price recovers to $44",
         "The order fills at $45, since that's the stop price she chose",
         "The order fills at about $40, since it becomes a market order",
         "The order is cancelled automatically at the open"],
      "A stop-limit becomes a limit order when triggered, which guarantees the price but not execution.", "s"],
    ["A client bought 2,000 shares at $25 in a margin account, depositing 50% of the cost ($25,000) and borrowing the rest. The stock falls to $20. If the margin requirement is still 50%, what is the margin deficiency?",
      ["$5,000", "$10,000", "$20,000", "$2,500"],
      "Loan = $25,000. Maximum loan at $20 = 50% × $40,000 = $20,000. Deficiency = $25,000 − $20,000 = $5,000.", "c"],
    ["A client places a market order to buy shares of a TSX-listed company at 3:50 p.m. on Wednesday, December 30. Thursday, December 31, is a business day. When does the trade settle?",
      ["Thursday, December 31", "Friday, January 1", "Wednesday, December 30", "Monday, January 4"],
      "T+1 settlement means the next business day.", "c"],
    ["Darren shorted 1,000 shares at $40. The stock has risen to $55 on takeover rumours, and he's worried it could keep climbing. He's travelling and won't be able to watch the market. Which order best limits his losses if the stock keeps rising?",
      ["A buy stop order placed above the current price", "A sell stop order placed below the current price", "A sell limit order placed above the current price", "A buy limit order placed below the current price"],
      "A buy stop closes the short position if the price rises to the stop level.", "s"],
    ["A client is considering using margin for the first time. Which statement about margin trading should her advisor confirm?",
      ["The dealer can sell her securities to meet a margin call without her consent",
         "Margin loans are interest-free, as long as they're repaid within one year",
         "She can lose at most the cash deposit that she put into the account",
         "Margin can be used in her RRSP, provided that she signs a waiver"],
      "Margin magnifies losses beyond the initial deposit, and the margin agreement lets the dealer liquidate positions."],
    ["A portfolio manager needs to buy 20,000 shares right now. If the full amount can't be bought immediately, she doesn't want any of it. Which order type fits?",
      ["Fill or kill", "All or none", "Good-till-cancelled", "Market-on-close"],
      "Fill or kill requires immediate execution of the full quantity. All or none requires the full quantity but not immediacy.", "s"]
  ]);

  add("deriv", [
    ["Which statement correctly describes the rights and obligations in a call option?",
      ["The buyer has the right to buy; the writer must sell if assigned",
       "The buyer must buy; the writer has the right to sell if it chooses",
       "Both the buyer and the writer are obligated to complete the trade",
       "The buyer has the right to sell; the writer must buy if assigned"],
      "Option buyers have rights; writers have obligations if assigned. A call conveys the right to buy."],
    ["How do forward contracts differ from futures contracts?",
      ["Forwards are customized and OTC; futures are standardized, exchange-traded and marked to market",
       "Forwards are standardized and exchange-traded; futures are customized private agreements",
       "Forwards give the buyer a right but no obligation; futures obligate both of the parties",
       "Forwards can only be used for currencies; futures can only be used for physical commodities"],
      "The key differences are customization, trading venue, clearing and daily settlement. Both obligate both parties."],
    ["In a plain-vanilla interest rate swap, what is typically exchanged?",
      ["Fixed-rate interest payments for floating-rate payments on a notional amount",
       "The full notional principal, at the start and again at the end of the swap",
       "A bond issued by one party for common shares issued by the other party",
       "An option premium in exchange for the right to borrow at a fixed rate"],
      "Swap parties exchange interest payments only; the notional principal isn't exchanged."],
    ["A stock trades at $42. Which of these options is in-the-money?",
      ["A put with a $45 strike", "A call with a $45 strike", "A put with a $40 strike", "A call with a $42.50 strike"],
      "A put is in-the-money when the stock is below the strike; a call when the stock is above the strike.", "c"],
    ["Which of these option positions has the greatest potential loss?",
      ["Writing an uncovered (naked) call", "Buying a put option outright", "Buying a call option", "Writing a covered call on shares owned"],
      "A naked call writer must deliver shares at the strike however high the price goes, so the potential loss is theoretically unlimited."],
    ["An investor holds a European-style option. When can it be exercised?",
      ["Only at expiration", "At any time up to expiration", "Only within 30 days of purchase", "Only if it's out-of-the-money"],
      "European-style options are exercisable only at expiry; American-style options at any time up to expiry."],
    ["A Canadian manufacturer has ordered equipment from a U.S. supplier and must pay US$5 million in six months. Its CFO fears the U.S. dollar will rise before then. Which use of derivatives is a hedge?",
      ["Buying U.S. dollars forward for delivery in six months",
       "Selling U.S. dollars forward for delivery in six months",
       "Buying call options on the manufacturer's own shares",
       "Writing put options on a broad U.S. stock index"],
      "Locking in the purchase price of the currency it needs offsets the risk of a rising U.S. dollar.", "s"],
    ["Which statement about warrants, compared with exchange-traded call options, is correct?",
      ["Warrants are issued by the company and create new shares when exercised",
       "Warrants are created by investors trading with each other on an exchange",
       "Both warrants and listed options create new shares when they're exercised",
       "Neither warrants nor listed options give the holder a right to buy shares"],
      "Warrants are a corporate financing tool, so exercising them dilutes existing holders. Listed options are contracts between investors."],
    ["An investor wants to profit if a stock rises, while risking only a small, known amount. Which strategy fits best?",
      ["Buy a call option", "Write a put option", "Sell the stock short", "Write a call option"],
      "Buying a call gives upside exposure with a maximum loss equal to the premium paid."],
    ["In a futures contract on crude oil, which party is obligated to perform?",
      ["Both the buyer and the seller", "Only the seller of the contract", "Only the buyer of the contract", "Neither, until one party exercises"],
      "Futures obligate both parties, unlike options."]
  ]);
})();
