// Exam-level questions, set 2: KYC & suitability (E3) and market & company analysis (E5).
window.QB_HARD = window.QB_HARD || {};
(function () {
  const add = (k, list) => { window.QB_HARD[k] = (window.QB_HARD[k] || []).concat(list); };

  add("kyc", [
    ["Paolo, 61, opens an account with $600,000. On the KYC form he chooses 'aggressive growth' as his objective and 'high' risk tolerance. Later in the meeting, he mentions he'll retire in two years and will rely on the portfolio to top up his small pension from then on. What should the advisor do first?",
      ["Discuss the conflict between his objective and his time horizon, then document a reconciled KYC",
       "Record aggressive growth as chosen, since clients are entitled to set their own objectives",
       "Change his objective to income without discussing it, because his retirement is so close",
       "Record aggressive growth for now, with a note to revisit his objectives when he retires"],
      "When KYC elements conflict, the advisor must explore and resolve the inconsistency with the client before making suitability determinations.", "s"],
    ["Rita and Sam, both 50, open a joint account for retirement savings. They have the same goals and a 15-year time horizon. On the KYC form, Rita rates her risk tolerance as low, while Sam rates his as high and says he'll make most of the decisions. What is the best approach?",
      ["Discuss it with both and agree on a profile, or consider separate accounts",
         "Use Sam's high tolerance, since he has said he'll make most of the decisions",
         "Use Rita's low tolerance without discussing it with either of them, as the safest option",
         "Average the two tolerances, record 'medium,' and invest the account on that basis"],
      "Suitability for a joint account must reflect both holders. Differences should be discussed openly and the agreed profile documented.", "s"],
    ["Alicia's KYC was updated four months ago. During a routine call about a dividend, she mentions that next month she'll quit her job as a nurse to open a bakery, using about a third of her investment account to start the business. What should her advisor do?",
      ["Update her KYC now and review the account's suitability",
       "Wait for her next scheduled KYC update in about 32 months",
       "Wait until she has actually left her job, then update her KYC",
       "Sell a third of her holdings right away to fund the bakery"],
      "A significant change in circumstances, such as income, liquidity needs or time horizon, triggers a KYC update and suitability review, whatever the schedule.", "s"],
    ["Beatrice, 58, transfers her account from another dealer. Her KYC shows a medium risk tolerance and moderate growth objective. The account holds 40% in one speculative biotech stock that she bought on a friend's tip, and she says she wants to keep it. What is the most appropriate course of action?",
      ["Assess suitability, explain the concentration risk, and document her choice",
         "Sell the biotech position right away, because it makes her whole account unsuitable",
         "Refuse to accept the transfer until she agrees to diversify her holdings",
         "Accept the transfer without comment, since the stock was bought at another firm"],
      "Transfers in trigger a suitability review. The advisor must raise concerns; if the client keeps the position after advice, her decision is documented.", "s"],
    ["Helena, 67, has $10 million in investments and a generous indexed pension that covers all her expenses. When discussing her portfolio, she says even a 5% decline would make her 'physically ill' and that she checks prices daily. How should her risk profile be determined?",
      ["It should reflect her low tolerance, even though her capacity is high",
       "It should be high, because her capacity to absorb losses is very high",
       "It should be medium, averaging her low tolerance and high capacity",
       "It doesn't apply, because she's a very high-net-worth client"],
      "Risk profile considers both willingness (tolerance) and ability (capacity) to accept risk. When they differ, the lower one generally governs. Here that's her tolerance.", "s"],
    ["An advisor is reviewing whether a leveraged strategy (borrowing $100,000 to invest) suits four different clients. Which client's situation most strongly indicates that leverage is unsuitable?",
      ["Her income barely covers her expenses and she has no emergency savings",
       "He has a 25-year horizon, a stable public-sector job and no other debts",
       "She understands that leverage magnifies gains and losses, and has used it before",
       "He has a large net worth, most of it in liquid, diversified investments"],
      "Leverage requires the ability to service the loan and absorb losses. Tight cash flow and no reserves make it unsuitable.", "s"],
    ["A dealer's product shelf consists only of mutual funds managed by its own affiliate. A new client asks whether the firm will look at funds from other companies when making recommendations. Under the Client Focused Reforms, what must the firm do?",
      ["Disclose that it offers only proprietary products, and still put the client's interest first",
         "Nothing special, because proprietary funds are regulated exactly the same way as other funds",
         "Stop offering proprietary products, since they always create conflicts it can't manage",
         "Obtain the client's written consent to invest only in the firm's proprietary funds"],
      "Firms must disclose shelf limitations, and suitability must still put the client's interest first within what the firm offers.", "s"],
    ["An advisor recommends Fund X, with a 1.9% MER, to a client. A very similar fund with a 0.6% MER, Fund Y, is also available at the firm. The client asks whether the advisor was required to recommend the cheaper fund. Which statement is most accurate?",
      ["Not necessarily, but the higher cost must be justified as being in the client's interest",
       "Yes; when two funds are similar, the advisor must always recommend the cheaper one",
       "No; cost isn't relevant as long as both funds match the client's stated risk profile",
       "No; the advisor only has to disclose the MER difference in writing after the trade"],
      "Costs are a suitability factor. The cheapest option isn't mandatory, but a higher-cost choice must be justified in the client's interest.", "s"],
    ["Margaret, 72, has a $500,000 RRIF. She takes only the minimum withdrawal each year, has a defined benefit pension that covers her expenses, and expects to leave much of the RRIF to her grandchildren. How should her time horizon be assessed?",
      ["Consider when each portion will be needed; much of it may be needed much later",
       "Treat it as under one year, because she is already making RRIF withdrawals",
       "Treat it as zero, because clients over 70 should only hold short-term investments",
       "Base it only on the size of her required minimum withdrawal for the current year"],
      "Time horizon is about when the money will be needed. A retiree drawing slowly may have a long horizon for much of the portfolio.", "s"],
    ["A client holds five different 'diversified' mutual funds from five fund companies. On review, the advisor finds that each fund has more than 35% of its assets in the same five Canadian banks. What should the advisor recognize?",
      ["The portfolio may be concentrated in one sector, even though each fund is diversified",
       "There's no concentration risk, because the client owns five different funds",
       "Concentration only matters for individual stocks, not for mutual fund holdings",
       "The portfolio is ideal, because Canadian banks are considered low-risk investments"],
      "Suitability considers concentration at the account level, including overlapping exposure through funds.", "s"],
    ["Yvonne has a medium risk profile and a 15-year horizon. She calls with an unsolicited order to buy a speculative junior mining stock she read about online. The purchase would be 3% of her account, and she understands it could go to zero. What is the best approach?",
      ["Assess suitability for the whole account, explain the risks, and document the outcome",
       "Refuse the order, because a medium-risk client can never hold speculative securities",
       "Accept the order without any assessment, because the client initiated it herself",
       "Accept the order only after changing her risk profile to high on the KYC form"],
      "Accepting an instruction triggers a suitability determination. A small speculative position may be suitable in the context of the whole account.", "s"],
    ["A compliance review of an advisor's files finds that each recommendation record shows the security, quantity, price and date, but nothing else. Under suitability requirements, what is missing?",
      ["A record of how each recommendation suits the client, including alternatives considered",
         "The client's signature on every recommendation, confirming that she agreed to each one",
         "A copy of each security's prospectus or Fund Facts, attached to the file",
         "Nothing, since trade details are all of the documentation that suitability rules require"],
      "Firms must keep records showing how suitability determinations were made.", "s"],
    ["Which situation requires the advisor to review the suitability of a client's account, even though the client hasn't asked for anything?",
      ["The client's account is reassigned to a new advisor after the old one retires",
       "The stock market rises 3% in a week and the client's account rises with it",
       "The client receives her regular quarterly statement in the mail",
       "A fund company announces its regular annual year-end distribution"],
      "Suitability triggers include account transfers, KYC changes, a change of representative, changes in a security that may make it unsuitable, and periodic reviews."],
    ["A client's KYC shows a low risk tolerance. Her advisor believes a growth fund would serve her better. Without speaking to her, he changes her risk tolerance on the KYC form to 'medium' and buys the fund. What is the main problem?",
      ["The KYC no longer reflects her actual situation, which is serious misconduct",
         "A medium risk tolerance isn't allowed for clients with low incomes",
         "The change should have waited until her next scheduled annual KYC review meeting",
         "The client should have signed the trade ticket for the growth fund"],
      "KYC must accurately reflect the client. Altering it to justify a recommendation is a serious breach.", "s"],
    ["A conservative client holds a bond fund that her advisor recommended last year. Today the advisor learns that the fund has changed its mandate and now invests mainly in high-yield corporate bonds. The client's KYC hasn't changed. What should the advisor do?",
      ["Review whether the fund is still suitable for her risk profile",
       "Nothing, until the client's next scheduled KYC update",
       "Sell the fund immediately for every client who holds it",
       "Notify CIRO that the fund has changed its investment strategy"],
      "A change in a security that could make it unsuitable triggers a suitability review.", "s"],
    ["Ruth, 84, asks to wire $60,000 to a man she met online who is 'stranded overseas' and needs money to come home. She becomes upset when her advisor asks questions, and says he's her fiancé. The firm reasonably believes she's being financially exploited. What is the most appropriate action?",
      ["Place a temporary hold, tell her why, and consider contacting her trusted contact",
         "Process the wire, since clients have the right to spend their own money as they choose",
         "Freeze her account permanently until a court appoints a guardian to manage it",
         "Process the wire, then report the transaction to OBSI as a suspected scam"],
      "Firms may place a temporary hold when they reasonably believe a vulnerable client is being financially exploited, with notice to the client and ongoing review.", "s"],
    ["Which statement best describes the purpose of Know Your Product (KYP) at the individual advisor level?",
      ["Understanding a product's features, risks and costs well enough to assess suitability",
         "Investing personally in each product before recommending it to any client",
         "Recommending only products that carry a low or low-to-medium risk rating",
         "Reading the full prospectus of every security that is available on the firm's product shelf"],
      "KYP lets advisors make informed suitability determinations. Firms also have KYP duties: assessing, approving and monitoring products."],
    ["Kim, 35, keeps $30,000 in her investment account as her only emergency fund. Her income is stable, but she rents and has no other savings. She asks her advisor to move all of it into an equity fund, because 'cash earns nothing.' What is the main suitability concern?",
      ["Liquidity: she may need the money just when equity prices are down",
       "Concentration: equity funds generally hold too few individual stocks",
       "Cost: equity funds always charge higher fees than savings accounts",
       "Tax: equity funds generate large amounts of fully taxable interest"],
      "Emergency money needs safety and liquidity; equities could force a sale at a loss.", "s"],
    ["Jamal, 40, has a 20-year horizon, a moderate risk tolerance, a stable income and an emergency fund. He asks for a recommendation for his RRSP. Which portfolio is most suitable?",
      ["A diversified balanced portfolio with a meaningful equity weighting",
       "Mostly GICs and high-interest savings, to preserve his capital",
       "Mostly small-cap and emerging-market equities, for maximum growth",
       "A single dividend stock with a long record of dividend increases"],
      "A long horizon plus moderate tolerance supports growth with diversification, not extremes.", "s"],
    ["Over six months, an advisor asks a client three times to update his KYC information, which is five years old. The client refuses each time, saying it's 'none of your business,' but keeps asking for stock recommendations. What is the most appropriate response?",
      ["Explain that without current KYC he can't get recommendations, and follow firm policy",
         "Keep making recommendations based on the KYC information he gave five years ago",
         "Estimate his current information from his recent trading activity and deposits",
         "Close the account right away and transfer the assets out without any explanation"],
      "Suitability depends on current KYC. Firms may restrict an account when KYC can't be kept up to date.", "s"],
    ["Which piece of information is part of a client's 'financial circumstances' for KYC purposes?",
      ["Annual income, net worth and liquid assets", "Investment knowledge and trading experience", "Risk tolerance and investment time horizon", "Marital status and number of dependants"],
      "Financial circumstances cover income, assets, liabilities and liquidity. Knowledge, risk profile and personal circumstances are separate KYC components."],
    ["Under the Client Focused Reforms, a suitability determination must consider the potential impact of costs. Which situation best shows an advisor doing this?",
      ["Comparing the costs of similar options and explaining why one is better for the client",
         "Listing the commission on the trade confirmation that is sent after the purchase",
         "Recording the fund's MER in the client's file at some point after the purchase is made",
         "Waiving the commission on every trade, so that costs no longer need to be considered"],
      "Considering costs means weighing them as part of the recommendation, not just disclosing them afterward."]
  ]);

  add("recs", [
    ["Gwen, 66, is retired with a modest pension. She needs $2,000 a month from her $450,000 portfolio for the next 25 years or more. She's worried about another market crash, but also that rising prices will eat into her income over time. Which approach is most suitable?",
      ["Quality bonds or a GIC ladder for near-term income, plus some dividend stocks for inflation",
         "100% GICs to remove market risk completely, renewing each one as it matures over time",
         "100% dividend-paying equities, to maximize both her income and her long-term growth",
         "A single high-yield bond fund paying the highest current income available"],
      "She needs predictable income, protection from large losses and some growth to keep pace with inflation; a blend addresses all three.", "s"],
    ["Owen, 30, earns a modest income while finishing an accounting designation. He expects his income to double within three years. He has $6,000 to save for retirement this year and has unused room in both his RRSP and TFSA. Which recommendation is most appropriate?",
      ["A TFSA now, or an RRSP contribution with the deduction saved for a higher-income year",
       "An RRSP contribution, claiming the full deduction this year at his current tax rate",
       "A non-registered account, so that he keeps the money completely flexible",
       "Waiting until his income rises before saving anything for retirement"],
      "RRSP deductions are worth more at higher tax rates. The deduction can be carried forward, or a TFSA can be used now.", "s"],
    ["A client holds government bonds, Canadian dividend stocks and U.S. dividend stocks. She has a non-registered account, a TFSA and an RRSP, each with room for any of these holdings. Which placement is generally most tax-efficient?",
      ["U.S. stocks in the RRSP, bonds in the RRSP or TFSA, Canadian dividend stocks in the non-registered account",
         "Canadian dividend stocks in the RRSP, U.S. stocks in the TFSA, bonds in the non-registered account",
         "Everything in the non-registered account, saving the registered room for future years",
         "Bonds in the non-registered account, with all of the stocks split evenly between the TFSA and the RRSP"],
      "Interest is the most heavily taxed income. Canadian dividends get the dividend tax credit. The RRSP avoids U.S. withholding tax on U.S. dividends.", "s"],
    ["Jun and Mei have a newborn and can set aside $2,500 a year toward their child's future education. They have unused room in their TFSAs and RRSPs. Which recommendation gives them the greatest benefit for this goal?",
      ["$2,500 a year in an RESP, for the maximum basic CESG of $500",
       "$2,500 a year in a TFSA, since withdrawals will be tax-free",
       "$2,500 a year in a spousal RRSP, withdrawn later for tuition",
       "A 10-year strip bond bought each year in a non-registered account"],
      "The CESG adds 20% on the first $2,500 a year, an immediate return that other accounts can't match for education savings.", "s"],
    ["Carlos, 45, has $40,000 of credit card debt at 21% interest and $40,000 in a savings account. His income is stable. He asks his advisor which mutual funds he should buy with the savings. What is the best first recommendation?",
      ["Use the savings to pay down the high-interest debt, keeping a modest emergency fund",
       "Invest the savings in a growth fund, since it is expected to return about 8% a year",
       "Invest half in a balanced fund, and keep the other half in the savings account",
       "Borrow more at a lower rate to invest, since markets usually rise over time"],
      "Paying off 21% debt is a guaranteed return that no suitable investment can reliably beat.", "s"],
    ["Hannah, 38, wants exposure to large U.S. companies for her 20-year RRSP portfolio. She has heard that the exchange rate can swing returns sharply and wants to avoid that. She is cost-conscious. Which recommendation is most suitable?",
      ["A low-cost, currency-hedged U.S. equity ETF",
       "An unhedged U.S. equity ETF bought in U.S. dollars",
       "A Canadian bank stock with large U.S. operations",
       "A U.S.-dollar money market fund held for 20 years"],
      "Currency hedging removes most of the exchange-rate effect on returns.", "s"],
    ["Diane, 52, inherits $200,000. Her long-term plan calls for a balanced portfolio, but she's anxious about investing it all at once and then watching the market fall. She doesn't need the money for at least 15 years. Which approach best addresses her concern while keeping to the plan?",
      ["Invest in equal instalments over several months (dollar-cost averaging)",
         "Keep it all in cash, and invest only once the market has clearly dropped",
         "Put it all in GICs permanently, so that it can never lose value",
         "Invest it all in equities right away to make up for lost time"],
      "Dollar-cost averaging reduces timing regret while moving toward the target allocation.", "s"],
    ["Farah turns 71 this year and has a large RRSP. She also receives CPP, OAS and a company pension, and doesn't need more income yet. She wants to keep her taxes as low as possible. What should she be told?",
      ["She must convert it (e.g., to a RRIF) by year-end; minimum withdrawals start next year",
         "She can keep contributing to her RRSP until the end of the year she turns 75",
         "She must withdraw the full RRSP balance in cash before December 31 this year",
         "She can transfer the RRSP into her TFSA tax-free, as long as she does it before year-end"],
      "An RRSP must mature by the end of the year the holder turns 71. A RRIF defers tax, with minimum withdrawals starting the next year.", "s"],
    ["Ben, 29, rents an apartment and plans to buy his first home in about three years. He has $15,000 saved, a stable job, and has never owned a home. He wants a tax-efficient way to save for the down payment. Which recommendation is most appropriate?",
      ["An FHSA holding low-risk, short-term investments",
       "An FHSA holding mostly small-cap equities for growth",
       "An RESP, naming himself as the beneficiary",
       "A non-registered account holding a 10-year bond"],
      "The FHSA gives a deduction and tax-free qualifying withdrawals. A 3-year horizon calls for low-risk, liquid holdings.", "s"],
    ["Lorraine, 74, wants a specific $150,000 investment to go to her daughter quickly when she dies, without passing through her estate. She also wants some protection of her principal if markets fall. Which recommendation best fits?",
      ["A segregated fund contract naming her daughter as beneficiary",
       "A joint account with her daughter, held as tenants-in-common",
       "A mutual fund held in her name, left to her daughter in her will",
       "A margin account with her daughter given trading authority"],
      "Segregated funds can pass directly to a named beneficiary, bypassing the estate, and include maturity and death benefit guarantees.", "s"],
    ["A client needs to pay $20,000 of tuition at the start of each of the next four years for her son's university program. She wants to know the money will be there when each payment is due. Which structure best matches the need?",
      ["A ladder of high-quality bonds or GICs maturing in each of the next four years",
         "A long-term bond fund, redeeming enough units each year to cover the tuition bill",
         "A single 10-year bond, selling part of the position each year as needed",
         "A high-yield bond ETF, using the extra income to cover the payments"],
      "Matching maturities to known cash needs removes price and reinvestment uncertainty.", "s"]
  ]);

  add("econ", [
    ["During a severe recession, with unemployment rising quickly, an economist argues that the government should increase infrastructure spending and run a deficit to boost aggregate demand. This view is most closely associated with which school of thought?",
      ["Keynesian economics", "Monetarism", "Supply-side economics", "Classical laissez-faire economics"],
      "Keynesians favour active fiscal policy to manage demand, especially in downturns.", "s"],
    ["An economist argues that inflation is caused mainly by excessive growth in the money supply, and that the central bank should aim for steady, predictable money growth rather than reacting to every change in the economy. Which view is this?",
      ["Monetarism", "Keynesian economics", "Supply-side economics", "Modern portfolio theory"],
      "Monetarists, associated with Milton Friedman, focus on the money supply as the key driver of inflation."],
    ["A government cuts marginal tax rates and reduces business regulation. It argues that this will encourage people to work, save and invest, and increase the economy's ability to produce goods and services over time. This policy reflects which approach?",
      ["Supply-side economics", "Keynesian economics", "Monetarism", "Demand management through deficit spending"],
      "Supply-side policies try to boost output by improving incentives to produce."],
    ["With inflation well above target, the Bank of Canada raises its target for the overnight rate by 0.5%. Which sequence of effects is most likely?",
      ["Borrowing costs rise, spending slows, the dollar tends to firm, and inflation eases",
         "Borrowing costs fall, spending rises, the dollar tends to weaken, and inflation rises",
         "Bond prices rise, mortgage rates fall, and housing activity picks up within a few weeks",
         "Government spending rises automatically, fully offsetting the effect of the increase"],
      "Tighter policy works through higher borrowing costs, slower demand and a firmer currency."],
    ["Over several months, 2-year Government of Canada yields rise above 10-year yields, although unemployment is still low and consumer spending remains strong. What are bond markets most likely signalling?",
      ["An expected slowdown, with interest rate cuts to follow",
       "Accelerating growth and rising long-term inflation",
       "That long-term bonds have become riskier than short-term bonds",
       "Nothing, because the yield curve has no link to the economy"],
      "An inverted yield curve has historically preceded recessions, as markets expect future rate cuts.", "s"],
    ["A company's statement of comprehensive income shows net income of $50 million. Its other comprehensive income includes a $5 million gain from translating a foreign subsidiary's results into Canadian dollars. What is its total comprehensive income?",
      ["$55 million", "$50 million", "$45 million", "$5 million"],
      "Comprehensive income = net income + other comprehensive income (such as certain currency translation gains).", "c"],
    ["An auditor issues a 'qualified' opinion on a company's annual financial statements. What does this mean?",
      ["The statements are fairly presented except for a specific matter the auditor describes",
       "The statements are fairly presented in all material respects, with no exceptions",
       "The statements are materially misstated and shouldn't be relied on by investors",
       "The auditor couldn't gather enough evidence to form any opinion on the statements"],
      "Unmodified = fairly presented; qualified = 'except for'; adverse = not fairly presented; disclaimer = no opinion."],
    ["Which statement about a reporting issuer's interim (quarterly) financial statements is correct?",
      ["They needn't be audited, but must disclose if the auditor hasn't reviewed them",
         "They must be fully audited, just like the company's annual statements",
         "They're optional for companies whose shares are listed on the Toronto Stock Exchange",
         "They need only be filed with the issuer's stock exchange, not regulators"],
      "Interim statements are part of continuous disclosure. They're generally unaudited, with a notice if not reviewed by the auditor."],
    ["The CEO and two other senior officers of a listed company team up to make a take-over bid for all the shares they don't already own. Compared with an ordinary take-over bid, what additional protection is generally required for minority shareholders?",
      ["An independent formal valuation and enhanced disclosure",
       "Approval from CIRO before the bid can be launched",
       "A guaranteed price at least 50% above the market price",
       "A ban on the insiders buying any more shares"],
      "Insider bids raise conflict concerns, so securities rules require extra protections such as formal valuations and enhanced disclosure.", "s"],
    ["A company has excess cash and makes a formal offer to all of its shareholders to buy back up to 10% of its shares at a fixed price. What is this called?",
      ["An issuer bid", "A take-over bid", "An insider bid", "A rights offering"],
      "An issuer bid is an offer by an issuer to acquire its own securities. Normal course issuer bids made through the exchange are exempt from the formal bid rules."],
    ["Helen receives the final prospectus for a new share issue on Monday and buys 1,000 shares. On Thursday she changes her mind and asks to cancel the purchase. The prospectus contains no misrepresentation. Which statement is most accurate?",
      ["Her 2-business-day withdrawal right has expired, so she generally can't cancel",
         "She can cancel at any time within 30 days of receiving the prospectus",
         "She can cancel only if the shares have fallen below the price she paid for them",
         "She can sue for damages, because the purchase was made so recently"],
      "The withdrawal right lasts 2 business days after receiving the prospectus. Rescission or damages require a misrepresentation.", "s"],
    ["An analyst is reviewing four transactions a company is considering. Which one would cause the company's current ratio to fall?",
      ["Using cash to repay a long-term loan early", "Issuing new common shares for cash", "Borrowing long-term and keeping the cash", "Collecting cash from its accounts receivable"],
      "Paying long-term debt with cash reduces current assets without reducing current liabilities. Collecting receivables swaps one current asset for another.", "c"],
    ["Company A and Company B are in the same industry and report the same net income. A's return on equity is 25%; B's is 12%. On further review, an analyst finds that A has far more debt than B. What is the best conclusion?",
      ["A's higher ROE partly reflects leverage, which also increases its financial risk",
       "A is clearly the better-managed company and should be the preferred investment",
       "B must be overvalued by the market, since its ROE is so much lower than A's",
       "ROE can't be meaningfully compared between companies in the same industry"],
      "Leverage reduces equity and raises ROE, but adds risk. DuPont analysis separates the drivers.", "s"],
    ["An analyst is trying to forecast where the Canadian economy is headed over the next year. Which data release would she most likely treat as a LEADING indicator?",
      ["A sharp drop in building permits and housing starts", "A rise in the national unemployment rate last month", "An increase in unit labour costs", "A longer average duration of unemployment this year"],
      "Housing activity tends to turn before the broader economy. Unemployment and labour costs typically lag.", "s"],
    ["Investors require a 2% real return on a 10-year bond and expect inflation to average 3% a year. Using the Fisher relationship, what nominal yield will they demand?",
      ["About 5%", "About 1%", "About 3%", "About 6%"],
      "Nominal ≈ real return + expected inflation = 2% + 3%.", "c"],
    ["A company's net income has grown steadily for three years. Over the same period, its cash flow from operations has fallen each year, and its accounts receivable have more than doubled while sales grew only 10%. What should an analyst conclude?",
      ["Earnings quality may be poor; revenue may be recognized before cash is collected",
         "The company is becoming more efficient at turning its profits into operating cash",
         "The company should increase its dividend, given its steady earnings growth",
         "The trend has no bearing on the company's value, as long as profits rise"],
      "Profits that don't turn into cash are a classic warning sign.", "s"]
  ]);

  add("fin", [
    ["An investor wants to understand management's explanation of a company's results, the main risks it faces and its outlook. Besides the annual financial statements, which document should she read?",
      ["The MD&A", "The auditor's report", "The statement of changes in equity", "The early warning report"],
      "Management's Discussion and Analysis gives management's narrative view of the results.", "s"],
    ["A company reports a large one-time gain from selling a division, which more than doubles its net income for the year. An analyst is estimating the company's value using a price-to-earnings approach. What should she generally do?",
      ["Adjust for the one-time gain and focus on sustainable earnings",
       "Use the higher reported earnings, since they were audited",
       "Ignore the income statement and value the company on book value",
       "Assume the gain will repeat each year and value the shares on that basis"],
      "Valuation focuses on recurring, sustainable earnings.", "s"],
    ["Which financial statement shows the dividends a company declared and the new shares it issued during the year?",
      ["Statement of changes in equity", "Statement of comprehensive income", "Notes on accounting policies", "Independent auditor's report"],
      "The statement of changes in equity reconciles opening and closing equity, including dividends and share issues."],
    ["A company issues $100 million of convertible bonds. Analysts expect most of them to be converted into common shares within a few years. What will conversion most likely do to existing shareholders' earnings per share?",
      ["Reduce it, because more shares will share the earnings (dilution)",
       "Increase it, because the company will no longer pay any bond interest",
       "Leave it unchanged, since conversion only affects the balance sheet",
       "Increase it, because the company's debt-to-equity ratio will improve"],
      "Diluted EPS reflects the extra shares issued on conversion. Lower interest costs only partly offset this.", "c"]
  ]);
})();
